### ISSUE TITLE
Handshake failed. Timeout in handshake with retry.

### ISSUE THREAD

**Issue by browkin** [getcursor/cursor#1071]
Subscribed to cursor and really like it so far. We think to use it in our company, so I am testing it currently. One of the most interesting features was codebase indexing, but that is currently not working for us. We get this error message:

Why could that be? Our repo is hosted in azure. Everything works except the indexing.

2023-11-14 08:25:06.922 [info] Setting indexing intent to should-index
2023-11-14 08:25:06.928 [info] Creating merkle client.
2023-11-14 08:25:06.928 [info] Done creating merkle client.
2023-11-14 08:25:06.928 [info] Doing a startup handshake.
2023-11-14 08:25:07.087 [info] Finished initializing merkle tree in 158.7222000360489 ms.
2023-11-14 08:25:07.088 [info] Doing the initial handshake with hash: 62c83d7aa82d60daeb1065e08896106aa1a748b995b00df73a4b55ad6078554a
2023-11-14 08:27:51.649 [error] Handshake failed:
2023-11-14 08:27:51.649 [error] Error: timeout in handshake with retry
	at e.RepoClientMultiplexer.handshakeWithRetry (c:\Users\abc\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:1077859)
	at async u.getServerStatus (c:\Users\abc\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:1090861)
	at async u.startIndexingRepository (c:\Users\abc\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:1093021)
2023-11-14 08:27:51.649 [error] Handshake failed.
2023-11-14 08:27:51.650 [info] Indexing job successfully done.

**Comment by jakobFNF** [comment]
What version of Cursor are you using? You can check in "About".

![image](https://github.com/getcursor/cursor/assets/74077124/b58e5109-487a-4f84-b154-0046823785a3)

**Comment by browkin** [comment]
@jakobFNF 

Version: 0.15.4
VSCode Version: 1.83.1
Commit: 38beb02b65eaf9ca5bddaa8f8d6ac40c7529af20
Date: 2023-11-14T07:20:54.057Z
Electron: 25.8.4
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by danperks** [comment]
Hey, if your still facing this, please comment in #2035
