### ISSUE TITLE
TS Server fatal error:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by UmarLE** [getcursor/cursor#1075]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.2.2

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
RangeError: Maximum call stack size exceeded
    at parsePrimaryExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34611:34)
    at parseMemberExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34078:24)
    at parseLeftHandSideExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34072:82)
    at parseUpdateExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34047:24)
    at parseUnaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33966:32)
    at parseBinaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33888:25)
    at parseAssignmentExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33559:18)
    at parseExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33524:16)
    at doOutsideOfContext (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31201:12)
    at allowInAnd (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31222:12)
    at parseParenthesizedExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34669:24)
    at parsePrimaryExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34631:16)
    at parseMemberExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34078:24)
    at parseLeftHandSideExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34072:82)
    at parseUpdateExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34047:24)
    at parseUnaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33966:32)
    at parseBinaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33888:25)
    at parseAssignmentExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33559:18)
    at parseExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33524:16)
    at doOutsideOfContext (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31201:12)
    at allowInAnd (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31222:12)
    at parseParenthesizedExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34669:24)
    at parsePrimaryExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34631:16)
    at parseMemberExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34078:24)
    at parseLeftHandSideExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34072:82)
    at parseUpdateExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34047:24)
    at parseUnaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33966:32)
    at parseBinaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33888:25)
    at parseAssignmentExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33559:18)
    at parseExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33524:16)
    at doOutsideOfContext (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31201:12)
    at allowInAnd (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31222:12)
    at parseParenthesizedExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34669:24)
    at parsePrimaryExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34631:16)
    at parseMemberExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34078:24)
    at parseLeftHandSideExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34072:82)
    at parseUpdateExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34047:24)
    at parseUnaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33966:32)
    at parseBinaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33888:25)
    at parseAssignmentExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33559:18)
    at parseExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33524:16)
    at doOutsideOfContext (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31201:12)
    at allowInAnd (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31222:12)
    at parseParenthesizedExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34669:24)
    at parsePrimaryExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34631:16)
    at parseMemberExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34078:24)
    at parseLeftHandSideExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34072:82)
    at parseUpdateExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34047:24)
    at parseUnaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33966:32)
    at parseBinaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33888:25)
    at parseAssignmentExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33559:18)
    at parseExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33524:16)
    at doOutsideOfContext (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31201:12)
    at allowInAnd (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31222:12)
    at parseParenthesizedExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34669:24)
    at parsePrimaryExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34631:16)
    at parseMemberExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34078:24)
    at parseLeftHandSideExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34072:82)
    at parseUpdateExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34047:24)
    at parseUnaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33966:32)
    at parseBinaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33888:25)
    at parseAssignmentExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33559:18)
    at parseExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33524:16)
    at doOutsideOfContext (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31201:12)
    at allowInAnd (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31222:12)
    at parseParenthesizedExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34669:24)
    at parsePrimaryExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34631:16)
    at parseMemberExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34078:24)
    at parseLeftHandSideExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34072:82)
    at parseUpdateExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34047:24)
    at parseUnaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33966:32)
    at parseBinaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33888:25)
    at parseAssignmentExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33559:18)
    at parseExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33524:16)
    at doOutsideOfContext (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31201:12)
    at allowInAnd (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31222:12)
    at parseParenthesizedExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34669:24)
    at parsePrimaryExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34631:16)
    at parseMemberExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34078:24)
    at parseLeftHandSideExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34072:82)
    at parseUpdateExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34047:24)
    at parseUnaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33966:32)
    at parseBinaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33888:25)
    at parseAssignmentExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33559:18)
    at parseExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33524:16)
    at doOutsideOfContext (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31201:12)
    at allowInAnd (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31222:12)
    at parseParenthesizedExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34669:24)
    at parsePrimaryExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34631:16)
    at parseMemberExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34078:24)
    at parseLeftHandSideExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34072:82)
    at parseUpdateExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34047:24)
    at parseUnaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33966:32)
    at parseBinaryExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33888:25)
    at parseAssignmentExpressionOrHigher (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33559:18)
    at parseExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33524:16)
    at doOutsideOfContext (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31201:12)
    at allowInAnd (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31222:12)
    at parseParenthesizedExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34669:24)
    at parsePrimaryExpression (/Applications/Cursor.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34631:16)
```

VS Code version: Cursor 0.15.5 (069284f607cba9bcfab9af796d80cb3698d9a6e0, 2023-11-15T02:04:58.593Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|14, 14, 12|
|Memory (System)|16.00GB (1.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bundle-size|amb|1.5.0
akonio|Avi|8.0.1
doxdocgen|csc|1.4.0
es7-react-js-snippets|dsz|4.4.3
vscode-todo-plus|fab|4.19.1
codespaces|Git|1.16.2
react-native-snippet|jun|0.5.6
vscode-docker|ms-|1.28.0
vscode-react-native|msj|1.12.1
color-highlight|nau|2.5.0
vscode-versionlens|pfl|1.9.2
material-icon-theme|PKi|4.31.0
toggle-case|Pra|0.1.2
code-spell-checker|str|3.0.1
vscode-gradle|vsc|3.13.4

(2 theme extensions excluded)

</details>

**Comment by jakobFNF** [comment]
This doesn't seem to be Cursor-specific. Does the same issue persist in regular VSCode?

Here's a very similar issue: https://github.com/microsoft/vscode/issues/194877
