### ISSUE TITLE
Multiple functionality (test running, test discovery, restarting jupyter) only works with a 30s delay

### ISSUE THREAD

**Issue by ldorigo** [getcursor/cursor#1178]
I haven't been able to repro very consistently, as it did not do it after a fresh install of cursor and sometimes it seems to magically work after I e.g. clear caches , but most of the time there is a 30s delay whenever I run/debug tests via the tests explorer UI.

The only seemingly relevant logs I see are:

![image](https://github.com/getcursor/cursor/assets/8631181/b69405ff-625c-4976-98d4-046b06ddb969)

(that error happens every time I try to run tests)

**Comment by ldorigo** [comment]
I was having trouble restarting jupyter notebooks and realized it was the same issue. See relevant logs:

```
08:40:45.412 [error] Jupyter Extension (Error in requestVariables, method:requestVariables): Error: Canceled future for execute_request message before replies were done
    at oi.dispose (~/.cursor/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-x64/dist/node_modules/@jupyterlab/services/lib/kernel/nonSerializingKernel.js:11:22379)
    at ~/.cursor/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-x64/dist/node_modules/@jupyterlab/services/lib/kernel/nonSerializingKernel.js:11:93953
    at Map.forEach (<anonymous>)
    at n._clearKernelState (~/.cursor/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-x64/dist/node_modules/@jupyterlab/services/lib/kernel/nonSerializingKernel.js:11:93939)
    at n.dispose (~/.cursor/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-x64/dist/node_modules/@jupyterlab/services/lib/kernel/nonSerializingKernel.js:11:87407)
    at ~/.cursor/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-x64/dist/extension.node.js:264:13027
    at kn (~/.cursor/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-x64/dist/extension.node.js:80:9941)
    at s_.start (~/.cursor/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-x64/dist/extension.node.js:264:13003)
    at s_.restart (~/.cursor/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-x64/dist/extension.node.js:264:12784)
    at ZT.restart (~/.cursor/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-x64/dist/extension.node.js:235:32913)
    at xT.restart (~/.cursor/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-x64/dist/extension.node.js:235:68901)
    at Function.wrapKernelMethodImpl (~/.cursor/extensions/ms-toolsai.jupyter-2023.11.1100101639-linux-x64/dist/extension.node.js:265:57604) {
  vslsStack: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {}
  ]
}
08:41:15.491 [warn] Failed to get activated env vars for ~/.venvs/langchain_tests_venv/bin/python in 30079ms
08:41:15.494 [error] Unable to determine site packages path for python ~/.venvs/langchain_tests_venv/bin/python (Venv)
08:41:15.530 [info] Process Execution: ~/.venvs/langchain_tests_venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
```

So it's still a problem with getting the environment variables, and still results in 30s delay before restarting the notebook...
