### ISSUE TITLE
[Solved] Latest update breaks WSL

### ISSUE THREAD

**Issue by lukaemon** [getcursor/cursor#1338]
Was working perfectly. Stop working right after 30.2 update. 

```
[2024-03-22 02:26:53.711] Downloading VS Code Server stable - 1d91a66cfe2b853adc2155d9f0373c8b21a549b0 into C:\Users\lucas\AppData\Local\Temp\vscode-remote-wsl\1d91a66cfe2b853adc2155d9f0373c8b21a549b0\vscode-server-stable-linux-x64.tar.gz.
[2024-03-22 02:26:53.942] Unable to download server on client side: Error: Request downloadRequest failed unexpectedly without providing any details.. Will try to download on WSL side.
[2024-03-22 02:26:53.942] NodeExecServer run: C:\Windows\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 1d91a66cfe2b853adc2155d9f0373c8b21a549b0 stable cursor-server .cursor-server --host=127.0.0.1 --port=0 --connection-token=1380241341-860469932-3871636487-1650546893 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all'
[2024-03-22 02:26:54.195] Setting up server environment: Looking for /home/lukaemon/.cursor-server/server-env-setup. Not found.
[2024-03-22 02:26:54.195] WSL version: 5.15.146.1-microsoft-standard-WSL2 Ubuntu
[2024-03-22 02:26:54.195] Updating VS Code Server to version 1d91a66cfe2b853adc2155d9f0373c8b21a549b0
[2024-03-22 02:26:54.195] Removing previous installation...
[2024-03-22 02:26:54.195] Installing VS Code Server for x64 (1d91a66cfe2b853adc2155d9f0373c8b21a549b0)
[2024-03-22 02:26:54.195] Downloading:     100%
[2024-03-22 02:26:54.195] Failed
[2024-03-22 02:26:54.195] --2024-03-21 19:26:54--  https://update.code.visualstudio.com/commit:1d91a66cfe2b853adc2155d9f0373c8b21a549b0/server-linux-x64/stable
[2024-03-22 02:26:54.195] Resolving update.code.visualstudio.com (update.code.visualstudio.com)... 13.107.213.70, 13.107.246.70, 2620:1ec:bdf::70, ...
[2024-03-22 02:26:54.195] Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|13.107.213.70|:443... connected.
[2024-03-22 02:26:54.195] HTTP request sent, awaiting response... 404 Not Found
[2024-03-22 02:26:54.195] 2024-03-21 19:26:54 ERROR 404: Not Found.
[2024-03-22 02:26:54.195] 
[2024-03-22 02:26:54.195] ERROR: Failed to download https://update.code.visualstudio.com/commit:1d91a66cfe2b853adc2155d9f0373c8b21a549b0/server-linux-x64/stable to /home/lukaemon/.cursor-server/bin/1d91a66cfe2b853adc2155d9f0373c8b21a549b0-1711074414.tar.gz
```

**Comment by kyleboddy** [comment]
Breaks remote SSH as well. Where can we find old versions?

[Trace  - 02:50:59.530] Server install command stderr:
https://cursor.blob.core.windows.net/remote-releases/0.30.2-1d91a66cfe2b853adc2155d9f0373c8b21a549b0/vscode-reh-linux-arm64.tar.gz:
2024-03-21 19:50:59 ERROR 404: The specified blob does not exist..

[Trace  - 02:50:59.530] Server install command stdout:
Downloading server from 'https://cursor.blob.core.windows.net/remote-releases/0.30.2-1d91a66cfe2b853adc2155d9f0373c8b21a549b0/vscode-reh-linux-arm64.tar.gz'
Error downloading server from https://cursor.blob.core.windows.net/remote-releases/0.30.2-1d91a66cfe2b853adc2155d9f0373c8b21a549b0/vscode-reh-linux-arm64.tar.gz
9f0c1da5883553e5777a9501: start
exitCode==1==
listeningOn====
connectionToken====
logFile==/home/pi/.cursor-server/.1d91a66cfe2b853adc2155d9f0373c8b21a549b0.log==
osReleaseId==ubuntu==
arch==aarch64==
platform==Linux==
tmpDir==/run/user/1000==
9f0c1da5883553e5777a9501: end

[Error  - 02:50:59.531] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (c:\Users\kyle\AppData\Local\Programs\cursor\resources\app\extensions\open-remote-ssh\dist\main.js:1:963961)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async c:\Users\kyle\AppData\Local\Programs\cursor\resources\app\extensions\open-remote-ssh\dist\main.js:1:438343

**Comment by sbarman-mi9** [comment]
This is bad :(

**Comment by biggsun** [comment]
Yes, I also encountered the same problem

**Comment by truell20** [comment]
Thank you for the report and apologies about this. Could you try 0.30.3? Just released a new update that should fix this.

**Comment by lukaemon** [comment]
Solved.
