### ISSUE TITLE
Codebase indexing and AI Review dosen't work

### ISSUE THREAD

**Issue by Dreamzlol** [getcursor/cursor#1468]
1) If you can, please include a screenshot of your problem
Maybe this is related too each other but Codebase indexing dosent work and AI Review also. Handshake failed.

2) Please include the name of your operating system
MacOS Sonoma 14.5

3) If you can, steps to reproduce are super helpful

4) Logs
This is probaly the only thing i can help with, didnt found nothing else in the logs.

2024-05-25 14:30:30.884 [info] Handshake start
2024-05-25 14:30:33.473 [info] Handshake start
2024-05-25 14:30:37.736 [info] Handshake start
2024-05-25 14:30:46.011 [info] Handshake start
2024-05-25 14:31:02.282 [info] Handshake start
2024-05-25 14:31:34.572 [info] Handshake start
2024-05-25 14:32:07.495 [info] Indexing job successfully done or aborted.
2024-05-25 14:32:08.122 [info] Setting indexing intent to should-index
2024-05-25 14:32:08.122 [info] Creating merkle client.
2024-05-25 14:32:08.122 [info] Done creating merkle client.
2024-05-25 14:32:08.122 [info] Doing a startup handshake.
2024-05-25 14:32:08.125 [info] Finished initializing merkle tree in 2.763698998838663 ms.
2024-05-25 14:32:08.125 [info] Doing the initial handshake with hash: f1ccdd73bab494605b9485e61c49775526d1746dbc77af1dc359e86e6140af13
2024-05-25 14:32:08.126 [info] Handshake start
2024-05-25 14:32:10.407 [info] Handshake start
2024-05-25 14:32:14.675 [info] Handshake start
2024-05-25 14:32:22.939 [info] Handshake start
2024-05-25 14:32:39.210 [info] Handshake start
2024-05-25 14:33:11.309 [info] Handshake start
2024-05-25 14:34:15.577 [error] Handshake failed:
2024-05-25 14:34:15.577 [error] Error: timeout in handshake with retry
	at e.RepoClientMultiplexer.handshakeWithRetry (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:995054)
	at async m.getServerStatus (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:1009958)
	at async m.startIndexingRepository (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:1012203)
2024-05-25 14:34:15.577 [error] Handshake failed.
2024-05-25 14:34:15.578 [info] Indexing job successfully done or aborted.

**Comment by Dreamzlol** [comment]
Solved.

**Comment by Balance8** [comment]
How did you solve this, I am having the exact same issue

**Comment by Dreamzlol** [comment]
> How did you solve this, I am having the exact same issue

They solved it if its buggy again then its on the Team too fix it.
