### ISSUE TITLE
Latest Update Ruined SSH

### ISSUE THREAD

**Issue by TheRealJamesRussell** [getcursor/cursor#1492]
I used the built in SSH from cursor.

New Update. Updated.

Try and access my vps?

Forced me to install the VSCode SSH extension.

Don't want to. it's a built in feature.

Built in feature force installs extension

Use extension? Doesn't work. Same error over and over and over:
```
[18:36:44.847] Log Level: 2
[18:36:44.866] SSH Resolver called for "[IP-Address-Redacted]", attempt 1
[18:36:44.868] "remote.SSH.useLocalServer": false
[18:36:44.868] "remote.SSH.useExecServer": true
[18:36:44.868] "remote.SSH.showLoginTerminal": false
[18:36:44.869] "remote.SSH.remotePlatform": {}
[18:36:44.869] "remote.SSH.path": undefined
[18:36:44.869] "remote.SSH.configFile": undefined
[18:36:44.869] "remote.SSH.useFlock": true
[18:36:44.869] "remote.SSH.lockfilesInTmp": false
[18:36:44.869] "remote.SSH.localServerDownload": auto
[18:36:44.870] "remote.SSH.remoteServerListenOnSocket": false
[18:36:44.870] "remote.SSH.showLoginTerminal": false
[18:36:44.871] "remote.SSH.defaultExtensions": []
[18:36:44.871] "remote.SSH.loglevel": 2
[18:36:44.871] "remote.SSH.enableDynamicForwarding": true
[18:36:44.871] "remote.SSH.enableRemoteCommand": false
[18:36:44.871] "remote.SSH.serverPickPortsFromRange": {}
[18:36:44.871] "remote.SSH.serverInstallPath": {}
[18:36:44.878] VS Code version: 0.35.0
[18:36:44.878] Remote-SSH version: remote-ssh@0.110.1
[18:36:44.878] win32 x64
[18:36:44.881] SSH Resolver called for host: [IP-Address-Redacted]
[18:36:44.881] Setting up SSH remote "[IP-Address-Redacted]"
[18:36:44.887] Using commit id "5f9353ed8be369c4ac2b4d43596f5ff281746ec0" and quality "stable" for server
[18:36:44.892] Install and start server if needed
[18:36:46.338] Checking ssh with "C:\[FolderName-Redacted]\Scripts\ssh.exe -V"
[18:36:46.346] Got error from ssh: spawn C:\[FolderName-Redacted]\Scripts\ssh.exe ENOENT
[18:36:46.347] Checking ssh with "C:\[FolderName-Redacted]\ssh.exe -V"
[18:36:46.349] Got error from ssh: spawn C:\[FolderName-Redacted]\ssh.exe ENOENT
[18:36:46.349] Checking ssh with "C:\[FolderName-Redacted]\bin\ssh.exe -V"
[18:36:46.353] Got error from ssh: spawn C:\[FolderName-Redacted]\bin\ssh.exe ENOENT
[18:36:46.354] Checking ssh with "c:\Users\[FolderName-Redacted]\AppData\Local\Programs\cursor\resources\app\bin\ssh.exe -V"
[18:36:46.357] Got error from ssh: spawn c:\Users\[FolderName-Redacted]\AppData\Local\Programs\cursor\resources\app\bin\ssh.exe ENOENT
[18:36:46.357] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[18:36:46.362] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[18:36:46.363] Checking ssh with "C:\Windows\ssh.exe -V"
[18:36:46.365] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[18:36:46.366] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[18:36:46.369] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[18:36:46.369] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[18:36:46.371] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[18:36:46.372] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[18:36:46.488] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[18:36:46.500] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 53300 "[IP-Address-Redacted]" bash
[18:36:46.505] Terminal shell path: C:\Windows\System32\cmd.exe
[18:36:46.787] > ]0;C:\Windows\System32\cmd.exe
[18:36:46.788] Got some output, clearing connection timeout
[18:36:46.817] > Bad owner or permissions on C:\\Users\\[FolderName-Redacted]\\.ssh\\config
> The process tried to write to a nonexistent pipe.
> 
[18:36:48.069] "install" terminal command done
[18:36:48.070] Install terminal quit with output: ]0;C:\Windows\System32\cmd.exeBad owner or permissions on C:\\Users\\[FolderName-Redacted]\\.ssh\\config
[18:36:48.070] Received install output: ]0;C:\Windows\System32\cmd.exeBad owner or permissions on C:\\Users\\[FolderName-Redacted]\\.ssh\\config
[18:36:48.071] Failed to parse remote port from server output
[18:36:48.074] Resolver error: Error: 
	at g.Create (c:\Users\[FolderName-Redacted]\\.cursor\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:499181)
	at t.handleInstallOutput (c:\Users\[FolderName-Redacted]\\.cursor\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:496503)
	at t.tryInstall (c:\Users\[FolderName-Redacted]\\.cursor\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:620069)
	at async c:\Users\[FolderName-Redacted]\\.cursor\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:579927
	at async t.withShowDetailsEvent (c:\Users\[FolderName-Redacted]\\.cursor\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:583233)
	at async k (c:\Users\[FolderName-Redacted]\\.cursor\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:576892)
	at async t.resolve (c:\Users\[FolderName-Redacted]\\.cursor\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:580604)
	at async c:\Users\[FolderName-Redacted]\\.cursor\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:846713
[18:36:48.100] ------
```

**Comment by Sanger2000** [comment]
does this work in vscode?

It looks like there are bad permissions on the .ssh/config file on your device from the error

**Comment by Jonas-Metzger** [comment]
exact same issue. 

Permissions of the config file are definitely not the issue. Not restricted in any way, and unchanged relative to when everything was working under the earlier versions of cursor.

**Comment by markrado123** [comment]
Can anyone send me penultimate version of the cursor for macbook m3?
The latest version is not working with SSH.

**Comment by loranger** [comment]
Same here. 
“More robust SSH” says the changelog…
No more SSH says the 0.35.1 :(

**Comment by sam-ulrich1** [comment]
Work around https://github.com/microsoft/vscode-remote-release/issues/2509#issuecomment-1945824892

**Comment by leerob** [comment]
Thanks for opening this issue! We've moved our community support to the [Cursor Forum](https://forum.cursor.com) where you can get help from both the team and other users.

If this is a specific bug that you can still reproduce, please open a new issue with clear reproduction steps on the forum.

Thanks you!
