### ISSUE TITLE
No inline suggestion

### ISSUE THREAD

**Issue by Entretoize** [getcursor/cursor#1561]
I used Cursor some weeks ago, and like with Github Copilot I had inline suggestion but after I switched back to cursor today, I get no inline suggestion at all.
![Capture d'écran 2024-07-22 155501](https://github.com/user-attachments/assets/dc95d241-42d8-4801-914c-0361cc1ee81a)

**Comment by Entretoize** [comment]
I tried with "Autoz for the model

**Comment by well-balanced** [comment]
I am experiencing the same issue as described above. The issue in my copilot++ vscode output is as follows:

```sh
2024-07-23 10:47:19.670 [info] CURSOR LOG: Error in streaming cpp [canceled] This operation was aborted
2024-07-23 10:47:19.670 [info] CURSOR LOG: restFunc done 07b31505-ce69-4880-8f2d-9496fcb600e7
2024-07-23 10:47:19.737 [info] CURSOR LOG: restFunc initiated 9cf6adcf-57e9-42de-9a30-c2005d17bf4e
2024-07-23 10:47:20.328 [info] CURSOR LOG: Done streaming cpp with id 9cf6adcf-57e9-42de-9a30-c2005d17bf4e
2024-07-23 10:47:20.328 [info] CPP RT LOG: Time taken for streaming cpp 590.67333984375 with request 9cf6adcf-57e9-42de-9a30-c2005d17bf4e
2024-07-23 10:47:20.328 [info] CPP Request Log with id 9cf6adcf-57e9-42de-9a30-c2005d17bf4e
2024-07-23 10:47:20.328 [info] =======>Model input 
2024-07-23 10:47:20.328 [info] =======>Model output 
2024-07-23 10:47:20.328 [info] =======>Debug stream time 8.853957999963313
2024-07-23 10:47:20.329 [info] CURSOR LOG: Error in streaming cpp [unavailable] Stream closed with error code NGHTTP2_PROTOCOL_ERROR
2024-07-23 10:47:20.329 [info] CURSOR LOG: restFunc done 9cf6adcf-57e9-42de-9a30-c2005d17bf4e
2024-07-23 10:47:20.527 [error] ConnectError: [unavailable] HTTP 502
    at /Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:1566517
    at Q (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:1566650)
    at next (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:1569575)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:678289
    at /Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:678173
    at Object.unary (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:1568165)
    at Object.reportDistribution (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:1556179)
```

Any insights or fixes for this issue would be greatly appreciated

**Comment by Entretoize** [comment]
Do you see that in Copilot++ OUTPUT panel ? The only thing I have here is `2024-07-23 07:44:44.333 [info] CURSOR LOG: Finished creating provider!`

**Comment by Entretoize** [comment]
Any news ?

**Comment by AyoCodess** [comment]
inline suggestions have stopped working

**Comment by filipef101** [comment]
```
2024-09-30 15:15:18.725 [info] ExtensionService#_doActivateExtension anysphere.cursor-always-local, startup: false, activationEvent: 'onStartupFinished'
2024-09-30 15:15:21.173 [error] ConnectError: [unknown] File sync is disabled
	at s.from (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:1613266)
	at /Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:1651034
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.unary (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:1631771)
	at async Object.fSConfig (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:1619785)
	at async e.FileSyncClient.fsConfig (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:680982)
	at async e.FileSyncClient.fsConfigUpdate (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:681342)
	at async e.FileSyncClient.initialize (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:677270)
```

**Comment by Thunder7991** [comment]
I also encountered the same problem and reported the same mistakes. Is this problem solved now?

**Comment by dhruv9499** [comment]
facing same problem.
