### ISSUE TITLE
Azure Account timeout, cannot use Azure plugins

### ISSUE THREAD

**Issue by PaulBernhardt** [getcursor/cursor#1648]
OS: Windows 11, also WSL Ubuntu

We are currently evaluating Cursor as a replacement for VS Code / Co-Pilot, and noticed this problem, which is now blocking us: The Azure extensions do not function, with a "timed out waiting for authentication provider to register" message. 
<img width="361" alt="image" src="https://github.com/user-attachments/assets/9a5d293a-b369-4669-a9ce-20febb3ab9a1">

You can try and do the Azure login commands but it does not seem to do anything inside of Cursor

This issue related to remote tunnels mentioned this problem, but I think this is a separate issue: https://github.com/getcursor/cursor/issues/1191

Also see https://github.com/microsoft/vscode-azure-account/issues/897, though it does seem like it's a Cursor issue.

**Comment by pmatheusvinhas** [comment]
Writing to endorse the issue. I'm having the same problem here.

**Comment by Apologin** [comment]
Same issue here. No solution yet.

**Comment by icazemier** [comment]
Got a similar error with the Microsoft Entra External ID (Preview) extension in VSCode...
Just installed, and trying an existing subscription.
No success.

![image](https://github.com/user-attachments/assets/00de8775-6435-4188-856c-12c7d0d152fc)

**Comment by MrErikCodes** [comment]
Yep, same issue. On latest
![bilde](https://github.com/user-attachments/assets/e93d3381-e871-4131-a8f2-41cbfcea46b9)

**Comment by jonasherfort** [comment]
Same issue here, also a problem with the databricks extension. Only a problem with WSL though.

**Comment by vladsterian-diconium** [comment]
Same problem here

**Comment by vladsterian-diconium** [comment]
Seems like this issue is related to the fact that Azure authentication is relying now on this Microsoft Authentication extension, which is build-in VSCode lately. This extension is missing on cursor. So, if anyone knows how to pack that buildin extension into a .vsix file probably it will solve this problem.

https://github.com/microsoft/vscode-azureresourcegroups?tab=readme-ov-file#move-to-built-in-vs-code-authentication

**Comment by connorblack** [comment]
This has been going on for MONTHS. Is the cursor team ever going to do something about it?

**Comment by connorblack** [comment]
I looked heavily into this a while ago but had to switch back to vscode for the project I needed Azure integrations with. I even tried switching some of the auth settings:

````
    "azure-dev.auth.useIntegratedAuth": true,
```
and 
```
    "azure.authenticationLibrary": "MSAL", // MSAL: Microsoft Authentication Library (Preview) vs ADAL: Azure Active Directory Authentication Library (default)
```

But not luck.

Some more details:

Azure Resource Groups
```
2024-10-03 15:46:58.346 [info] Error: command 'workbench.action.openWalkthrough' not found
2024-10-03 16:18:35.116 [info] Error: Timed out waiting for authentication provider to register
```

Window
```
2024-10-03 16:12:10.844 [error] [unimplemented] HTTP 404: ConnectError: [unimplemented] HTTP 404
    at Object.U [as unary] (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3555:11882)
    at async Object.repositoryStatus (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:266:139584)
    at async B._getUpdatedRepoStatus (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2359:8458)
    at async B.getUpdatedRepoStatus (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2359:8360)
    at async B.setRepositoryInfo (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2355:8595)
    at async B.setRepoInfo (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2355:7023)
2024-10-03 16:19:39.085 [error] [Extension Host] Error: ENOENT: no such file or directory, stat 'ms-azuretools.vscode-azureresourcegroups.Azure Resource Groups'
    at Object.stat (node:internal/fs/sync:58:25)
    at statSync (node:fs:1669:17)
    at t.statSync (node:electron/js2c/node_init:2:5052)
    at Object.n.statSync (/Users/connorblack/.cursor/extensions/esbenp.prettier-vscode-11.0.0/dist/extension.js:1:3435)
    at Tn (/Users/connorblack/.cursor/extensions/tim-koehler.helm-intellisense-0.14.3/out/extension.js:51:400)
    at mi (/Users/connorblack/.cursor/extensions/tim-koehler.helm-intellisense-0.14.3/out/extension.js:51:10165)
    at /Users/connorblack/.cursor/extensions/tim-koehler.helm-intellisense-0.14.3/out/extension.js:53:3883
    at v.h (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:207453)
    at v.g (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:206445)
    at v.executeCommand (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:206352)
    at Object.executeCommand (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:26491)
    at /Users/connorblack/.cursor/extensions/tim-koehler.helm-intellisense-0.14.3/out/extension.js:53:4117
    at l.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:21158)
    at r.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:84:739)
    at r.C (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:84:809)
    at r.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:84:1025)
    at S.$acceptModelSaved (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:82004)
    at L.S (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:5996)
    at L.Q (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:5762)
    at L.M (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:4782)
    at L (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:3606)
    at l.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:2298)
    at r.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:84:739)
    at r.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:84:956)
    at w.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:14563)
    at l.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:186:8653)
    at r.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:84:739)
    at r.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:84:956)
    at w.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:14563)
    at MessagePortMain.<anonymous> (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:186:6779)
    at MessagePortMain.emit (node:events:514:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
2024-10-03 16:21:19.913 [error] command 'workbench.action.openWalkthrough' not found: Error: command 'workbench.action.openWalkthrough' not found
    at b.n (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2192:32605)
    at b.executeCommand (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2192:32534)
2024-10-03 16:21:44.883 [error] There are no commenting ranges at the current position (with range).: Error: There are no commenting ranges at the current position (with range).
    at U.addCommentAtLine (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2784:2646)
    at U.addOrToggleCommentAtLine (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2784:2176)
    at U.cb (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2784:1881)
    at $.value (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2783:21637)
    at te.B (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:430:732)
    at te.C (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:430:802)
    at te.fire (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:430:1018)
    at te.fire (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1296:22638)
    at pe.onMouseUp (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1296:20448)
    at v.emitMouseUp (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:451:6580)
    at y.emitMouseUp (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1202:47014)
    at i.F (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1248:15422)
    at vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1248:12979
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1243:32922)

```

Extensions host
```
2024-10-03 16:16:11.612 [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-azureresourcegroups, startup: false, activationEvent: 'onView:azureResourceGroups'
2024-10-03 16:16:11.670 [info] ExtensionService#_doActivateExtension ms-azuretools.azure-dev, startup: false, activationEvent: 'api', root cause: ms-azuretools.vscode-azureresourcegroups
2024-10-03 16:16:14.061 [error] Error: Client not initialized
    at e.FileSyncClient.fsConfig (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:680908)
    at e.FileSyncClient.fsConfigUpdate (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:681353)
    at e.FileSyncer.handleFileSyncEnabledChange (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:689027)
```

**Comment by atans2468** [comment]
Still having this issue as well

**Comment by TomMoeras** [comment]
This seems to be the solution: https://github.com/microsoft/vscode-azure-account/issues/897#issuecomment-2424082420

> Found the fix elsewhere. https://forum.cursor.com/t/azure-extension-doesent-work/3949/15
> 
> **Fix Azure extensions on Cursor** Cursor does not come with Microsoft authentication, a builtin extension for vscode
> 
> To get this extension, grab it from VSCode `\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\microsoft-authentication` Copy to `\AppData\Local\Programs\cursor\resources\app\extensions`
> 
> For MacOS
> 
> `/Applications/Visual Studio Code. app/Contents/Resources/app/extensions/microsoft-authentication` and `/Applications/Cursor.app/Contents/Resources/app/extensions`
> 
> Reload Cursor windows after.
> 
> See additional steps at the link to connect to servers.

**Comment by vladsterian-diconium** [comment]
I confirm that the solution works, however only using MSAL
