### ISSUE TITLE
[Version 0.40.1] Failed to download VS Code Server: 404 Not Found

### ISSUE THREAD

**Issue by GabrielDrapor** [getcursor/cursor#1714]
Cannot open in devcontainer

1) If you can, please include a screenshot of your problem
<img width="1577" alt="image" src="https://github.com/user-attachments/assets/63b0db61-743b-4686-84f7-18df93f15388">

```
Support for ARM64 is in preview.

[654 ms] Start: Run in container: test -d '/home/vscode/.cursor-server/bin/58b91712431381a1b75817cd3437cee35dddcb30'
[654 ms] 
[654 ms] 
[654 ms] Exit code 1
[654 ms] Start: Run in container: test -d '/vscode/cursor-server/bin/linux-arm64/58b91712431381a1b75817cd3437cee35dddcb30'
[656 ms] 
[656 ms] 
[656 ms] Exit code 1
[656 ms] Installing VS Code Server for commit 58b91712431381a1b75817cd3437cee35dddcb30
[656 ms] Start: Run in container: /bin/sh
[657 ms] Start: Downloading VS Code Server
[657 ms] 58b91712431381a1b75817cd3437cee35dddcb30 linux-arm64 stable
[1225 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:58b91712431381a1b75817cd3437cee35dddcb30/server-linux-arm64/stable): HTTP 404 - Not Found
[1225 ms] Retrying to download VS Code Server.
[1727 ms] Error: Server returned 404
    at l (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1179:48659)
    at v.download (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1180:1878)
```

2) Please include the name of your operating system

```
Version: 0.40.1
VSCode Version: 1.91.1
Commit: 58b91712431381a1b75817cd3437cee35dddcb30
Date: 2024-08-24T02:52:24.035Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.3.0
```

3) If you can, steps to reproduce are super helpful

rebuild & reopen in devcontainer or attach to the running container

**Comment by hktxt** [comment]
+1, same issue.

**Comment by GabrielDrapor** [comment]
Solved by downgrade devcontainer extension to v0.327.0

**Comment by christine-sb** [comment]
> Solved by downgrade devcontainer extension to v0.327.0

When I try to do this in cursor then I get an error claiming "This extension has no other versions." On vscode then I have the option to use any previous version that I want, but does anyone else have this issue on cursor?
<img width="723" alt="Screenshot 2024-08-31 at 4 30 23 PM" src="https://github.com/user-attachments/assets/7d84bfa2-d038-4098-b33f-1dedd4fe0489">

**Comment by sdepablos** [comment]
Thanks @GabrielDrapor, it worked for me too.

@christine-sb you need to download it manually:

1. Uninstall the current version of dev containers
2. Download it manually from https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-containers/0.327.0/vspackage (I just copied a URL from version history in the official extension page https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers and change the version number
3. Open VS Code.
4. Go to the Extensions view (Ctrl+Shift+X).
5. Click on the three-dot menu (•••) in the upper right corner of the Extensions view.
6. Select Install from VSIX.... and install it

**Comment by GabrielDrapor** [comment]
@christine-sb Thanks for the additional information!

you can also: remove it in Cursor -> back to **VS Code**, right click the dev containers extension and select 'install another version' to downgrade -> import again in Cursor Settings

**Comment by nigiwen** [comment]
Some containers can and some containers cannot, I don't know the difference between them
```bash
[1453 ms] WARNING: Ignoring https://mirrors.ustc.edu.cn/alpine/v3.16/main: No such file or directory
WARNING: Ignoring https://mirrors.ustc.edu.cn/alpine/v3.16/community: No such file or directory
[2596 ms] Failed to download VS Code Server (https://cursor.blob.core.windows.net/remote-releases/5af2d34c39df93a39bd54c9b9103cab514b380f0/vscode-reh-linux-alpine.tar.gz): HTTP 404 - The specified blob does not exist.
[2596 ms] Retrying to download VS Code Server.
[3676 ms] Error: Server returned 404
    at BI (vscode-file://vscode-app/c:/Users/BSI/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:667:62034)
    at _Wt.download (vscode-file://vscode-app/c:/Users/BSI/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:2925:30901)
```

**Comment by leerob** [comment]
Thanks for opening this issue! We've moved our community support to the [Cursor Forum](https://forum.cursor.com) where you can get help from both the team and other users.

If this is a specific bug that you can still reproduce, please open a new issue with clear reproduction steps on the forum.

Thanks you!
