### ISSUE TITLE
Attach to docker not working

### ISSUE THREAD

**Issue by Boffice** [getcursor/cursor#1748]
1) If you can, please include a screenshot of your problem
![image](https://github.com/user-attachments/assets/e382696c-2e97-4ff3-a2cd-6cd27495035d)

2) Please include the name of your operating system
Fedora
3) If you can, steps to reproduce are super helpful
Attach to running container

**Comment by Boffice** [comment]
tried it on windows different error.
![image](https://github.com/user-attachments/assets/003deec0-2ca8-4d0b-80d5-f7f2a0c35f68)

**Comment by Boffice** [comment]
Url seems to be cahnging 
![image](https://github.com/user-attachments/assets/8e8079f9-ba01-47ac-8f05-832cae97d205)

**Comment by MiguelZamoraM** [comment]
I have the same problem on Ubuntu 22.04 using `cursor-0.40.4x86_64.AppImage`.

**Comment by yumeminami** [comment]
+1

**Comment by yumeminami** [comment]
> I have the same problem on Ubuntu 22.04 using `cursor-0.40.4x86_64.AppImage`.

```shell
[2117 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/server-linux-x64/stable): HTTP 404 - Not Found
[2118 ms] Retrying to download VS Code Server.
[2284 ms] Error: Server returned 404
    at l (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1197:48671)
    at y.download (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1198:1878)
```

**Comment by lnexenl** [comment]
![image](https://github.com/user-attachments/assets/787f5cbf-9ab5-4ff9-baab-96b04bc4c4df)
On Win 11
