### ISSUE TITLE
Indexing Fails - Handshake failed.

### ISSUE THREAD

**Issue by strueman** [getcursor/cursor#1806]
indexing fails with handshake failed message,
Delete index, restart Cursor and it completes fine, with no errors, until it doesn't and rinse and repeat.

Possible Solution:
I am thinking a workaround may be to automate a delete index and clear any cache / temp data the indexing system uses, restart the indexing system and trigger a rebuild on repeated handshake error? Not the ideal solution but I can see this has been an ongoing niggling problem throughout many versions in the old issues and forum posts.

mac os ver 14.5 (23F79)
cursor info:
Version: 0.40.3
VSCode Version: 1.91.1
Commit: 2804893a83ef162ae6c48e8254717e25c7c7c510
Date: 2024-08-29T17:42:50.254Z (4 days ago)
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

Cursor Indexing and Retrieval output 

2024-09-03 12:43:38.707 [info] Creating merkle client.
2024-09-03 12:43:38.707 [info] Done creating merkle client.
2024-09-03 12:43:38.707 [info] Doing a startup handshake.
2024-09-03 12:43:38.712 [info] Finished initializing merkle tree in 4.370000123977661 ms.
2024-09-03 12:43:38.712 [info] Doing the initial handshake with hash: 9a60c9b9735c0f1ce36dcbbb65f3104bcbe7641f57624eb0da4320bc00c3e69e
2024-09-03 12:43:38.713 [info] Handshake start
2024-09-03 12:43:42.725 [info] Handshake start
2024-09-03 12:43:50.730 [info] Handshake start
2024-09-03 12:44:06.735 [info] Handshake start
2024-09-03 12:44:38.739 [info] Handshake start
2024-09-03 12:45:42.747 [info] Handshake start
2024-09-03 12:46:09.391 [info] Search by message took 21.677958011627197ms for query ""
2024-09-03 12:46:09.391 [info] Search by message took 27.364166021347046ms for query ""
2024-09-03 12:46:09.391 [info] Search by sha took 21.419875144958496ms for query ""
2024-09-03 12:46:09.391 [info] Search by sha took 25.430042028427124ms for query ""
2024-09-03 12:47:50.752 [error] Handshake failed:
2024-09-03 12:47:50.753 [error] Error: timeout in handshake with retry
	at t.RepoClientMultiplexer.handshakeWithRetry (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:817710)
	at async w.getServerStatus (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:832927)
	at async w.startIndexingRepository (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:835227)
2024-09-03 12:47:50.753 [error] Handshake failed.
2024-09-03 12:47:50.753 [info] Indexing job successfully done or aborted.

**Comment by AtlasPilotPuppy** [comment]
I am running into the same issue

**Comment by nrw303** [comment]
I also have this issue:

Version: 0.41.3
VSCode Version: 1.91.1
Commit: 51c8aff7cb5a89f4a0e462fbacab938bdbfaf140
Date: 2024-09-25T17:13:50.377Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 24.0.0

**Comment by danperks** [comment]
Anyone with this issue, please comment in #2035 with your OS and Cursor info, thanks!
