### ISSUE TITLE
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed

### ISSUE THREAD

**Issue by bay0max** [getcursor/cursor#185]
I run AppImage file and got this error

`
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_CursorDY1dVU/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_CursorDY1dVU/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_CursorDY1dVU/resources/app.asar/.webpack/main/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109416)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_CursorDY1dVU/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_CursorDY1dVU/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_CursorDY1dVU/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_CursorDY1dVU/resources/app.asar/.webpack/main/index.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_CursorDY1dVU/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_CursorDY1dVU/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed

`

**Comment by truell20** [comment]
Is this still happening in the newest version?

**Comment by danperks** [comment]
Will close to keep the Issues clear, but feel free to comment and we can reopen this for you!
