### ISSUE TITLE
Doesn't work with copilot

### ISSUE THREAD

**Issue by feyroozecode** [getcursor/cursor#1856]
Macbook air 2024 SANOMA
Open Cursor and start writing we dont get copilot suggest

**Comment by mashirozx** [comment]
me too

```
2024-09-12 09:35:46.926 [info] [certificates] Removed 22 expired certificates
2024-09-12 09:36:02.503 [error] [default] Error sending telemetry FetchError: Client network socket disconnected before secure TLS connection was established
    at fetch (/Users/mashiro/.cursor/extensions/github.copilot-1.229.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/Users/mashiro/.cursor/extensions/github.copilot-1.229.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at bae.fetch (/Users/mashiro/.cursor/extensions/github.copilot-1.229.0/lib/src/network/helix.ts:93:22) {
  type: 'system',
  _name: 'FetchError',
  code: 'ECONNRESET',
  errno: undefined,
  erroredSysCall: undefined
}
2024-09-12 09:36:09.859 [error] [auth] Canceled
2024-09-12 09:36:14.141 [info] [certificates] Removed 22 expired certificates
2024-09-12 09:36:31.725 [error] [default] Error sending telemetry FetchError: Client network socket disconnected before secure TLS connection was established
    at fetch (/Users/mashiro/.cursor/extensions/github.copilot-1.229.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/Users/mashiro/.cursor/extensions/github.copilot-1.229.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at bae.fetch (/Users/mashiro/.cursor/extensions/github.copilot-1.229.0/lib/src/network/helix.ts:93:22) {
  type: 'system',
  _name: 'FetchError',
  code: 'ECONNRESET',
  errno: undefined,
  erroredSysCall: undefined
}
2024-09-12 09:39:23.105 [error] [auth] Canceled
2024-09-12 09:39:25.462 [info] [certificates] Removed 22 expired certificates
2024-09-12 09:39:41.640 [error] [default] Error sending telemetry FetchError: Client network socket disconnected before secure TLS connection was established
    at fetch (/Users/mashiro/.cursor/extensions/github.copilot-1.229.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/Users/mashiro/.cursor/extensions/github.copilot-1.229.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at bae.fetch (/Users/mashiro/.cursor/extensions/github.copilot-1.229.0/lib/src/network/helix.ts:93:22) {
  type: 'system',
  _name: 'FetchError',
  code: 'ECONNRESET',
  errno: undefined,
  erroredSysCall: undefined
}
```

Version: 0.40.4
VSCode Version: 1.91.1
Commit: 63dae81aea2c3fc079420fe72578a8eef26ba870
Date: 2024-09-05T02:52:05.660Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.6.0

**Comment by mashirozx** [comment]
@feyroozecode Got the solution, try login first:

<img width="701" alt="image" src="https://github.com/user-attachments/assets/86ab8d5c-0040-484a-8a84-8fdb015fff68">

**Comment by feyroozecode** [comment]
Ok thank you in gonna to try it

**Comment by danperks** [comment]
Hey, did this fix your issue?
