### ISSUE TITLE
Failed to download VS Code Server

### ISSUE THREAD

**Issue by Dexoon** [getcursor/cursor#1882]
![изображение](https://github.com/user-attachments/assets/949de00c-826a-4bb9-badb-4c2acc82ed81)

While building devcontainer on fresh installed cursor on ubuntu 22.04, I get this error
Failed to download VS Code Server (https://update.code.visualstudio.com/commit:63dae81aea2c3fc079420fe72578a8eef26ba870/server-linux-x64/stable): HTTP 404 - Not Found
Retrying to download VS Code Server.
Error: Server returned 404
    at c (vscode-file://vscode-app/tmp/.mount_cursoreQNcj4/resources/app/out/vs/workbench/workbench.desktop.main.js:1179:48659)
    at v.download (vscode-file://vscode-app/tmp/.mount_cursoreQNcj4/resources/app/out/vs/workbench/workbench.desktop.main.js:1180:1878)

**Comment by wendlerc** [comment]
Same here.

**Comment by danperks** [comment]
Will close as a duplicate of #1191
