### ISSUE TITLE
Open Folder doesn't work in fresh setup (main branch)

### ISSUE THREAD

**Issue by shoaibmohommed** [getcursor/cursor#195]
Hey,

So I have cloned the repo and currently in `main` branch, i am using `Windows OS` BTW, 

Already installed `node_modules`
run the app using `npm start` --> app opens normally 

When i click on the `Open Folder` button it gives error in `main` process

i checked the code i can see there are 2 handlers for "open_folder"  
![image](https://user-images.githubusercontent.com/6280803/227374766-c384c446-e258-452d-82ef-fc099000eb85.png)

is it correct can we have multiple handlers for same event

BTW here is the error i got on main process
```
03:27:03.476 > uncaughtException Error: Attempted to register a second handler for 'open_folder'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:2:97331)
    at App.createWindow (C:\Users\shoai\OneDrive\Documents\WORK\cursor\.webpack\main\index.js:86847:51)
    at App.emit (node:events:525:35)
[BABEL] Note: The code generator has deoptimised the styling of C:\Users\shoai\OneDrive\Documents\WORK\cursor\node_modules\react-dom\cjs\react-dom.development.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of C:\Users\shoai\OneDrive\Documents\WORK\cursor\node_modules\lodash\lodash.js as it exceeds the max of 500KB.
03:27:34.223 > Error occurred in handler for 'get_folder': TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (true)
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at Object.basename (node:path:752:5)
    at C:\Users\shoai\OneDrive\Documents\WORK\cursor\.webpack\main\index.js:86460:66
    at Generator.next (<anonymous>)
    at C:\Users\shoai\OneDrive\Documents\WORK\cursor\.webpack\main\index.js:86159:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\shoai\OneDrive\Documents\WORK\cursor\.webpack\main\index.js:86155:12)
    at addToFilesFolders (C:\Users\shoai\OneDrive\Documents\WORK\cursor\.webpack\main\index.js:86459:24)
    at C:\Users\shoai\OneDrive\Documents\WORK\cursor\.webpack\main\index.js:86505:19
03:27:34.240 > Error occurred in handler for 'getStore': No handler registered for 'getStore'
03:27:36.138 > Error occurred in handler for 'get_folder': TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (true)
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at Object.basename (node:path:752:5)
    at C:\Users\shoai\OneDrive\Documents\WORK\cursor\.webpack\main\index.js:86460:66
    at Generator.next (<anonymous>)
    at C:\Users\shoai\OneDrive\Documents\WORK\cursor\.webpack\main\index.js:86159:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\shoai\OneDrive\Documents\WORK\cursor\.webpack\main\index.js:86155:12)
    at addToFilesFolders (C:\Users\shoai\OneDrive\Documents\WORK\cursor\.webpack\main\index.js:86459:24)
    at C:\Users\shoai\OneDrive\Documents\WORK\cursor\.webpack\main\index.js:86505:19
[39152:0324/032903.482:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is 
```

**Comment by truell20** [comment]
thanks for reporting, fixed
