### ISSUE TITLE
Git-related symbols not accessible through Chat

### ISSUE THREAD

**Issue by snickerdudle** [getcursor/cursor#1989]
1) If you can, please include a screenshot of your problem

![Screenshot 2024-09-24 at 2 02 07 PM](https://github.com/user-attachments/assets/a75104f1-b5ef-413e-8b26-97c472d2e6e1)
![Screenshot 2024-09-24 at 2 02 15 PM](https://github.com/user-attachments/assets/a5627d77-105e-4ff0-941f-a97c21b24505)

2) Please include the name of your operating system

MacOS Sonoma - M1

3) If you can, steps to reproduce are super helpful

When opening Chat and putting in the @ symbol to tag a file, the file "pill" shows up at the top and the preview of the supplied content is shown right below - all as expected.

However, when using @PR or @Commit , nothing is displayed, and when the chat is started the model says that no context was supplied.

System info:

```
Version: 0.41.2
VSCode Version: 1.91.1
Commit: 297991d169fa3a11975c5aa95adc69be73250c70
Date: 2024-09-21T04:18:39.370Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by snickerdudle** [comment]
I will note that this was working fine before updating to latest version

**Comment by danperks** [comment]
If you go to the Output tab, and choose "Cursor Indexing & Retrieval", do you see any errors or output? This is where you would see them if there are some git errors when getting your PRs or Commits.

**Comment by snickerdudle** [comment]
I see LOTs of the following messages (alternating for each file I open):

```
2024-09-24 19:46:55.335 [error] Failed to get cached related files... falling back to uncached No indexer found for file. Maybe not inside a git repo? <<file pwd here>>
2024-09-24 19:46:55.335 [error] Failed to get related files No indexer found for file. Maybe not inside a git repo? <<file pwd here>>
```

**Comment by snickerdudle** [comment]
Also, I'm occasionally seeing this message: 
```
2024-09-24 19:51:05.736 [info] Git graph is disabled. shouldIndex: true isEnabled: false
```

**Comment by ilmarioranen** [comment]
I'm seeing this same issue in the latest cursor version!
I'm also on: MacOS Sonoma - M1

I am also seeign similar huge error spam in Output -> "Cursor Git Graph":
> 2024-09-26 14:03:24.515 [error] Failed to get related files No indexer found for file. Maybe not inside a git repo? /Users/[redacted]"

Additionally I'm seeing some other worrying errors (which might be new or not, havent checked these recently):

* In Output -> "Window":

> 2024-09-26 14:03:41.115 [error] ((e.request && e.request.fetch) || globalThis.fetch || fe) is not a function: TypeError: ((e.request && e.request.fetch) || globalThis.fetch || fe) is not a function
> 	at Se (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:24945)
> 	at o (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:26460)
> 	at Pe (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:28438)
> 	at /Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:30317
> 	at /Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:288910
> 	at async t.GitProvider.searchPullRequests (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:745237)
> 	at async q.$searchPRs (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:193985)

* And this in "Output" -> "Extension Host"
> 2024-09-26 14:10:42.723 [error] Error: Client not initialized
> 	at e.FileSyncClient.fsConfig (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:680908)
> 	at e.FileSyncClient.fsConfigUpdate (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:681353)
> 	at async e.FileSyncer.handleFileSyncEnabledChange (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:689027)
> 

* In "Output" -> "GitLens (Git)":

> 2024-09-26 14:10:42.723 [error] Error: Client not initialized
> 	at e.FileSyncClient.fsConfig (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:680908)
> 	at e.FileSyncClient.fsConfigUpdate (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:681353)
> 	at async e.FileSyncer.handleFileSyncEnabledChange (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-always-local/dist/main.js:2:689027)
>
