### ISSUE TITLE
Error Indexing codebase 

### ISSUE THREAD

**Issue by soumen02** [getcursor/cursor#2035]
1) If you can, please include a screenshot of your problem
Initial error on chat
![image](https://github.com/user-attachments/assets/d83ffd48-1e2f-48cc-8b2b-2ec9b1faa46d)
When I click _Open Settings_ and index, it got stuck on this for around 5-8 minutes 
![image](https://github.com/user-attachments/assets/11df21f8-53e2-4196-9459-13ba2abb3a0e)
After sometime I see the following, 
![image](https://github.com/user-attachments/assets/cd8c26be-dbd9-488f-a328-8dbc6e9c04a7)
I continue asking it questions in chat, and when it gives me hallucinated output I go back to the settings page I see the following.
![image](https://github.com/user-attachments/assets/689b33bd-dcc2-424e-8689-d761510e40a2)
2) Please include the name of your operating system
MacOS Sonoma 14.6.1 (23G93)
3) If you can, steps to reproduce are super helpful

**Comment by ascanio** [comment]
Same Issue here
<img width="535" alt="image" src="https://github.com/user-attachments/assets/5d0d7890-4c9a-4754-b42c-2a837774e124">
<img width="505" alt="image" src="https://github.com/user-attachments/assets/0dd221df-e26f-403b-8dd7-43ab8ff3b656">

**Comment by brahyam** [comment]
Same issue today on similar platform. could this be due to an outage?

**Comment by danperks** [comment]
Hi, is this issue still occurring? Seems likely that an outage or temporary bug.

**Comment by SeekBytes-AI** [comment]
I am having the same issue. 
I have reinstalled the cursor after cleanup but did not help.

**Comment by daniel-wachira** [comment]
I'm also experiencing this problem. Has anyone managed to find a workaround?

**Comment by KekmaTime** [comment]
dude im tired of it happening i tried reinstalling the whole thing but it still persists

**Comment by chriswep** [comment]
same, seems to be an issue at their end? https://www.reddit.com/r/cursor/comments/1fytjlg/curosr_forum_multiple_users_started_to_have/

**Comment by danperks** [comment]
Hey all, devs have been notified and are looking into it - sorry for anyone having issues!

**Comment by athmanar** [comment]
issue persists:
2024-10-02 10:06:07.652 [info] Setting indexing intent to should-index
2024-10-02 10:06:07.655 [info] Creating merkle client.
2024-10-02 10:06:07.655 [info] Done creating merkle client.
2024-10-02 10:06:07.656 [info] Doing a startup handshake.
2024-10-02 10:06:08.528 [info] Finished initializing merkle tree in 873.6273000240326 ms.
2024-10-02 10:06:08.530 [info] Doing the initial handshake with hash: ba088e651205d23a2561a2a127ba47f54bd00ba8382e36a8877b1168027f860d
2024-10-02 10:06:08.533 [info] Handshake start
2024-10-02 10:06:11.588 [info] Handshake start
2024-10-02 10:06:19.607 [info] Handshake start
2024-10-02 10:06:35.630 [info] Handshake start
2024-10-02 10:07:07.639 [info] Handshake start
2024-10-02 10:08:01.208 [info] Handshake start
2024-10-02 10:09:26.825 [error] Handshake failed:
2024-10-02 10:09:26.827 [error] Error: timeout in handshake with retry
at t.RepoClientMultiplexer.handshakeWithRetry (c:\Users\USER\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:826553)
at async w.getServerStatus (c:\Users\USER\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:841881)
at async w.startIndexingRepository (c:\Users\USER\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:844181)
2024-10-02 10:09:26.829 [error] Handshake failed.
2024-10-02 10:09:26.829 [info] Indexing job successfully done or aborted.

**Comment by samgabrail** [comment]
yes same issue here running on windows 11 within WSL2

**Comment by henriquebs12** [comment]
Same issue here, it's a pity to see you can't rely on their services. Their reputation just goes down a bit every time theses outages occurs.

**Comment by pinion** [comment]
same. mac os x 14.7

curl https://repo42.cursor.sh
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>

**Comment by georgeliu1998** [comment]
Logging out and back in doesn't solve the issue anymore. Here's my system info:

**OS**
macOS Sequoia Version 15.0.1 (24A348)

**Cursor**
Version: 0.41.3
VSCode Version: 1.91.1
Commit: 51c8aff7cb5a89f4a0e462fbacab938bdbfaf140
Date: 2024-09-25T17:13:50.377Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 24.0.0

**Comment by AtlasPilotPuppy** [comment]
as a developer willing to help fix how can i help / contribute? @danperks

**Comment by danperks** [comment]
> as a developer willing to help fix how can i help / contribute? @danperks 
> 
> 

Hey @AtlasPilotPuppy, thanks for offering to help! Cursor is closed source right now and the dev team are aware of this issue, so for now there's not much that can be done, although I appreciate the offer!

If needed, a dev may ask for more info if they're struggling to reproduce an issue, so keep an eye on this issue and we'll see what happens :)

**Comment by cchevall** [comment]
I just logged out from my cursor account and logged in with a new account. Right after, this issue showed up on all my repositories. Could it be linked?

**Comment by afastlearner** [comment]
> Same Issue here <img alt="image" width="535" src="https://private-user-images.githubusercontent.com/279210/372070934-5d0d7890-4c9a-4754-b42c-2a837774e124.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MjAxNDUsIm5iZiI6MTcyODQxOTg0NSwicGF0aCI6Ii8yNzkyMTAvMzcyMDcwOTM0LTVkMGQ3ODkwLTRjOWEtNDc1NC1iNDJjLTJhODM3Nzc0ZTEyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQyMDM3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODMwN2NlOWM1NWJiMzMzOWNiOTkwZTA0MTNmYzdkZjcxOGJiNzEzMTViODIxNzYyMDA4MTQ2OTg5OWJmZDExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KIWLAukdhcCIACnCJWD_Qet6WKOKLxdsFLLzBABQikI"> <img alt="image" width="505" src="https://private-user-images.githubusercontent.com/279210/372071263-0dd221df-e26f-403b-8dd7-43ab8ff3b656.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MjAxNDUsIm5iZiI6MTcyODQxOTg0NSwicGF0aCI6Ii8yNzkyMTAvMzcyMDcxMjYzLTBkZDIyMWRmLWUyNmYtNDAzYi04ZGQ3LTQzYWI4ZmYzYjY1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQyMDM3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2I2MzgwYjA0OGY4ZDc2NGVmNjYwMjJjM2NjOWY2NmYxMzgzZGYxOTk0YTJkYTVhNzc4YjJkMmRkMTg1Y2MzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-3Nq6fNSW76e2M54Q8XetLpgGf4TYSlBsWsKbLXltGo">

same on windows 11

**Comment by afastlearner** [comment]
> I just logged out from my cursor account and logged in with a new account. Right after, this issue showed up on all my repositories. Could it be linked?

I even closed the cursor windows for that repo and opened it again and it was already failed, without loging out.

**Comment by Raleose** [comment]
There is a strange requests under the hood.

The first one is `POST https://repo42.cursor.sh/aiserver.v1.RepositoryService/RepositoryStatus HTTP/1.1`.
It always completes by status 404 and body:
`{"message":"Route POST:/aiserver.v1.RepositoryService/RepositoryStatus not found","error":"Not Found","statusCode":404}`
I tried to modify request host to `api2.cursor.sh` instead of `repo42.cursor.sh`, but nothing has changed.

The second one is `POST https://api2.cursor.sh/aiserver.v1.RepositoryService/FastRepoInitHandshake HTTP/1.1`.
It sometimes completes by status 500, but it's very rare case.
In most cases it completes by 200, but if we look inside the proto body we will find that message contains something like that:
`{"status":"STATUS_FAILURE","repoName":"some guid here"}`
`repoName` isn't interesting for us, but `STATUS_FAILURE` - it is number 3 inside of proto serialized body.

@danperks it may be helpful for devs, i think.

**Comment by seqis** [comment]
Getting the same error: Running Linux Mint 20.3, MATE Edition.

![image](https://github.com/user-attachments/assets/72db9ad5-49c3-4b24-9842-d510f3bd925f)

~~~~markdown
cat ./remoteTunnelService.log 
2024-10-06 20:49:17.539 [error] Missing 'tunnelApplicationConfig' or 'tunnelApplicationName' in product.json. Remote tunneling is not available.
2024-10-07 08:28:35.825 [error] Missing 'tunnelApplicationConfig' or 'tunnelApplicationName' in product.json. Remote tunneling is not available.
2024-10-07 08:47:37.062 [error] Missing 'tunnelApplicationConfig' or 'tunnelApplicationName' in product.json. Remote tunneling is not available.
2024-10-07 09:02:45.765 [error] Missing 'tunnelApplicationConfig' or 'tunnelApplicationName' in product.json. Remote tunneling is not available.
2024-10-08 18:23:33.506 [error] Missing 'tunnelApplicationConfig' or 'tunnelApplicationName' in product.json. Remote tunneling is not available.
~~~~

**Comment by RyanAD** [comment]
I have this issue as well. I used Google Login to create my account if that helps narrow it down.

**Comment by ubergeekseven** [comment]
same issue. I have tried indexing several times with the handshake failed ultimately occurring. I went through my codebase and added as many of the extraneous portions of my libraries dependency folders to the cursor ignore file. That did not help. I thought it would until searching led me here.

**Comment by ozansozuozgit** [comment]
Same issue here, just bought pro 2 days ago smh

**Comment by Raleose** [comment]
> There is a strange requests under the hood.
> 
> The first one is `POST https://repo42.cursor.sh/aiserver.v1.RepositoryService/RepositoryStatus HTTP/1.1`. It always completes by status 404 and body: `{"message":"Route POST:/aiserver.v1.RepositoryService/RepositoryStatus not found","error":"Not Found","statusCode":404}` I tried to modify request host to `api2.cursor.sh` instead of `repo42.cursor.sh`, but nothing has changed.
> 
> The second one is `POST https://api2.cursor.sh/aiserver.v1.RepositoryService/FastRepoInitHandshake HTTP/1.1`. It sometimes completes by status 500, but it's very rare case. In most cases it completes by 200, but if we look inside the proto body we will find that message contains something like that: `{"status":"STATUS_FAILURE","repoName":"some guid here"}` `repoName` isn't interesting for us, but `STATUS_FAILURE` - it is number 3 inside of proto serialized body.
> 
> @danperks it may be helpful for devs, i think.

Now indexing works for me. I looked at the response body of FastRepoInitHandshake and it's status has 2 as value. Great job, thank you

**Comment by JoanEsquivel** [comment]
I do have the same issue.

**Comment by danielkubat** [comment]
Ubuntu 20.04, Cursor 0.42.5

![image](https://github.com/user-attachments/assets/97cab5bd-eb8e-4d7a-b484-5411f3efe841)
:tada: :tada:

I'm now finally able to execute and finish indexing  - trick was to disconnect from corporate proxy...

**Comment by anshamray** [comment]
Have the same issue on my M2 Mac with macOS 15.1. I tried everything this week, but couldn't find the solution.

**Comment by iamsaurabhc** [comment]
Guys - this issue persists with inconsistent internet / network. I changed mine to a faster WiFi, and the issue got resolved. Recheck your connection.

**Comment by c00134744** [comment]
I'm also experiencing this issue. I'm using a company proxy, and disabling HTTP/2 didn't resolve it.  Here's the error log:

2024-11-30 16:32:14.051 [info] Creating merkle client.
2024-11-30 16:32:14.051 [info] Done creating merkle client.
2024-11-30 16:32:14.051 [info] Doing a startup handshake.
2024-11-30 16:32:14.070 [info] Finished initializing merkle tree in 15.57260000007227 ms.
2024-11-30 16:32:14.070 [info] Doing the initial handshake with hash: 03989adfc16dcac751f...
2024-11-30 16:32:14.072 [info] Handshake start
2024-11-30 16:32:17.412 [info] Search by sha took 17.391200000070967ms for query ""
2024-11-30 16:32:17.438 [info] Search by message took 46.25659999996424ms for query ""
2024-11-30 16:32:18.094 [warning] Retrying handshake with timeout 4000. Error:  [deadline_exceeded] the operation timed out
2024-11-30 16:32:18.094 [info] Handshake start
2024-11-30 16:32:18.970 [info] Search by sha took 26.7461000001058ms for query ""
2024-11-30 16:32:18.978 [info] Search by sha took 29.483299999963492ms for query ""
2024-11-30 16:32:18.982 [info] Search by sha took 26.711200000019744ms for query ""
2024-11-30 16:32:18.991 [info] Search by sha took 25.97720000008121ms for query ""
2024-11-30 16:32:18.998 [info] Search by sha took 25.34299999999348ms for query ""
2024-11-30 16:32:19.005 [info] Search by message took 64.56649999995716ms for query ""
2024-11-30 16:32:19.012 [info] Search by message took 65.9939000000013ms for query ""
2024-11-30 16:32:19.016 [info] Search by message took 64.3632000000216ms for query ""
2024-11-30 16:32:19.022 [info] Search by message took 62.595000000088476ms for query ""
2024-11-30 16:32:19.027 [info] Search by message took 56.87939999997616ms for query ""
2024-11-30 16:32:21.088 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-11-30 16:32:25.104 [warning] Retrying handshake with timeout 8000. Error:  [canceled] This operation was aborted
2024-11-30 16:32:25.104 [info] Handshake start
2024-11-30 16:32:26.099 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-11-30 16:32:31.114 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-11-30 16:32:34.113 [warning] Retrying handshake with timeout 16000. Error:  [canceled] This operation was aborted
2024-11-30 16:32:34.113 [info] Handshake start
2024-11-30 16:32:49.132 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-11-30 16:32:54.135 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-11-30 16:33:05.141 [warning] Retrying handshake with timeout 32000. Error:  [canceled] This operation was aborted
2024-11-30 16:33:05.141 [info] Handshake start
2024-11-30 16:33:20.172 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-11-30 16:33:25.180 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-11-30 16:33:52.186 [warning] Retrying handshake with timeout 64000. Error:  [canceled] This operation was aborted
2024-11-30 16:33:52.186 [info] Handshake start
2024-11-30 16:34:07.202 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-11-30 16:34:12.204 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-11-30 16:35:11.212 [warning] Retrying handshake with timeout 128000. Error:  [canceled] This operation was aborted
2024-11-30 16:35:11.213 [error] Handshake failed:
2024-11-30 16:35:11.213 [error] Error: timeout in handshake with retry
	at t.RepoClientMultiplexer.handshakeWithRetry (c:\Users\c\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:813516)
	at async v.getServerStatus (c:\Users\c\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:830054)
	at async v.startIndexingRepository (c:\Users\c\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:832745)
2024-11-30 16:35:11.213 [error] Handshake failed.
2024-11-30 16:35:11.214 [info] Indexing job successfully done or aborted.

==========================
Version: 0.43.5
VSCode Version: 1.93.1
Commit: 2eaa79a1b14cff5d1c78a2c358a08be16a8e5a0
Date: 2024-11-27T09:11:51.854Z (2 days ago)
Electron: 30.5.1
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

@danperks

**Comment by 27Bslash6** [comment]
Same as @c00134744 - would be nice if Cursor's indexing feature respected VSCode proxy configuration so I can bypass system-level proxies and SSL interception.

**Comment by danielkubat** [comment]
Those who are still facing this issue, did you try to **Disable Http2**? The issue is now fully resolved for me, even when connecting via corporate proxy.

![image](https://github.com/user-attachments/assets/a8a336a0-8892-443c-9efb-3e09194caa37)

**Comment by hermandr** [comment]
2024-12-17 14:21:06.253 [info] InternalRepoInfo constructor with preferredEmbeddingModel 0
2024-12-17 14:21:06.255 [info] Setting indexing intent to should-index
2024-12-17 14:21:06.259 [info] InternalRepoInfo constructor with preferredEmbeddingModel 0
2024-12-17 14:21:06.266 [info] Creating merkle client.
2024-12-17 14:21:06.266 [info] Done creating merkle client.
2024-12-17 14:21:06.266 [info] Doing a startup handshake.
2024-12-17 14:21:06.400 [info] Finished initializing merkle tree in 78.28407199960202 ms.
2024-12-17 14:21:06.400 [info] Doing the initial handshake with hash: 0db1fda139dab41728b278059d2aff66c609549772d68522a8e93f0d01dfdde6
2024-12-17 14:21:06.403 [info] Handshake start
2024-12-17 14:21:08.026 [error] Error Checking Connection: [unavailable]
2024-12-17 14:21:08.027 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-12-17 14:21:09.269 [warning] Retrying handshake with timeout 4000. Error:  [unavailable]
2024-12-17 14:21:09.269 [info] Handshake start
2024-12-17 14:21:14.034 [warning] Retrying handshake with timeout 8000. Error:  [unavailable]
2024-12-17 14:21:14.034 [info] Handshake start
2024-12-17 14:21:15.568 [error] Error Checking Connection: [unavailable]
2024-12-17 14:21:15.569 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-12-17 14:21:22.811 [warning] Retrying handshake with timeout 16000. Error:  [unavailable]
2024-12-17 14:21:22.811 [info] Handshake start
2024-12-17 14:21:24.384 [error] Error Checking Connection: [unavailable]
2024-12-17 14:21:24.385 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-12-17 14:21:33.021 [info] Search by sha took 29.73665599990636ms for query ""
2024-12-17 14:21:33.038 [info] Search by message took 55.68685000017285ms for query ""
2024-12-17 14:21:39.625 [warning] Retrying handshake with timeout 32000. Error:  [unavailable]
2024-12-17 14:21:39.625 [info] Handshake start
2024-12-17 14:21:39.938 [info] Search by message took 37.895245000720024ms for query ""
2024-12-17 14:21:39.944 [info] Search by message took 26.955276999622583ms for query ""
2024-12-17 14:21:39.944 [info] Search by sha took 35.97531499993056ms for query ""
2024-12-17 14:21:39.945 [info] Search by sha took 18.477207999676466ms for query ""
2024-12-17 14:21:41.193 [error] Error Checking Connection: [unavailable]
2024-12-17 14:21:41.194 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-12-17 14:22:12.424 [warning] Retrying handshake with timeout 64000. Error:  [unavailable]
2024-12-17 14:22:12.424 [info] Handshake start
2024-12-17 14:22:14.064 [error] Error Checking Connection: [unavailable]
2024-12-17 14:22:14.065 [info] Creating Indexing Repo client:  https://repo42.cursor.sh
2024-12-17 14:23:17.298 [warning] Retrying handshake with timeout 128000. Error:  [unavailable]
2024-12-17 14:23:17.299 [error] Handshake failed:
2024-12-17 14:23:17.299 [error] Error: timeout in handshake with retry
    at t.RepoClientMultiplexer.handshakeWithRetry (/home/herman/.cursor-server/bin/a846435528b4b760494a836f96f0739889253530/extensions/cursor-retrieval/dist/main.js:2:813516)
    at v.getServerStatus (/home/herman/.cursor-server/bin/a846435528b4b760494a836f96f0739889253530/extensions/cursor-retrieval/dist/main.js:2:830054)
    at v.startIndexingRepository (/home/herman/.cursor-server/bin/a846435528b4b760494a836f96f0739889253530/extensions/cursor-retrieval/dist/main.js:2:832745)
2024-12-17 14:23:17.299 [error] Handshake failed.

-----------

Version: 0.43.6
VSCode Version: 1.93.1
Commit: a846435528b4b760494a836f96f0739889253530
Date: 2024-12-06T05:11:55.168Z
Electron: 30.5.1
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22635

**Comment by jamie0walton** [comment]
This is happening for me on a firewalled debian ssh session using ssh from win 11. In the Debian host I've set the proxy in .bashrc and curl https://repo42.cursor.sh provides a welcome to cursor message. However the shell session that is attempting to access repo421.cursor.sh doesn't appear to be aware of the proxy settings.

**Comment by Ma-1003** [comment]
I'm a Chinese student. When I connect to my school's server via SSH to run programs, it prompts "handshake failed".
![image](https://github.com/user-attachments/assets/2ede11ae-e97c-490f-b3b5-9438d78b2ea7)
 However, when I open the local project with cursor, indexing works normally.
![image](https://github.com/user-attachments/assets/08f4e3df-3beb-4842-b1e4-ca5e08b3ce79)
 I think it's a server issue, but I don't have the permission to modify the server's DNS. Do you have any suggestions or ideas to solve this problem? Thank you! :) I use Windows 10.

**Comment by DylanDelobel** [comment]
Same issue
```
2025-01-21 13:24:38.439 [info] Doing the initial handshake with hash: 2d691cf65f011dcfde65fe36c79e1305e63ae64e4c66e9d55cac1eca08bc48e5
2025-01-21 13:24:38.440 [info] Handshake start
2025-01-21 13:24:38.780 [info] Handshake timing: 340.4893000000002
2025-01-21 13:24:40.793 [warning] Retrying handshake with timeout 4000. Error:  FastRepoInitHandshakeResponse_Status.FAILURE in handshakeWithRetry
2025-01-21 13:24:40.793 [info] Handshake start
2025-01-21 13:24:40.918 [info] Handshake timing: 126.48109999999997
2025-01-21 13:24:44.929 [warning] Retrying handshake with timeout 8000. Error:  FastRepoInitHandshakeResponse_Status.FAILURE in handshakeWithRetry
2025-01-21 13:24:44.929 [info] Handshake start
2025-01-21 13:24:45.052 [info] Handshake timing: 123.89649999999892
2025-01-21 13:24:53.055 [warning] Retrying handshake with timeout 16000. Error:  FastRepoInitHandshakeResponse_Status.FAILURE in handshakeWithRetry
2025-01-21 13:24:53.056 [info] Handshake start
2025-01-21 13:24:53.175 [info] Handshake timing: 120.29859999999826
2025-01-21 13:25:09.183 [warning] Retrying handshake with timeout 32000. Error:  FastRepoInitHandshakeResponse_Status.FAILURE in handshakeWithRetry
2025-01-21 13:25:09.183 [info] Handshake start
2025-01-21 13:25:09.306 [info] Handshake timing: 123.41860000000452
2025-01-21 13:25:41.316 [warning] Retrying handshake with timeout 64000. Error:  FastRepoInitHandshakeResponse_Status.FAILURE in handshakeWithRetry
2025-01-21 13:25:41.316 [info] Handshake start
2025-01-21 13:25:41.432 [info] Handshake timing: 117.06819999999425
```

**Comment by raulgad** [comment]
Same issue. MacOS Sequoia 15.2. Was going to buy a subscription, but now I highly doubt it.

**Comment by yusufsiregar44** [comment]
The same issue is happening now. My OS is MacOS Sequoia 15.2.

Version: 0.44.11
VSCode Version: 1.93.1
Commit: fe574d0820377383143b2ea26aa6ae28b3425220
Date: 2025-01-03T07:59:06.361Z (2 wks ago)
Electron: 30.5.1
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.2.0

![Image](https://github.com/user-attachments/assets/17100bfe-dda0-4da6-967a-14405efd1a9a)

**Comment by ostwalprasad** [comment]
Same issue. Lot of people got this issue today.

**Comment by smaga38** [comment]
The same issue is happening now. Windows 11
Version: 0.44.11
VSCode Version: 1.93.1
Commit: fe574d0820377383143b2ea26aa6ae28b3425220
Date: 2025-01-03T07:59:06.361Z
Electron: 30.5.1
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by chaosIV** [comment]
help 😭😭😭😭😭😭
版本: 0.44.11
提交: 1.93.1
日期: fe574d0820377383143b2ea26aa6ae28b3425220
Electron: 2025-01-03T07:59:06.361Z
ElectronBuildId: 30.5.1
Chromium: undefined
Node.js: 124.0.6367.243
V8: 20.16.0
OS: 12.4.254.20-electron.0

**Comment by yusufsiregar44** [comment]
@danperks Can we pin this issue again for everyone's visibility? It appears to be affecting many people.

**Comment by DevGuyRash** [comment]
I'm trying to use cursor and am experiencing this issue right now. Have tried re-signing in as well. Handshake fails every time.

**Comment by sk-tjdownes** [comment]
Same

Version: 0.45.0
VSCode Version: 1.96.2
Commit: f06cc5e62b757b2bf61ec052a8701fb2da9ded20
Date: 2025-01-20T19:17:28.428Z
Electron: 32.2.6
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

![Image](https://github.com/user-attachments/assets/3a090ad6-b40a-4d74-96b1-c37d46148e9f)

**Comment by amojury** [comment]
same

**Comment by CN-CJ** [comment]
same

版本: 0.44.11
提交: 1.93.1
日期: fe574d0820377383143b2ea26aa6ae28b3425220
Electron: 2025-01-03T07:59:06.361Z
ElectronBuildId: 30.5.1
Chromium: undefined
Node.js: 124.0.6367.243
V8: 20.16.0
OS: 12.4.254.20-electron.0

**Comment by rshabhsinha** [comment]
facing this exact same issue

**Comment by serend1p1ty** [comment]
Same issue here.

![Image](https://github.com/user-attachments/assets/ab3dac8e-2aa8-4333-adfd-c90ad80405ef)

![Image](https://github.com/user-attachments/assets/9d6524a5-0335-490c-9159-b7975ea45f38)

**Comment by bgbg** [comment]
Related to this https://forum.cursor.com/t/cursor-cannot-create-index-behind-corporate-proxy/31317

I too, experience this problem when working on an SSH project that requires me to use corporate VPN

**Comment by danielkubat** [comment]
> Related to this https://forum.cursor.com/t/cursor-cannot-create-index-behind-corporate-proxy/31317
> 
> I too, experience this problem when working on an SSH project that requires me to use corporate VPN

did you try to disable http2? for me, it fixed the issue.

`"cursor.general.disableHttp2": true,`

**Comment by jamie0walton** [comment]
> > Related to this https://forum.cursor.com/t/cursor-cannot-create-index-behind-corporate-proxy/31317
> > I too, experience this problem when working on an SSH project that requires me to use corporate VPN
> 
> did you try to disable http2? for me, it fixed the issue.
> 
> `"cursor.general.disableHttp2": true,`

OK, I do NOT have an issue with a corporate proxy however this setting clearly changes something about the way the indexing works as indexing code through an SSH connection works with this change for me.

Thanks!

**Comment by tblatrille** [comment]
> > Related to this https://forum.cursor.com/t/cursor-cannot-create-index-behind-corporate-proxy/31317
> > I too, experience this problem when working on an SSH project that requires me to use corporate VPN
> 
> did you try to disable http2? for me, it fixed the issue.
> 
> `"cursor.general.disableHttp2": true,`

This fixed it for me. thanks

**Comment by zachsa999** [comment]
esp-idf broke codebase indexing for me. I uninstalled that plugin and it worked perfectly.

**Comment by MattMorgis** [comment]
I had the same issue in a dev container on macOS host with corporate firewall. I was able to `curl` and make requests from the container through the firewall just fine, but always got handshake failed with indexing. 

`"cursor.general.disableHttp2": true` in my project settings did the trick as well

**Comment by BadaLeexxx** [comment]
I connected to remote server A, codebase not indexed. The cursor version is 0.44.11. I tried uninstalling and reinstalling, logging out and back in, and disabling http2. The problem is still the same. However, when I connected to remote server B, this function worked. What should I do?

![Image](https://github.com/user-attachments/assets/de362aa2-500c-45f3-ac0b-49fc61faf835)

![Image](https://github.com/user-attachments/assets/45be902d-1ccb-4c77-bf2b-4c2cf2667042)

![Image](https://github.com/user-attachments/assets/543f30bb-64e4-4ec9-bdd5-421b2f6883ad)

**Comment by maxlk96** [comment]
Having the same issue..

Version: 0.45.11
VSCode Version: 1.96.2
Commit: f5f18731406b73244e0558ee7716d77c8096d150
Date: 2025-02-07T09:43:58.555Z
Electron: 32.2.6
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22635

**Comment by kkarski** [comment]
Same issue. Tried logging out and in again, disabled HTTP2...still same handshake issue.

`Version: 0.45.11
VSCode Version: 1.96.2
Commit: f5f18731406b73244e0558ee7716d77c8096d150
Date: 2025-02-07T09:43:58.555Z
Electron: 32.2.6
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.9.3-76060903-generic`

**Comment by maxlk96** [comment]
No word on this...? I'm paying for a pro subscription, which I can not properly use without codebase indexing...

**Comment by red7x** [comment]
Same issue. Is there a fix plan for this issue? I am considering purchasing a pro subscription.
```
Version: 0.45.15 (user setup)
VSCode Version: 1.96.2
Commit: 73dd83bb6f8e3a3704ad8078a8e455ac6d4260d0
Date: 2025-02-22T10:19:07.356Z
Electron: 32.2.6
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by maxlk96** [comment]
Working for me now with 0.46

https://forum.cursor.com/t/codebase-indexing-handshake-failed/21471/29?u=maxlk96

**Comment by zoowayss** [comment]
<img width="1564" alt="Image" src="https://github.com/user-attachments/assets/5932b82b-db39-47c0-a2a9-8aa56ab43163" />
CursorSettiong -> open editor settings -> Application -> proxy ; set up your proxy . It work for me

**Comment by MattMorgis** [comment]
I have the issue inside a VS Code dev container only, not on my host machine. My machine does have ZScaler installed and Cursor indexing & agent both work fine when running on my host. 

I copy the ZScaler root cert into my container and set `NODE_EXTRA_CA_CERTS`, `SSL_CERT_FILE`, along with others. 
If I disable http/2 in the dev container, indexing will work but the agent gets timeouts when calling tools. I don't think that's the right fix though because it works with http/2 outside of the container on my host. With http/2 enabled in the container, agent mode works great, but indexing fails with a handshake. 

It feels like the indexing process is honoring either NODE_EXTRA_CA_CERTS or `http_proxy`/`https_proxy`?

**Comment by Minisaints** [comment]
I'm using Cloudflare WARP and I get this handshake error. Disabling HTTP2 setting within Cursor resolved it.
