### ISSUE TITLE
AppImage linux version can not run on Kylin V10

### ISSUE THREAD

**Issue by Drreeww** [getcursor/cursor#219]
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_CursorEzJpo1/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_CursorEzJpo1/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_CursorEzJpo1/resources/app.asar/.webpack/main/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109416)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_CursorEzJpo1/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_CursorEzJpo1/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_CursorEzJpo1/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_CursorEzJpo1/resources/app.asar/.webpack/main/index.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_CursorEzJpo1/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_CursorEzJpo1/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
[15316:0324/201739.114247:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[15316:0324/201739.114352:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[15367:0324/201739.226424:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[15367:0324/201739.226520:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[15367:0324/201739.226549:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
No protocol specified
[15367:0324/201739.228634:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[15367:0324/201739.228693:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[15367:0324/201739.228714:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[15367:0324/201739.228746:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[15367:0324/201739.259685:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[15383:0324/201739.271579:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[15383:0324/201739.271647:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[15383:0324/201739.271669:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
No protocol specified
[15383:0324/201739.271771:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: 

Could not open the default X display.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[15383:0324/201739.271802:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[15383:0324/201739.271871:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[15383:0324/201739.271899:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[15383:0324/201739.273320:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[15390:0324/201739.302553:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[15390:0324/201739.302625:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[15390:0324/201739.302664:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Not initialized.
[15390:0324/201739.302688:ERROR:gl_display.cc(920)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[15390:0324/201739.302715:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[15390:0324/201739.303925:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
No protocol specified
No protocol specified
[15406:0324/201739.326608:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by houchaowei** [comment]
> innerError Error: Cannot find module '../build/Debug/pty.node' Require stack:
> 
> * /tmp/.mount_CursorEzJpo1/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
> * /tmp/.mount_CursorEzJpo1/resources/app.asar/node_modules/node-pty/lib/index.js
> * /tmp/.mount_CursorEzJpo1/resources/app.asar/.webpack/main/index.js
> * at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
>   at n._resolveFilename (node:electron/js2c/browser_init:2:109416)
>   at Module._load (node:internal/modules/cjs/loader:811:27)
>   at f._load (node:electron/js2c/asar_bundle:2:13328)
>   at Module.require (node:internal/modules/cjs/loader:1035:19)
>   at require (node:internal/modules/cjs/helpers:102:18)
>   at Object. (/tmp/.mount_CursorEzJpo1/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
>   at Module._compile (node:internal/modules/cjs/loader:1141:14)
>   at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
>   at Module.load (node:internal/modules/cjs/loader:1011:32) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/tmp/.mount_CursorEzJpo1/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
>   '/tmp/.mount_CursorEzJpo1/resources/app.asar/node_modules/node-pty/lib/index.js',
>   '/tmp/.mount_CursorEzJpo1/resources/app.asar/.webpack/main/index.js',
>   undefined
>   ]
>   }
>   A JavaScript error occurred in the main process
>   Uncaught Exception:
>   Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_CursorEzJpo1/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)
>   at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
>   at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
>   at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
>   at Module.load (node:internal/modules/cjs/loader:1011:32)
>   at Module._load (node:internal/modules/cjs/loader:846:12)
>   at f._load (node:electron/js2c/asar_bundle:2:13328)
>   at Module.require (node:internal/modules/cjs/loader:1035:19)
>   at require (node:internal/modules/cjs/helpers:102:18)
>   at Object. (/tmp/.mount_CursorEzJpo1/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
>   at Module._compile (node:internal/modules/cjs/loader:1141:14)
>   [15316:0324/201739.114247:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
>   [15316:0324/201739.114352:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
>   No protocol specified
>   No protocol specified
>   No protocol specified
>   No protocol specified
>   No protocol specified
>   [15367:0324/201739.226424:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
>   ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
>   [15367:0324/201739.226520:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
>   [15367:0324/201739.226549:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
>   No protocol specified
>   [15367:0324/201739.228634:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
>   ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
>   [15367:0324/201739.228693:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
>   [15367:0324/201739.228714:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
>   [15367:0324/201739.228746:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
>   [15367:0324/201739.259685:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
>   No protocol specified
>   No protocol specified
>   No protocol specified
>   No protocol specified
>   No protocol specified
>   [15383:0324/201739.271579:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
>   ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
>   [15383:0324/201739.271647:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
>   [15383:0324/201739.271669:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
>   No protocol specified
>   [15383:0324/201739.271771:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289:
> 
> Could not open the default X display. ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display. [15383:0324/201739.271802:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display. [15383:0324/201739.271871:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED [15383:0324/201739.271899:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed. [15383:0324/201739.273320:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization No protocol specified No protocol specified No protocol specified No protocol specified No protocol specified [15390:0324/201739.302553:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1 ERR: DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1 [15390:0324/201739.302625:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Not initialized. ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Not initialized. [15390:0324/201739.302664:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Not initialized. [15390:0324/201739.302688:ERROR:gl_display.cc(920)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED [15390:0324/201739.302715:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed. [15390:0324/201739.303925:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization No protocol specified No protocol specified [15406:0324/201739.326608:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

I have encountered this issue as well.

**Comment by yc-huang** [comment]
same error on ubuntu 18.04...

**Comment by zuxunyang** [comment]
me too.

**Comment by truell20** [comment]
Is this still happening in the newest version?

**Comment by Drreeww** [comment]
thanks. the newest version Cursor can run on my computer, but still raise some error message:[uncaught exception in main]: Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found, I just use a moment, find two small issue: can not install recommend python extension, and close the Cursor GUI will fail  due to the File permission

**Comment by danperks** [comment]
Thanks for the reply @Drreeww.

As this issue is resolved, I will close this issue, but please make new Issues for the other problems you've been having, as it's likely other are having similar issues too!

Thanks :)
