### ISSUE TITLE
Failed to install rust language server, Error: EROFS: read-only file system

### ISSUE THREAD

**Issue by eval-exec** [getcursor/cursor#221]
I download `Cursor-0.1.6.AppImage` from release page.
then launch cursor 0.1.6, click the setting icon on the top right corner, then click `install` button on rust language server. 

The full logs are:
```bash
$ ~/Downloads/Cursor-0.1.6.AppImage
20:34:08.346 › Made main window
20:34:08.447 › setting up handle get_folder
20:34:08.447 › setting up handle getClipboard
20:34:08.448 › setting up handle get_file
20:34:08.485 › setting up index
20:34:08.486 › setup index
20:34:10.883 › found settings
20:34:10.956 › starting server for copilot
20:34:10.957 › Store has language copilot {
  name: 'copilot',
  running: true,
  downloadedInfo: {
    isNode: true,
    command: '/tmp/.mount_CursorX807pm/resources/lsp/copilot/dist/agent.js',
    args: []
  }
}
20:34:10.974 › !!!!!!!!!Finished spawning child process copilot
20:34:10.976 › created connection copilot
20:34:10.985 › starting server for copilot
20:34:10.986 › Store has language copilot {
  name: 'copilot',
  running: true,
  downloadedInfo: {
    isNode: true,
    command: '/tmp/.mount_CursorX807pm/resources/lsp/copilot/dist/agent.js',
    args: []
  }
}
20:34:10.996 › !!!!!!!!!Finished spawning child process copilot
20:34:10.997 › created connection copilot
20:34:11.142 › lang copilot stderr: node:internal/modules/cjs/loader:966
  throw err;
  ^

Error: Cannot find module '/tmp/.mount_CursorX807pm/resources/lsp/copilot/dist/agent.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

20:34:15.037 › Store does not have language downloaded rust
20:34:15.038 › INSTALLING
20:34:16.382 › Error occurred in handler for 'installLS': Error: EROFS: read-only file system, mkdir '/tmp/.mount_CursorDT7WnK/resources/lsp/rust'
    at Object.mkdirSync (node:fs:1386:3)
    at Me.<anonymous> (/tmp/.mount_CursorDT7WnK/resources/app.asar/.webpack/main/index.js:8:832618)
    at Generator.next (<anonymous>)
    at o (/tmp/.mount_CursorDT7WnK/resources/app.asar/.webpack/main/index.js:8:825782)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
20:34:25.752 › Store does not have language downloaded rust
20:34:25.753 › INSTALLING
20:34:26.413 › Error occurred in handler for 'installLS': Error: EROFS: read-only file system, mkdir '/tmp/.mount_CursorDT7WnK/resources/lsp/rust'
    at Object.mkdirSync (node:fs:1386:3)
    at Me.<anonymous> (/tmp/.mount_CursorDT7WnK/resources/app.asar/.webpack/main/index.js:8:832618)
    at Generator.next (<anonymous>)
    at o (/tmp/.mount_CursorDT7WnK/resources/app.asar/.webpack/main/index.js:8:825782)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

```

What can I do to help you get deeper on this error?

**Comment by alexwebdevs** [comment]
@eval-exec , @truell20 my fix on C lang server install issue would fix most of language server install issues:
https://github.com/getcursor/cursor/pull/214
my PR would make that rust server install issue

**Comment by truell20** [comment]
thanks @alexwebdevs! merged

**Comment by eval-exec** [comment]
> 

Thank you :heart:
