### ISSUE TITLE
Remote-SSH: Unable to "Search files by name"

### ISSUE THREAD

**Issue by Kellen-Stuart** [getcursor/cursor#2252]
1) If you can, please include a screenshot of your problem
When using Remote-SSH, the "Search files by name" completely does not work. 

![image](https://github.com/user-attachments/assets/f0fc20cc-48fb-43d3-a72c-7b7f2e7cbc57)

2) Please include the name of your operating system

I am on a Windows 11 Pro X86 OS remoting into a MacBook Pro Apple M1 Pro on Sonoma 14.6.1

3) If you can, steps to reproduce are super helpful
1. SSH into a machine on local network using public private key
2. Search for file
3. No files are suggested. 

I have even tried just running `cursor ./path/to/file.ts` and it sometimes works and sometimes throws an exception back at me. 

Love the IDE but need this basic stuff to work before I make the transition, especially to pay.

**Comment by chitung-reevo** [comment]
same issue here

**Comment by Epikem** [comment]
for me, this resolved the issue.
```
(base) epikem@epi-mini bin % pwd
/Users/epikem/.cursor-server/cli/servers/Stable-a846435528b4b760494a836f96f0739889253530/server/node_modules/@vscode/ripgrep/bin
(base) epikem@epi-mini bin % cp ./rg ./rgArm
```

**Comment by Epikem** [comment]
After updating “Cursor,” the search stopped working again, and I found in the logs that it was looking in a different path, as shown below. It would be great if this issue could be fixed so that the process doesn’t need to be repeated every time.

<img width="804" alt="image" src="https://github.com/user-attachments/assets/d0af3e11-aef5-49bf-86b2-f69ef0021917" />

```
2024-12-21 09:39:49.858 [error] Error: spawn /Users/epikem/.cursor-server/cli/servers/Stable-1d610252e6812bf33245763f0742a534fd0f1d90/server/node_modules/@vscode/ripgrep/bin/rgArm ENOENT
    at M (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3082:6695)
    at vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3087:5052
    at async vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3087:3186
```

**Comment by self-transition** [comment]
> for me, this resolved the issue.
> 
> ```
> (base) epikem@epi-mini bin % pwd
> /Users/epikem/.cursor-server/cli/servers/Stable-a846435528b4b760494a836f96f0739889253530/server/node_modules/@vscode/ripgrep/bin
> (base) epikem@epi-mini bin % cp ./rg ./rgArm
> ```

Thx, it works, But my CPU is x86_64 architecture. ,So its supposed to:

```
cp ./rg ./rgX64
```
