### ISSUE TITLE
Cursor doesn't show directory or files which I created from terminal.

### ISSUE THREAD

**Issue by eval-exec** [getcursor/cursor#228]
I open a project which contains some directories and files by cursor `c22c98361d77665feef891f3d57702421c92f2e3`.
Then I create a dir and file in the root of the project, but the newly created directory doesn't show in the file struct tree in the left sidebar.

**Comment by boxizen** [comment]
What version do you use, and how do you reproduce it? It is normal for me to use `v0.1.7` for testing.

**Comment by eval-exec** [comment]
> What version do you use, and how do you reproduce it? It is normal for me to use `v0.1.7` for testing.


It occurs on this commit `c22c98361d77665feef891f3d57702421c92f2e3`.

It may be already fixed if this bug didn't occur on latest commit or `v0.1.7`. :heart:

**Comment by eval-exec** [comment]
@boxizen I reproduced this on `v0.1.7`.

Reproduce steps:
1. Launch `Cursor-0.1.7.AppImage`
2. In cursor main window, click File->Open Folder
3. Select a non-empty folder which contains some directory and files.
4. Open my terminal (I use alacritty), create a file in terminal `pwd > test.txt`
5. Return focus to cursor's main window, but the `test.txt` not show in the file structure tree. :sob: 

The full logs is:
```bash
$ ~/Downloads/Cursor-0.1.7.AppImage
[2164592:0325/183010.855575:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[2164592:0325/183010.855685:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[2164592:0325/183010.855765:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[2164592:0325/183010.860713:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[2164592:0325/183010.860818:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[2164592:0325/183010.860912:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[2164592:0325/183010.861015:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[2164592:0325/183010.886917:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
18:30:10.981 › Made main window
18:30:11.016 › setting up handle get_folder
18:30:11.017 › setting up handle getClipboard
18:30:11.017 › setting up handle get_file
18:30:11.043 › setting up index
18:30:11.044 › setup index
[2164629:0325/183011.150774:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[2164629:0325/183011.150882:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[2164629:0325/183011.150961:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[2164629:0325/183011.153595:ERROR:angle_platform_impl.cc(43)] Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1004 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[2164629:0325/183011.153655:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[2164629:0325/183011.153742:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[2164629:0325/183011.153772:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[2164629:0325/183011.154899:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: /usr/lib/dri/vdpau_drv_video.so init failed
18:30:17.887 › found settings
18:30:18.090 › starting server for copilot
18:30:18.093 › Store has language copilot {
  name: 'copilot',
  running: true,
  downloadedInfo: {
    isNode: true,
    command: '/tmp/.mount_CursorX807pm/resources/lsp/copilot/dist/agent.js',
    args: []
  }
}
18:30:18.111 › !!!!!!!!!Finished spawning child process copilot
18:30:18.113 › created connection copilot
18:30:18.125 › starting server for copilot
18:30:18.127 › Store has language copilot {
  name: 'copilot',
  running: true,
  downloadedInfo: {
    isNode: true,
    command: '/tmp/.mount_CursorX807pm/resources/lsp/copilot/dist/agent.js',
    args: []
  }
}
18:30:18.139 › !!!!!!!!!Finished spawning child process copilot
18:30:18.140 › created connection copilot
18:30:18.232 › lang copilot stderr: node:internal/modules/cjs/loader:966
  throw err;
  ^

Error: Cannot find module '/tmp/.mount_CursorX807pm/resources/lsp/copilot/dist/agent.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

18:30:33.522 › Opening folder: /home/exec/Temp/te
18:30:33.552 › Error occurred in handler for 'sendRequestLS': Error: Pending response rejected since connection got disposed
    at Object.dispose (/tmp/.mount_CursorgKmQdf/resources/app.asar/.webpack/main/index.js:8:764746)
    at je.killServer (/tmp/.mount_CursorgKmQdf/resources/app.asar/.webpack/main/index.js:8:882284)
    at node:electron/js2c/browser_init:2:97574
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81087)
    at EventEmitter.emit (node:events:513:28)
18:30:33.570 › starting server for copilot
18:30:33.573 › Store has language copilot {
  name: 'copilot',
  running: true,
  downloadedInfo: {
    isNode: true,
    command: '/tmp/.mount_CursorX807pm/resources/lsp/copilot/dist/agent.js',
    args: []
  }
}
18:30:33.584 › !!!!!!!!!Finished spawning child process copilot
18:30:33.584 › created connection copilot
18:30:33.682 › lang copilot stderr: node:internal/modules/cjs/loader:966
  throw err;
  ^

Error: Cannot find module '/tmp/.mount_CursorX807pm/resources/lsp/copilot/dist/agent.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}


```

Some information may help solve this issue:
```
$ uname -a
Linux Mufasa 6.2.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 18 Mar 2023 01:06:36 +0000 x86_64 GNU/Linux
$ node --version
v19.8.1

```

**Comment by alexwebdevs** [comment]
@eval-exec fyi, the root directory of the terminal is not where you opened the folder, but the tutor directory.

**Comment by truell20** [comment]
Should be fixed in the newest version 🙂
