### ISSUE TITLE
[BUG]  Live Share error. ms-vsliveshare.vsliveshare, startup: false, activationEvent: 'onView:liveshare.session' 

### ISSUE THREAD

**Issue by ruslansenatorov** [getcursor/cursor#2439]
![image](https://github.com/user-attachments/assets/dd70a1cd-bd34-4f41-874b-60cb48cbe34a)

[info] Extension host with pid 82516 started
2024-11-30 11:47:27.975 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-11-30 11:47:27.980 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-11-30 11:47:27.996 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-11-30 11:47:28.052 [info] Eager extensions activated
2024-11-30 11:47:28.057 [info] ExtensionService#_doActivateExtension anysphere.cursor-always-local, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:28.125 [info] ExtensionService#_doActivateExtension anysphere.cursor-retrieval, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:28.177 [info] ExtensionService#_doActivateExtension anysphere.cursor-shadow-workspace, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:28.185 [info] ExtensionService#_doActivateExtension anysphere.cursor-tokenize, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:28.298 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:28.300 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:28.304 [info] ExtensionService#_doActivateExtension yy0931.vscode-sqlite3-editor, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:29.609 [info] Extension host terminating: renderer closed the MessagePort
2024-11-30 11:47:29.618 [error] ProxyResolver#resolveProxy DIRECT Canceled: Canceled
	at new I (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:35402)
	at P.U (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:167:6021)
	at K.<computed>.G.charCodeAt.N.CharCode.DollarSign.K.<computed> (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:167:3108)
	at O.resolveProxy (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:49806)
	at Object.resolveProxy (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:155:32473)
	at useProxySettings (/Applications/Cursor.app/Contents/Resources/app/node_modules.asar/@vscode/proxy-agent/out/index.js:179:16)
	at /Applications/Cursor.app/Contents/Resources/app/node_modules.asar/@vscode/proxy-agent/out/index.js:114:13
	at /Applications/Cursor.app/Contents/Resources/app/node_modules.asar/@vscode/proxy-agent/out/index.js:484:13 
2024-11-30 11:47:29.620 [info] Extension host with pid 82516 exiting with code 0
2024-11-30 11:47:30.555 [info] Extension host with pid 82522 started
2024-11-30 11:47:30.555 [info] Skipping acquiring lock for /Users/ruslansenatorov/Library/Application Support/Cursor/User/workspaceStorage/f1a42253c7eb63f044930b9d2c763f39.
2024-11-30 11:47:30.670 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-11-30 11:47:30.674 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: false, activationEvent: 'onCommand:git.api.getRepositories', root cause: vscode.git
2024-11-30 11:47:30.676 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python', root cause: ms-python.black-formatter
2024-11-30 11:47:30.712 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onLanguage:python'
2024-11-30 11:47:31.005 [info] ExtensionService#_doActivateExtension vscode.git, startup: false, activationEvent: 'onCommand:git.api.getRepositories'
2024-11-30 11:47:31.018 [info] ExtensionService#_doActivateExtension vscode.github, startup: false, activationEvent: '*'
2024-11-30 11:47:31.026 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
2024-11-30 11:47:31.101 [info] ExtensionService#_doActivateExtension ms-python.black-formatter, startup: false, activationEvent: 'onLanguage:python'
2024-11-30 11:47:31.108 [info] ExtensionService#_doActivateExtension ms-python.debugpy, startup: false, activationEvent: 'onLanguage:python'
2024-11-30 11:47:31.161 [info] Eager extensions activated
2024-11-30 11:47:31.178 [info] ExtensionService#_doActivateExtension anysphere.cursor-always-local, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:31.225 [info] ExtensionService#_doActivateExtension anysphere.cursor-retrieval, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:31.269 [info] ExtensionService#_doActivateExtension anysphere.cursor-shadow-workspace, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:31.278 [info] ExtensionService#_doActivateExtension anysphere.cursor-tokenize, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:31.398 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:31.401 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:31.405 [info] ExtensionService#_doActivateExtension yy0931.vscode-sqlite3-editor, startup: false, activationEvent: 'onStartupFinished'
2024-11-30 11:47:50.700 [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare, startup: false, activationEvent: 'onView:liveshare.session'

**Comment by leerob** [comment]
Thanks for opening this issue! We've moved our community support to the [Cursor Forum](https://forum.cursor.com) where you can get help from both the team and other users.

If this is a specific bug that you can still reproduce, please open a new issue with clear reproduction steps on the forum.

Thanks you!
