### ISSUE TITLE
When using an arm server, the file search function is not available

### ISSUE THREAD

**Issue by wodabo** [getcursor/cursor#2503]
NOTE: We will try our best to check Github Issues, but [forum.cursor.com](https://forum.cursor.com/) is our main site for bug reports / user feedback. We'd recommend you post there for the fastest response.
![image](https://github.com/user-attachments/assets/1414bdb2-cd82-4601-b8e5-c8ba64616bcf)

According to the error path, the ARM-related file does not exist

**Comment by wodabo** [comment]
[13:42:18.333] [server] server inflate progress: 1399/1965 (71%)
[13:42:18.343] [server] server inflate progress: 1499/1965 (76%)
[13:42:18.347] [server] server inflate progress: 1599/1965 (81%)
[13:42:18.354] [server] server inflate progress: 1699/1965 (86%)
[13:42:18.383] [server] server inflate progress: 1799/1965 (92%)
[13:42:18.389] [server] server inflate progress: 1899/1965 (97%)
[13:42:18.407] [server] server inflate progress: 1965/1965 (100%)
[13:42:18.407] [server] server entrypoint: cursor-server
[13:42:20.151] [server] Server integrity verified, version: 0.44.3 / 4cabe4501c19546ecce8b6afbf17d76b743bf410 / arm64 / 
[13:42:20.151] [server] Server setup complete
[13:42:20.152] [server] Starting server...
[13:42:20.152] [server] Starting server with command... Command { std: "/Users/zhong/.cursor-server/cli/servers/Stable-4cabe4501c19546ecce8b6afbf17d76b743bf410/server/bin/cursor-server" "--connection-token=remotessh" "--accept-server-license-terms" "--start-server" "--enable-remote-auto-shutdown" "--socket-path=/var/folders/05/15jbl1md5gzdz8pngl94t5c80000gn/T/cursor-ddc2f23a-ce67-4c7d-a4a4-2f9560f95ce7", kill_on_drop: false }
[13:42:20.152] [server] Server bound to /var/folders/05/15jbl1md5gzdz8pngl94t5c80000gn/T/cursor-ddc2f23a-ce67-4c7d-a4a4-2f9560f95ce7
[13:42:20.153] [server] Extension host agent listening on /var/folders/05/15jbl1md5gzdz8pngl94t5c80000gn/T/cursor-ddc2f23a-ce67-4c7d-a4a4-2f9560f95ce7
[13:42:20.153] [server] parsed location: "/var/folders/05/15jbl1md5gzdz8pngl94t5c80000gn/T/cursor-ddc2f23a-ce67-4c7d-a4a4-2f9560f95ce7"
[13:42:20.153] [server] 
[13:42:20.153] [server] Server started
[13:42:20.558] [server] [13:42:20] 
[13:42:20.559] [server] 
[13:42:20.559] [server] 
[13:42:20.560] [server] 
[13:42:20.560] [server] 
[13:42:20.563] [server] [13:42:20] Extension host agent started.
[13:42:20.592] [server] [13:42:20] [<unknown>][7c7d12a8][ExtensionHostConnection] New connection established.
[13:42:20.592] [server] [13:42:20] [<unknown>][bf0f8321][ManagementConnection] New connection established.
[13:42:20.596] [server] Generating translation files failed. Error: ENOENT: no such file or directory, open '/Users/zhong/.cursor-server/cli/servers/Stable-4cabe4501c19546ecce8b6afbf17d76b743bf410/server/out/nls.keys.json'
[13:42:20.596] [server]     at async open (node:internal/fs/promises:639:25)
[13:42:20.596] [server]     at async Object.readFile (node:internal/fs/promises:1249:14)
[13:42:20.597] [server]     at async s (/Users/zhong/.cursor-server/cli/servers/Stable-4cabe4501c19546ecce8b6afbf17d76b743bf410/server/out/vs/server/node/server.main.js:101:2332)
[13:42:20.597] [server]     at async f (/Users/zhong/.cursor-server/cli/servers/Stable-4cabe4501c19546ecce8b6afbf17d76b743bf410/server/out/vs/server/node/server.main.js:183:72918)
[13:42:20.597] [server]     at async a.start (/Users/zhong/.cursor-server/cli/servers/Stable-4cabe4501c19546ecce8b6afbf17d76b743bf410/server/out/vs/server/node/server.main.js:183:75730) {
[13:42:20.597] [server]   errno: -2,
[13:42:20.597] [server]   code: 'ENOENT',
[13:42:20.597] [server]   syscall: 'open',
[13:42:20.598] [server]   path: '/Users/zhong/.cursor-server/cli/servers/Stable-4cabe4501c19546ecce8b6afbf17d76b743bf410/server/out/nls.keys.json'
[13:42:20.598] [server] }
[13:42:21.180] [server] [13:42:20] [<unknown>][7c7d12a8][ExtensionHostConnection] <24436> Launched Extension Host Process.

**Comment by tmm1** [comment]
Hi, what OS and arch is the remote server?
