### ISSUE TITLE
Problem with linux instalation

### ISSUE THREAD

**Issue by maksim-glyzin** [getcursor/cursor#263]
Hi, guys. 

You should add to your setup.sh file following line (or you can manually add packages, which GYP is demand like make, g++, ...) :

`apt install build-essential`

Without that line beta-tester will get on the new system:

```
maksim@knife:~/cursor$ npm i
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated core-js@3.18.3: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.6.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.2
npm notice Run npm install -g npm@9.6.2 to update!
npm notice 
npm ERR! code 1
npm ERR! path /home/maksim/cursor/node_modules/node-pty
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@19.8.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.7 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v19.8.1/node-v19.8.1-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v19.8.1/node-v19.8.1-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v19.8.1/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v19.8.1/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/maksim/cursor/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/maksim/cursor/node_modules/node-pty/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/maksim/cursor/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/maksim/.cache/node-gyp/19.8.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/maksim/.cache/node-gyp/19.8.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/maksim/cursor/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/maksim/.cache/node-gyp/19.8.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/maksim/cursor/node_modules/node-pty',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/home/maksim/cursor/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /home/maksim/cursor/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/home/maksim/cursor/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /home/maksim/cursor/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/home/maksim/cursor/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /home/maksim/cursor/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /home/maksim/cursor/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/maksim/cursor/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:195:21)
npm ERR! gyp ERR! System Linux 5.19.0-38-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/home/maksim/cursor/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/maksim/cursor/node_modules/node-pty
npm ERR! gyp ERR! node -v v19.8.1
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maksim/.npm/_logs/2023-03-26T19_19_15_493Z-debug-0.log
```

Tested on:
`
Ubuntu 22.10
x86_64
`

**Comment by maksim-glyzin** [comment]
@noviceswing , add your error log.

**Comment by huykon** [comment]
I can not run the appImage file although I change the file permission. Dose any one know the problem?

**Comment by truell20** [comment]
Is this still happening for the newest version?

**Comment by huykon** [comment]
@truell20 yes right. I'm using ubuntu version 22.04

**Comment by danperks** [comment]
Seems like a repeat of #97, so I will close in favour of that one.
