### ISSUE TITLE
rust lsp install error

### ISSUE THREAD

**Issue by lazywhite** [getcursor/cursor#326]
cursor: 0.1.9
os: ubuntu 22.10
```
10:30:42.195 › Store does not have language downloaded rust
10:30:42.196 › INSTALLING
10:30:43.616 › Error occurred in handler for 'installLS': Error: EROFS: read-only file system, mkdir '/tmp/.mount_CursorJxD5eh/resources/lsp/rust'
    at Object.mkdirSync (node:fs:1386:3)
    at je.<anonymous> (/tmp/.mount_CursorJxD5eh/resources/app.asar/.webpack/main/index.js:8:832668)
    at Generator.next (<anonymous>)
    at o (/tmp/.mount_CursorJxD5eh/resources/app.asar/.webpack/main/index.js:8:825782)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by truell20** [comment]
Should be fixed in the newest version 🙂
