### ISSUE TITLE
Cursor is trying to download and run LSP files into it's own read-only directories, which all fail.

### ISSUE THREAD

**Issue by MostHated** [getcursor/cursor#355]
Please see the errors below: I believe persistent application data should probably be set to download and run from `$XDG_DATA_HOME` instead of trying to use the local read-only squashfs mount.
It would deceivingly work locally when testing, before you package the app as an app image, but once you do, it no longer would, as we see here.

Rust LSP failure:

```javascript

20:06:27.156 › Error occurred in handler for 'installLS': Error: EROFS: read-only file system, mkdir '/tmp/.mount_cursori7C2lf/resources/lsp/rust'
    at Object.mkdirSync (node:fs:1386:3)
    at Kt.<anonymous> (/tmp/.mount_cursori7C2lf/resources/app.asar/.webpack/main/index.js:8:864978)
    at Generator.next (<anonymous>)
    at o (/tmp/.mount_cursori7C2lf/resources/app.asar/.webpack/main/index.js:8:857959)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

```

Copilot failure:
```javascript

Error: Cannot find module '/tmp/.mount_cursori7C2lf/resources/lsp/copilot/dist/agent.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Thanks,
-MH

**Comment by raymond-ley** [comment]
Thank you for your feedback. This will be fixed in a future version, and I have the intention to fix it. :)

**Comment by danperks** [comment]
As v0.2.0 may have fixed this, and the developers have said they are aware, I'll make this as closed to keep the Issues clear, but feel free to comment and we can reopen this for you!
