### ISSUE TITLE
Use command "npm start" and get an error

### ISSUE THREAD

**Issue by galileoliu** [getcursor/cursor#397]
Log info as follows:

  ~/Documents/github/cursor   main ●  npm start

> cursor@0.1.11 start /Users/xxx/Documents/github/cursor
> electron-forge start

/Users/xxx/Documents/github/cursor/node_modules/listr2/dist/index.cjs:90
    this.path = [...task.listr.path ?? [], task.title].join(" > ");
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/xxx/Documents/github/cursor/node_modules/@electron-forge/cli/dist/electron-forge.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cursor@0.1.11 start: `electron-forge start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cursor@0.1.11 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2023-03-31T03_42_02_391Z-debug.log

**Comment by alexwebdevs** [comment]
@galileoliu share the development environment with us.

**Comment by danperks** [comment]
Due to a lack of activity, and the face this is regarding the v0.1.X codebase, I'll close this for now.

Feel free to comment and this can be reopened for you!
