### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Mingliang233** [getcursor/cursor#442]
I get an error when open Cursor.
macOS version: 13.3 (22E252)

```
Uncaught Exception:
Error: Failed to get 'userData' path
at u (/Applications/Cursor.app/Contents/Resources/app.asar/.webpack/main/index.js:8:155272)
at new e.exports (/Applications/Cursor.app/Contents/Resources/app.asar/.webpack/main/index.js:8:155666)
at /Applications/Cursor.app/Contents/Resources/app.asar/.webpack/main/index.js:8:823538
at /Applications/Cursor.app/Contents/Resources/app.asar/.webpack/main/index.js:8:903105
at Object.<anonymous> (/Applications/Cursor.app/Contents/Resources/app.asar/.webpack/main/index.js:8:903126)
at Module._compile (node:internal/modules/cjs/loader:1141:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13328)
```

**Comment by truell20** [comment]
Could you send a screen recording of this happening? Will help a ton for fixing this

**Comment by danperks** [comment]
As this is likely for v0.1.X versions of Cursor, and is probably fixed in the latest version, I'll close this for now.

If you continue to have this issue and want support, feel free to comment again and we can reopen this.
