### ISSUE TITLE
cursor 0.2 connot run in windows x64 

### ISSUE THREAD

**Issue by fawdlstty** [getcursor/cursor#458]
ref: #457

command output:

```
C:\Users\Administrator\AppData\Local\Programs\Cursor>Cursor.exe
[main 2023-04-06T16:46:51.246Z] update#ctor - updates are disabled as there is no update URL
[main 2023-04-06T16:46:51.251Z] Error: The module '\\?\C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\node_modules\.store\windows-mutex@0.4.1\node_modules\windows-mutex\build\Release\CreateMutex.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 106. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at R (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:87:699)
    at bindings (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\node_modules\.store\bindings@1.5.0\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\node_modules\.store\windows-mutex@0.4.1\node_modules\windows-mutex\index.js:1:99)
    at h._compile (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:87:1299)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at g (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:101)
    at c.load (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:87:1706)
    at c.load (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:86:67583)
    at E (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:10200)
    at Object.errorback (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:10321)
    at c.triggerErrorback (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:86:67947)
    at C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:86:67653
    at c.load (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:87:1723)
    at c.load (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:86:67583)
    at E (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:10200)
    at y._loadModule (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:10330)
    at y._resolve (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:89:452)
    at y.defineModule (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:6042)
    at y._relativeRequire (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:6728)
    at g (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:9306)
    at J.Ie (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:68837)
    at new Promise (<anonymous>)
    at pt.J (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:68815)
    at pt.I (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:68405)
    at C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:55087
    at v.invokeFunction (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:37:360)
    at pt.startup (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:55063)
    at async Oe.a (C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:87:4031) {
  code: 'ERR_DLOPEN_FAILED',
  phase: 'loading',
  moduleId: 'windows-mutex',
  neededBy: [ '===anonymous5===' ]
}
```

cnpm output:

```
C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app>cnpm rebuild
npm ERR! code 1
npm ERR! path C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\node_modules\.store\xterm@5.2.0-beta.29\node_modules\xterm
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run setup
npm ERR! > xterm@5.2.0-beta.29 presetup
npm ERR! > node ./bin/install-addons.js
npm ERR! node:internal/modules/cjs/loader:1078
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\node_modules\.store\xterm@5.2.0-beta.29\node_modules\xterm\bin\install-addons.js'
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:920:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }
npm ERR!
npm ERR! Node.js v18.15.0

npm ERR! A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-04-06T16_53_39_150Z-debug-0.log
```

log file content:

```
0 verbose cli D:\Software\Program\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\bin\npm-cli.js
1 info using npm@9.6.4
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\.npmrc Completed in 0ms
10 timing config:load:project Completed in 6ms
11 timing config:load:file:C:\Users\Administrator\.cnpmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:D:\Software\Program\nodejs\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 14ms
17 timing npm:load:configload Completed in 15ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm rebuild
21 verbose argv "--userconfig" "C:\\Users\\Administrator\\.cnpmrc" "--disturl" "https://cdn.npmmirror.com/binaries/node" "--registry" "https://registry.npmmirror.com" "rebuild"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 4ms
24 timing npm:load:display Completed in 6ms
25 verbose logfile logs-max:10 dir:C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-04-06T16_53_39_150Z-
26 verbose logfile C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-04-06T16_53_39_150Z-debug-0.log
27 timing npm:load:logFile Completed in 17ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 42ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 12 files
33 silly logfile done cleaning log files
34 timing build:queue Completed in 2ms
35 timing build:deps Completed in 2ms
36 timing build:queue Completed in 7ms
37 info run node-pty@0.11.0-beta29 prepare node_modules/.store/node-pty@0.11.0-beta29/node_modules/node-pty npm run build
38 info run xterm@5.2.0-beta.29 prepare node_modules/.store/xterm@5.2.0-beta.29/node_modules/xterm npm run setup
39 info run xterm@5.2.0-beta.29 prepare { code: 1, signal: null }
40 timing command:rebuild Completed in 3175ms
41 verbose stack Error: command failed
41 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
41 verbose stack     at ChildProcess.emit (node:events:513:28)
41 verbose stack     at maybeClose (node:internal/child_process:1091:16)
41 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
42 verbose pkgid xterm@5.2.0-beta.29
43 verbose cwd C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app
44 verbose Windows_NT 10.0.22000
45 verbose node v18.15.0
46 verbose npm  v9.6.4
47 error code 1
48 error path C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\node_modules\.store\xterm@5.2.0-beta.29\node_modules\xterm
49 error command failed
50 error command C:\Windows\system32\cmd.exe /d /s /c npm run setup
51 error > xterm@5.2.0-beta.29 presetup
51 error > node ./bin/install-addons.js
52 error node:internal/modules/cjs/loader:1078
52 error   throw err;
52 error   ^
52 error
52 error Error: Cannot find module 'C:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\node_modules\.store\xterm@5.2.0-beta.29\node_modules\xterm\bin\install-addons.js'
52 error     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
52 error     at Module._load (node:internal/modules/cjs/loader:920:27)
52 error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
52 error     at node:internal/main/run_main_module:23:47 {
52 error   code: 'MODULE_NOT_FOUND',
52 error   requireStack: []
52 error }
52 error
52 error Node.js v18.15.0
53 verbose exit 1
54 timing npm Completed in 3248ms
55 verbose unfinished npm timer build 1680800019514
56 verbose unfinished npm timer build:links 1680800019516
57 verbose unfinished npm timer build:run:prepare 1680800019524
58 verbose unfinished npm timer build:run:prepare:node_modules/.store/node-pty@0.11.0-beta29/node_modules/node-pty 1680800019524
59 verbose unfinished npm timer build:run:prepare:node_modules/.store/xterm@5.2.0-beta.29/node_modules/xterm 1680800019576
60 verbose code 1
61 error A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-04-06T16_53_39_150Z-debug-0.log
```

**Comment by truell20** [comment]
Did you try opening Cursor from the normal windows app bar or from the command line? Could you send a screen recording? Would help a ton for fixing this 🙏

**Comment by fawdlstty** [comment]
The actual reason for the problem is that the published cursor software has a dependency on node/npm, but it should be packaged during actual publishing to avoid users relying on node/npm.

**Comment by danperks** [comment]
Your video does not seem to load for me @fawdlstty

**Comment by fawdlstty** [comment]
1. open url for chrome new tab <https://user-images.githubusercontent.com/7323999/230638925-8d3bfddc-64b3-4abf-8866-96c22a78abc7.mp4>
2. right menu, save as local file
3. open video file

**Comment by fawdlstty** [comment]
you can try download the video from <https://www.fawdlstty.com/out.mp4>, I have upload it to my own server

**Comment by danperks** [comment]
That worked, thanks, may have just been on my end. Does anything different happen if you open it with the Desktop shortcut, or clicking the .exe itself? Other than that, I think we'll need a developer to help you out here.

**Comment by fawdlstty** [comment]
Double clicking will open the window and instantly exit, with the same effect as the video

**Comment by danperks** [comment]
Only other thing I can suggest besides the help of a developer is disabling your anti-virus as a test, as some people with an anti-virus named 360 were having issues until they disabled it.

**Comment by danperks** [comment]
Noted. @truell20 maybe soenthing to do? Quite a few people hitting this bug, maybe less so in the later versions?

**Comment by benherve** [comment]
same here :(
