### ISSUE TITLE
cursor 0.2 crashed when start.

### ISSUE THREAD

**Issue by nirenyang** [getcursor/cursor#459]
os: win10 64bit

> C:\Users\hello\AppData\Local\Programs\Cursor>
> [main 2023-04-06T17:22:18.979Z] update#ctor - updates are disabled as there is no update URL
> [main 2023-04-06T17:22:18.988Z] Error: Cannot find module 'windows-mutex'
> Require stack:
> - C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js
> -
>     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
>     at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
>     at Module._load (node:internal/modules/cjs/loader:785:27)
>     at c._load (node:electron/js2c/asar_bundle:5:13343)
>     at Module.require (node:internal/modules/cjs/loader:1012:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at g (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:101)
>     at c.load (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:87:1706)
>     at c.load (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:86:67583)
>     at E (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:10200)
>     at Object.errorback (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:10321)
>     at c.triggerErrorback (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:86:67947)
>     at C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:86:67653
>     at c.load (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:87:1723)
>     at c.load (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:86:67583)
>     at E (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:10200)
>     at y._loadModule (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:10330)
>     at y._resolve (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:89:452)
>     at y.defineModule (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:6042)
>     at y._relativeRequire (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:6728)
>     at g (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\main.js:88:9306)
>     at J.Ie (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:68837)
>     at new Promise (<anonymous>)
>     at pt.J (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:68815)
>     at pt.I (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:68405)
>     at C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:55087
>     at v.invokeFunction (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:37:360)
>     at pt.startup (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:55063)
>     at async Oe.a (C:\Users\hello\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:87:4031) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'C:\\Users\\hello\\AppData\\Local\\Programs\\Cursor\\resources\\app\\out\\main.js',
>     undefined
>   ],
>   phase: 'loading',
>   moduleId: 'windows-mutex',
>   neededBy: [ '===anonymous5===' ]
> }

thanks!

**Comment by truell20** [comment]
Did you try opening Cursor from the normal windows app bar or from the command line? Could you send a screen recording? Would help a ton for fixing this 🙏

**Comment by luppiterw** [comment]
I met a crash from normal windows app entry:
![image](https://user-images.githubusercontent.com/13158261/230503868-5dd777e2-dd7f-4b9d-9d5a-77cabcac5490.png)
Cursor cannot startup normally, and crash in flash across since version 0.2. (It is normal in version 0.1)

then, I try to start  it from command line, the same crash occurs :
` ~/AppData/Local/Programs/cursor
$ ./Cursor.exe

[main 2023-04-06T22:21:06.422Z] update#ctor - updates are disabled as there is no update URL
[main 2023-04-06T22:21:06.429Z] Error: Cannot find module 'windows-mutex'
Require stack:
- D:\Datas\AppData\Local\Programs\cursor\resources\app\out\main.js`

![950b952b835691b80db7b536d0cca0d](https://user-images.githubusercontent.com/13158261/230504580-7bfeecd5-9f0b-4969-a12b-20258d0484b5.png)

**Comment by vonwell** [comment]
WIN11  也闪退

**Comment by danperks** [comment]
@luppiterw You appear to be running Cursor in Mingw64, which will probably cause issues. Try running from either Command Prompt or Powershell and see if the issue still occurs.

**Comment by benherve** [comment]
same here, 

Windows PowerShell
Copyright (C) Microsoft Corporation. Tous droits réservés.

Installez la dernière version de PowerShell pour de nouvelles fonctionnalités et améliorations ! https://aka.ms/PSWindows

Le chargement des profils personnels et système a duré 3315 ms.
   ~  cd C:\Users\bherve\AppData\Local\Programs\Cursor                                                    10:48:06
   Cursor  .\Cursor.exe                                                                                   10:48:08

   Cursor  [main 2023-05-12T08:48:15.378Z] update#ctor - updates are disabled as there is no update URL   10:48:14
[main 2023-05-12T08:48:15.381Z] Error: Cannot find module 'windows-mutex'
Require stack:
- C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at r (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:101)
    at t.load (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:5:1706)
    at t.load (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:4:13356)
    at c (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:10200)
    at Object.errorback (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:10321)
    at t.triggerErrorback (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:4:13720)
    at C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:4:13426
    at t.load (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:5:1723)
    at t.load (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:4:13356)
    at c (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:10200)
    at n._loadModule (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:10330)
    at n._resolve (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:7:452)
    at n.defineModule (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:6042)
    at n._relativeRequire (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:6728)
    at r (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:9306)
    at J.Ie (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:68837)
    at new Promise (<anonymous>)
    at pt.J (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:68815)
    at pt.I (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:68405)
    at C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:55087
    at v.invokeFunction (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:37:360)
    at pt.startup (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:85:55063)
    at async Oe.a (C:\Users\bherve\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:87:4033) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\bherve\\AppData\\Local\\Programs\\Cursor\\resources\\app\\out\\main.js',
    undefined
  ],
  phase: 'loading',
  moduleId: 'windows-mutex',
  neededBy: [ '===anonymous5===' ]
}
[main 2023-05-12T08:48:17.631Z] Starting extension host with pid 30212 (fork() took 15 ms).

**Comment by websailor** [comment]
same here,
![图片](https://github.com/getcursor/cursor/assets/6450895/f5b632a6-6aeb-40bc-bc22-c58c69835cae)

**Comment by danperks** [comment]
Pretty sure this was an issue with a much older version, so I'll close this for now.
If anyone still has any issues, please create a new issue and we'll go from there :)
