### ISSUE TITLE
无法登录，无法login in，无法访问

### ISSUE THREAD

**Issue by hustzxf12** [getcursor/cursor#598]

**Comment by truell20** [comment]
Are you on a VPN or is the cursor.so or cursor.sh domain blocked for you by any chance?

**Comment by qubitpercy** [comment]
cannot log in again. version 0.2.10 works fine, however, after updating to the latest version, cannot log in again

**Comment by truell20** [comment]
Could you open the developer tools by clicking the "Help" menu and then "Toggle Developer Tools"?

Then, could you try taking a screenshot of the developer console?

**Comment by truell20** [comment]
What do you see when you navigate to https://api.cursor.sh/?

**Comment by qubitpercy** [comment]
this is the screenshot for the cannot log in problem

**Comment by qubitpercy** [comment]
> What do you see when you navigate to https://api.cursor.sh/?

Welcome to Cursor. From server d0cymeghvwharv8w7e1y8.

**Comment by qubitpercy** [comment]
I can logged in today, however, when I try to use cursor to ask question, it will reporting :Something unexpected happened...
Please check your internet connection and try again. If this persists,
please email admin@cursor.so

**Comment by qubitpercy** [comment]
> Could you open the developer tools by clicking the "Help" menu and then "Toggle Developer Tools"?
> 
> Then, could you try taking a screenshot of the developer console?

sorry, cannnot screenshot on the pc from company.

**Comment by qubitpercy** [comment]
could you please ban the update automatically? cause whenever I reinstall the old version, although I disable the updating function. it will finally update the software. Thank you

**Comment by SIN8023SIN** [comment]
When I tried to log in, I couldn't get the request in the console. Here's the error message
workbench.desktop.main.js:20402         
 GET https://api2.cursor.sh/auth/poll?uuid=7140e720-e22f-4cef-ad6d-7fab87d314ce&verifier=ayk9MhOWZTpcfI1UBfHMX5mEaq_HwEyGuVd0aPsDn3Q 404

**Comment by SIN8023SIN** [comment]
Why can't I visit the official website

**Comment by SIN8023SIN** [comment]
Failed to load resource: the server responded with a status of 404 ()       poll:1

**Comment by zhangzhuang15** [comment]
+1 @SIN8023SIN

**Comment by moyuchenxin** [comment]
Unable login too

**Comment by gabrieljbaker** [comment]
I'm also repeatedly getting this when I try to chat w/ my repo but I do seem to be logged in 
<img width="1013" alt="image" src="https://github.com/getcursor/cursor/assets/5530378/5fd5fae6-a8b8-4384-9dc8-311c9c4ff19f">

**Comment by itpPhange** [comment]
![image](https://github.com/getcursor/cursor/assets/26141107/9e52a64f-9524-48c9-8642-96c4e5e72d16)

**Comment by hemangjoshi37a** [comment]
same problem #1323
have you found any solution? if yes please let me know.

**Comment by VTANS** [comment]
Can not login from Windows 10 in Cursor., 
1. Do log in on the website like requested from inside Cursor
2. Should proceed back to Cursor:
"You may now proceed back to Cursor
If you have any trouble, please contact hi@cursor.sh".
3. Cursor still requests to log in on the website.
4. Click on the the button opens a new website window. 
5. Returned to step 1 and opened 10+ new windows, on every new one fresh logged in automatically.

I have chosen the free version of "Cursor Setup 0.31.3 - x64.exe".
Please help, copilot will not work until logged in,

**Comment by VTANS** [comment]
Uninstalled, Marketplace also requires login. Will try it out when you fix this bug.

**Comment by denodaeus** [comment]
Can you guys consider not using .sh as your domain name for auth?  It really puts a hamper on many forward proxy setups out there.  .sh is not a widely recognized TLD and will be blocked by default for the vast majority of enterprise use cases out there

**Comment by vardhamani** [comment]
If the problem persists, please check your internet connection or VPN, or email us at hi@cursor.sh.

**Comment by hemangjoshi37a** [comment]
the problem is not abviously with my internet or vpn as i dont even use any vpn and i an using my internet all the time so definately my internet works just fine . i do not wish to communicate through email instead here as the email conversation will not solve the problem for all the users that are having similar oroblem but only for me which i dont want.

**Comment by daryl-z** [comment]
I'm unable to log in due to firewall software such as lulu.app. For your reference.

**Comment by Kalyan1123** [comment]
> I'm also repeatedly getting this when I try to chat w/ my repo but I do seem to be logged in <img alt="image" width="1013" src="https://private-user-images.githubusercontent.com/5530378/256948535-5fd5fae6-a8b8-4384-9dc8-311c9c4ff19f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjUzMDksIm5iZiI6MTcyNzM2NTAwOSwicGF0aCI6Ii81NTMwMzc4LzI1Njk0ODUzNS01ZmQ1ZmFlNi1hOGI4LTQzODQtOWRjOC0zMTFjOWM0ZmYxOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMTUzNjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTlmNjNkNTI5YTVmNWJjOWM2YTk2OWE1NTEzZmZmZTA3NTgyZmM0NDUzODdkZDg4ZjQ0NzgzYzE0NThjMjRiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4rBBFXYRw2O05bhBN4Ec63OTAKuFBDnKhktc35EIzxQ">

Bro, Did you solve the problem?. If so please let me know . I'm also facing the same the issue.

**Comment by zhangzhuang15** [comment]
你好 ，您发给我的邮件我已经收到。

**Comment by hemangjoshi37a** [comment]
@Kalyan1123 not yet. still this issue persists after so many version updates .

**Comment by hemangjoshi37a** [comment]
@Kalyan1123 But right now i am using aider with claude sonet. it works really well. it does not have such great ui similar to cursor but it works fine

**Comment by geraugu** [comment]
me too, same error

**Comment by danperks** [comment]
> I have the same issue with latest version of Cursor. Clicking on "Sign in" does nothing. Console shows errors (floods the screen) like:
> 
> ```
> workbench.desktop.main.js:2349 GET https://api2.cursor.sh/auth/poll?uuid=<uuid>&verifier=<verifier> 404 (Not Found)
> ```
> 
> > What do you see when you navigate to https://api.cursor.sh/?
> 
> I see "ERR_NAME_NOT_RESOLVED".

The authentication endpoint is now at "https://api2.cursor.sh".

For anyone still facing this issue, can you let me know if you can visit that page?
You should see something like "Welcome to Cursor. From server xxxx..." if your network/VPN isn't blocking requests.

**Comment by danperks** [comment]
Just to confirm, what's the error in the console now? If you can access that endpoint, that mostly rules out firewall and VPN issues, which are the most comment cause for Cursor issues

**Comment by Devligue** [comment]
I have the same issue - log in button doesn't work.

In developer console I see spam to api2.cursor.sh, all failing with 404:

```
workbench.desktop.main.js:2589 
 GET https://api2.cursor.sh/auth/poll?uuid=83bd9719-ac72-4257-b4d0-98f8814fb735&verifier=jN75jhxgvKpOYtbVKGpivuw48ppKmmY4P4hFs6a29ho 404 (Not Found)
 ```
 
 I can access https://api2.cursor.sh/ from browser just fine. I'm not using VPN and firewall is disabled.

**Comment by zdaar** [comment]
Same error, ubuntu 23.04

**Comment by chenlijia0502** [comment]
是否解决，我也遇见相同的问题，Windoes系统最新版本cursor。点击登录无法跳转，登录按钮不起作用。

**Comment by f12defilippis** [comment]
> log in button doesn't work.
> 
> In developer console I see spam to api2.cursor.sh, all failing with 404:

I have the same situation...

**Comment by shphonetown** [comment]
https://api2.cursor.sh/ 返回Welcome to Cursor. From server h4p7oeitmdisjwz1fwaugg with time 0.003244000021368265.
			Pod name: undefined.
			DD_VERSION: 0.305.936-main-e1eceb7e811c203ccdf698e9a87a547c3f01a215.
https://api2.cursor.sh/auth/poll?uuid=053127a8-8925-471e-af8b-7edd067f1c19&verifier=KIfk0F4efx1xL7ZVuqZpwH5XNyOqtoVO_GvLAVd_PMY 返回Not found

**Comment by wuxian08** [comment]
When clicking "Sign in", my chrome opens up a new tab which asks me to sign in. And after I have signed in on the web, nothing happens on the cursor desktop, which still tells me to sign in. The "window"  output of the cursor shows unauthenticated error
`2024-11-19 17:53:11.823 [error] [unauthenticated] Error: ConnectError: [unauthenticated] Error
    at Object.F [as unary] (vscode-file://vscode-app/c:/Users/infin/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:3822:11898)
    at async Object.availableModels (vscode-file://vscode-app/c:/Users/infin/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:266:139432)
    at async et.keepCppModelStateUpdated (vscode-file://vscode-app/c:/Users/infin/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:4347:13642)
    at async et.loadCppConfigIncludingHandlingProAccess (vscode-file://vscode-app/c:/Users/infin/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:4363:1075)
2024-11-19 17:53:12.867 [error] [unauthenticated] Error`

**Comment by wuxian08** [comment]
> When clicking "Sign in", my chrome opens up a new tab which asks me to sign in. And after I have signed in on the web, nothing happens on the cursor desktop, which still tells me to sign in. The "window" output of the cursor shows unauthenticated error `2024-11-19 17:53:11.823 [error] [unauthenticated] Error: ConnectError: [unauthenticated] Error at Object.F [as unary] (vscode-file://vscode-app/c:/Users/infin/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:3822:11898) at async Object.availableModels (vscode-file://vscode-app/c:/Users/infin/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:266:139432) at async et.keepCppModelStateUpdated (vscode-file://vscode-app/c:/Users/infin/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:4347:13642) at async et.loadCppConfigIncludingHandlingProAccess (vscode-file://vscode-app/c:/Users/infin/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:4363:1075) 2024-11-19 17:53:12.867 [error] [unauthenticated] Error`


After "Toggle Developer Tools", I realized that it was because my vpn on the computer was not enabled, in which case the cursor desktop failed to retrieve the login response message. (I was able to login on the cursor web since I opened up my vpn for the browser only...)

**Comment by PranavMasekar** [comment]
Please fix this asap not able to use cursor even though I have premium

**Comment by Alien-Y** [comment]
I found a way that it worked for me, go incognito and sign up as usual, it will work with no issues, save the credentials and go back to the non-incognito window, sign in with same credentials, open Cursor desktop and click sign in, it will take you the browser, choose Log me in and Apra Kadapra.

**Comment by mYcc-one** [comment]
![image](https://github.com/user-attachments/assets/7172b187-516a-4731-8c87-b4ff8639a1da)
set like this ,it works

**Comment by mYcc-one** [comment]
![image](https://github.com/user-attachments/assets/ebb19a2e-10d9-427f-9c50-726c8fb95174)
set like this, it works

**Comment by STOSKR** [comment]
> No description provided.
I resolved the error by changing the default browser:

1. Cofig.
2. Application

![Image](https://github.com/user-attachments/assets/99311649-9cfd-4fe9-b8c4-963199dea7d8)

3. Predeterminated applications

![Image](https://github.com/user-attachments/assets/085231b5-84a2-437b-86bf-b3c0af3171ee)

4. Change or choose a default browser

![Image](https://github.com/user-attachments/assets/49ed36a5-bc61-4f92-9641-18672966ebe6)

**Comment by houming818** [comment]
+1

**Comment by LSQii** [comment]
+1

**Comment by Jerrygan** [comment]
+1

**Comment by arriverist** [comment]
When I click on the **Sign in** button nothing happens

**Comment by RydalWater** [comment]
+1 Ubuntu 24.04.2 LTS

**Comment by macias** [comment]
Same here. openSUSE 15.3. I execute Cursor, there is "Sign in" link in the center, I hover over, it is underlined, I click on it, nothing happens. Since it is executed from the terminal, I switch to it, no messages.

Just to check, I switched default browser from Firefox to Chromium, I checked in other program it is triggered correctly, yes, again, I clicked on "Sign in" -- nothing.

**Comment by rodger025** [comment]
I also encountered this problem today, is there any solution now?

**Comment by yimity** [comment]
Rebooting your device is one solution.

**Comment by macias** [comment]
After rebooting it does not work the same way it didn't work before. No reaction, no message, no feedback, nothing.
