### ISSUE TITLE
I can't ssh to the remote server on the 0.6.0 version cursor

### ISSUE THREAD

**Issue by Lyapunova-cd** [getcursor/cursor#712]
I cannot ssh to a new ip when I updated cursor to 0.6.0 version from an old version about 0.3.0. 

The log tell me it failed to download vscodium server package, but I can still ssh to the ip from vscode and then manually download the package from "https://cursor.blob.core.windows.net/remote-releases/0.6.0-1.0.0/vscode-reh-linux-x64.tar.gz" and then rename it to "4bc2ab0a56df141f4b33c57498dcf59af5cc5c82"

It is disappointing that the manual vscodium package didn't work.

Please help locate the issue, thx.

1) If you can, please include a screenshot of your problem
`[Info  - 02:01:11.116] Resolving ssh remote authority 'ssh-remote+192.168.3.190(\x49ntel_\x47en4)' (attemp #1)
[Error  - 02:01:11.195] Couldn't get identities from OpenSSH agent
Error: Failed to connect to agent
	at Socket.n (c:\Users\xxx\AppData\Local\Programs\Cursor\resources\app\extensions\open-remote-ssh\dist\main.js:1:112720)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[Trace  - 02:01:11.195] Identity keys:
C:\Users\xxx/.ssh/id_rsa ssh-rsa SHA256:g+h+csYFxc8vbG1lSXFXdAuC++hf4T4oLnHEJoVD7xI=
[Info  - 02:01:11.386] Trying no-auth authentication
[Info  - 02:01:11.420] Trying publickey authentication: C:\Users\xxx/.ssh/id_rsa ssh-rsa SHA256:g+h+csYFxc8vbG1lSXFXdAuC++hf4T4oLnHEJoVD7xI=
[Trace  - 02:01:12.231] Server install command:

# Server installation script

TMP_DIR="${XDG_RUNTIME_DIR:-"/tmp"}"

DISTRO_VERSION="0.6.0"
DISTRO_COMMIT="4bc2ab0a56df141f4b33c57498dcf59af5cc5c82"
DISTRO_QUALITY="stable"
DISTRO_VSCODIUM_RELEASE="1.0.0"

SERVER_APP_NAME="codium-server"
SERVER_INITIAL_EXTENSIONS=""
SERVER_LISTEN_FLAG="--port=0"
SERVER_DATA_DIR="$HOME/.cursor-server"
SERVER_DIR="$SERVER_DATA_DIR/bin/$DISTRO_COMMIT-$DISTRO_QUALITY"
SERVER_SCRIPT="$SERVER_DIR/bin/$SERVER_APP_NAME"
SERVER_LOGFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.log"
SERVER_PIDFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.pid"
SERVER_TOKENFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.token"
SERVER_OS=
SERVER_ARCH=
SERVER_CONNECTION_TOKEN=
SERVER_DOWNLOAD_URL=

LISTENING_ON=
OS_RELEASE_ID=
ARCH=
PLATFORM=

# Mimic output from logs of remote-ssh extension
print_install_results_and_exit() {
    echo "716ff01979f3481c114f0a20: start"
    echo "exitCode==$1=="
    echo "listeningOn==$LISTENING_ON=="
    echo "connectionToken==$SERVER_CONNECTION_TOKEN=="
    echo "logFile==$SERVER_LOGFILE=="
    echo "osReleaseId==$OS_RELEASE_ID=="
    echo "arch==$ARCH=="
    echo "platform==$PLATFORM=="
    echo "tmpDir==$TMP_DIR=="
    
    echo "716ff01979f3481c114f0a20: end"
    exit 0
}

# Check if platform is supported
PLATFORM="$(uname -s)"
case $PLATFORM in
    Darwin)
        SERVER_OS="darwin"
        ;;
    Linux)
        SERVER_OS="linux"
        ;;
    FreeBSD)
        SERVER_OS="freebsd"
        ;;
    DragonFly)
        SERVER_OS="dragonfly"
        ;;
    *)
        echo "Error platform not supported: $PLATFORM"
        print_install_results_and_exit 1
        ;;
esac

# Check machine architecture
ARCH="$(uname -m)"
case $ARCH in
    x86_64 | amd64)
        SERVER_ARCH="x64"
        ;;
    armv7l | armv8l)
        SERVER_ARCH="armhf"
        ;;
    arm64 | aarch64)
        SERVER_ARCH="arm64"
        ;;
    ppc64le)
        SERVER_ARCH="ppc64le"
        ;;
    *)
        echo "Error architecture not supported: $ARCH"
        print_install_results_and_exit 1
        ;;
esac

# https://www.freedesktop.org/software/systemd/man/os-release.html
OS_RELEASE_ID="$(grep -i '^ID=' /etc/os-release 2>/dev/null | sed 's/^ID=//gi' | sed 's/"//g')"
if [[ -z $OS_RELEASE_ID ]]; then
    OS_RELEASE_ID="$(grep -i '^ID=' /usr/lib/os-release 2>/dev/null | sed 's/^ID=//gi' | sed 's/"//g')"
    if [[ -z $OS_RELEASE_ID ]]; then
        OS_RELEASE_ID="unknown"
    fi
fi

# Create installation folder
if [[ ! -d $SERVER_DIR ]]; then
    mkdir -p $SERVER_DIR
    if (( $? > 0 )); then
        echo "Error creating server install directory"
        print_install_results_and_exit 1
    fi
fi

SERVER_DOWNLOAD_URL="$(echo "https://cursor.blob.core.windows.net/remote-releases/\${version}-\${release}/vscode-reh-\${os}-\${arch}.tar.gz" | sed "s/\${quality}/$DISTRO_QUALITY/g" | sed "s/\${version}/$DISTRO_VERSION/g" | sed "s/\${commit}/$DISTRO_COMMIT/g" | sed "s/\${os}/$SERVER_OS/g" | sed "s/\${arch}/$SERVER_ARCH/g" | sed "s/\${release}/$DISTRO_VSCODIUM_RELEASE/g")"

echo "Downloading server from '$SERVER_DOWNLOAD_URL'"

# Check if server script is already installed
if [[ ! -f $SERVER_SCRIPT ]]; then
    if [[ "$SERVER_OS" = "dragonfly" ]] || [[ "$SERVER_OS" = "freebsd" ]]; then
        echo "Error "$SERVER_OS" needs manual installation of remote extension host"
        print_install_results_and_exit 1
    fi

    pushd $SERVER_DIR > /dev/null

    if [[ ! -z $(which wget) ]]; then
        wget --tries=3 --timeout=10 --continue --no-verbose -O vscode-server.tar.gz $SERVER_DOWNLOAD_URL
    elif [[ ! -z $(which curl) ]]; then
        curl --retry 3 --connect-timeout 10 --location --show-error --silent --output vscode-server.tar.gz $SERVER_DOWNLOAD_URL
    else
        echo "Error no tool to download server binary"
        print_install_results_and_exit 1
    fi

    if (( $? > 0 )); then
        echo "Error downloading server from $SERVER_DOWNLOAD_URL"
        print_install_results_and_exit 1
    fi

    tar -xf vscode-server.tar.gz --strip-components 1
    if (( $? > 0 )); then
        echo "Error while extracting server contents"
        print_install_results_and_exit 1
    fi

    if [[ ! -f $SERVER_SCRIPT ]]; then
        echo "Error server contents are corrupted"
        print_install_results_and_exit 1
    fi

    rm -f vscode-server.tar.gz

    popd > /dev/null
else
    echo "Server script already installed in $SERVER_SCRIPT"
fi

# Try to find if server is already running
if [[ -f $SERVER_PIDFILE ]]; then
    SERVER_PID="$(cat $SERVER_PIDFILE)"
    echo "Server PID: $SERVER_PID"
    echo "Server script: $SERVER_SCRIPT"
    SERVER_RUNNING_PROCESS="$(ps -o pid,args -p $SERVER_PID | grep $SERVER_SCRIPT)"
else
    echo "Server script: $SERVER_SCRIPT"
    SERVER_RUNNING_PROCESS="$(ps -o pid,args -A | grep $SERVER_SCRIPT | grep -v grep)"
fi

echo "Server running process: $SERVER_RUNNING_PROCESS"

if [[ -z $SERVER_RUNNING_PROCESS ]]; then
    if [[ -f $SERVER_LOGFILE ]]; then
        rm $SERVER_LOGFILE
    fi
    if [[ -f $SERVER_TOKENFILE ]]; then
        rm $SERVER_TOKENFILE
    fi

    touch $SERVER_TOKENFILE
    chmod 600 $SERVER_TOKENFILE
    SERVER_CONNECTION_TOKEN="2463d048-511a-4f8f-a5c7-12e04ff8b259"
    echo $SERVER_CONNECTION_TOKEN > $SERVER_TOKENFILE

    $SERVER_SCRIPT --start-server --host=127.0.0.1 $SERVER_LISTEN_FLAG $SERVER_INITIAL_EXTENSIONS --connection-token-file $SERVER_TOKENFILE --telemetry-level off --enable-remote-auto-shutdown --accept-server-license-terms &> $SERVER_LOGFILE &
    echo $! > $SERVER_PIDFILE
else
    echo "Server script is already running $SERVER_SCRIPT"
fi

if [[ -f $SERVER_TOKENFILE ]]; then
    SERVER_CONNECTION_TOKEN="$(cat $SERVER_TOKENFILE)"
else
    echo "Error server token file not found $SERVER_TOKENFILE"
    print_install_results_and_exit 1
fi

if [[ -f $SERVER_PIDFILE ]]; then
    SERVER_PID="$(cat $SERVER_PIDFILE)"
    SERVER_RUNNING_PROCESS="$(ps -o pid,args -p $SERVER_PID | grep $SERVER_SCRIPT)"
else
    SERVER_RUNNING_PROCESS="$(ps -o pid,args -A | grep $SERVER_SCRIPT | grep -v grep)"
fi
if [[ -f $SERVER_LOGFILE ]]; then
    for i in {1..5}; do
        LISTENING_ON="$(cat $SERVER_LOGFILE | grep -E 'Extension host agent listening on .+' | sed 's/Extension host agent listening on //')"
        if [[ -n $LISTENING_ON ]]; then
            break
        fi
        sleep 0.5
    done

    if [[ -z $LISTENING_ON ]]; then
        echo "Error server did not start sucessfully"
        print_install_results_and_exit 1
    fi
else
    echo "Error server log file not found $SERVER_LOGFILE"
    print_install_results_and_exit 1
fi

# Finish server setup
print_install_results_and_exit 0

[Trace  - 02:01:14.191] Server install command stderr:
WARNING: cannot verify cursor.blob.core.windows.net's certificate, issued by ‘CN=Microsoft Azure TLS Issuing CA 02,O=Microsoft Corporation,C=US’:
  Unable to locally verify the issuer's authority.

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

[Trace  - 02:01:14.191] Server install command stdout:
Downloading server from 'https://cursor.blob.core.windows.net/remote-releases/0.6.0-1.0.0/vscode-reh-linux-x64.tar.gz'
Error while extracting server contents
716ff01979f3481c114f0a20: start
exitCode==1==
listeningOn====
connectionToken====
logFile==/home/xxx/.cursor-server/.4bc2ab0a56df141f4b33c57498dcf59af5cc5c82.log==
osReleaseId==ubuntu==
arch==x86_64==
platform==Linux==
tmpDir==/run/user/1001==
716ff01979f3481c114f0a20: end

[Error  - 02:01:14.192] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (c:\Users\xxxx\AppData\Local\Programs\Cursor\resources\app\extensions\open-remote-ssh\dist\main.js:1:464158)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\xxx\AppData\Local\Programs\Cursor\resources\app\extensions\open-remote-ssh\dist\main.js:1:435141`
2) Please include the name of your operating system
Local: Windows 11
Remote: Linux Ubuntu 20.04
3) If you can, steps to reproduce are super helpful

**Comment by dongmingli-Ben** [comment]
Same problem here. My remote machine is Ubuntu 20.04 and my local machine is Windows 11. I am using the remote SSH extension. Here is the error message in the log:

```
[15:00:19.337] > Acquiring lock on /home/toymaker/.cursor-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/vscode-remote-lock.toymaker.74f6148eb9ea00507ec113ec51c489d6ffb4b771
> Installing to /home/toymaker/.cursor-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771...
[15:00:19.345] > 8fe7ac0ddaa3%%1%%
> Downloading with wget
[15:00:33.494] > Download complete
> 8fe7ac0ddaa3%%2%%
> tar --version:
> tar (GNU tar) 1.30
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.Written by John Gilmore and Jay Fenlason.
> 
[15:00:34.803] > mv: cannot move 'vscode-server-linux-x64/bin' to './bin': Directory not empty
> mv: cannot move 'vscode-server-linux-x64/extensions' to './extensions': Directory not empty
[15:00:34.827] > mv: cannot move 'vscode-server-linux-x64/node_modules' to './node_modules': Directory not empty
> mv: cannot move 'vscode-server-linux-x64/out' to './out': Directory not empty
> ERROR: /home/toymaker/.cursor-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/node or /home/toymaker/.cursor-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/bin/codium-server don't exist
> Trigger local server download
```

I have tried the built-in SSH in the newest cursor but no luck either.

**Comment by Sanger2000** [comment]
> 

For this issue, there are a few reasons that it may not be working. It looks like the core issue is the download resulted in a corrupted .tar.gz version being installed:

The immediate reasons this may be happening are:
1. There may not be enough space on your device
2. The download was corrupted for some reason.

What happens if you try removing the full directory `/home/xxx/.cursor-server/`, then restarting the builtin remote ssh?

**Comment by Sanger2000** [comment]
> Same problem here. My remote machine is Ubuntu 20.04 and my local machine is Windows 11. I am using the remote SSH extension. Here is the error message in the log:
> 
> ```
> [15:00:19.337] > Acquiring lock on /home/toymaker/.cursor-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/vscode-remote-lock.toymaker.74f6148eb9ea00507ec113ec51c489d6ffb4b771
> > Installing to /home/toymaker/.cursor-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771...
> [15:00:19.345] > 8fe7ac0ddaa3%%1%%
> > Downloading with wget
> [15:00:33.494] > Download complete
> > 8fe7ac0ddaa3%%2%%
> > tar --version:
> > tar (GNU tar) 1.30
> > Copyright (C) 2017 Free Software Foundation, Inc.
> > License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> > This is free software: you are free to change and redistribute it.
> > There is NO WARRANTY, to the extent permitted by law.Written by John Gilmore and Jay Fenlason.
> > 
> [15:00:34.803] > mv: cannot move 'vscode-server-linux-x64/bin' to './bin': Directory not empty
> > mv: cannot move 'vscode-server-linux-x64/extensions' to './extensions': Directory not empty
> [15:00:34.827] > mv: cannot move 'vscode-server-linux-x64/node_modules' to './node_modules': Directory not empty
> > mv: cannot move 'vscode-server-linux-x64/out' to './out': Directory not empty
> > ERROR: /home/toymaker/.cursor-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/node or /home/toymaker/.cursor-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/bin/codium-server don't exist
> > Trigger local server download
> ```
> 
> I have tried the built-in SSH in the newest cursor but no luck either.

This may be a separate problem, but the same solution of removing `/home/toymaker/.cursor-server` then re-using the original cursor builtin remote ssh should work. 

Make sure not to use any external remote ssh extensions, as they won't work with Cursor's features!

**Comment by Lyapunova-cd** [comment]
> > 
> 
> For this issue, there are a few reasons that it may not be working. It looks like the core issue is the download resulted in a corrupted .tar.gz version being installed:
> 
> The immediate reasons this may be happening are:
> 
>     1. There may not be enough space on your device
> 
>     2. The download was corrupted for some reason.
> 
> 
> What happens if you try removing the full directory `/home/xxx/.cursor-server/`, then restarting the builtin remote ssh?

Thanks! I succeed to ssh to the remote after removing the cursor-server directory. I was unconscious that .vscodium-server been renamed to .cursor-server when uptating cursor to the newest.

**Comment by samtvlabs** [comment]
I get this error after I upgrade. Deleted but the `.cusor-server` and `vscodium-server` directories and it doesnt help.

**Comment by Mrtao233** [comment]
Maybe the truth is because the many Chinese user usually get free use of it, the authority close this Chinese service.
