### ISSUE TITLE
Remote SSH connection not working -- Error resolving authority Error: Illegal argument: connectionToken

### ISSUE THREAD

**Issue by kirill-vishniakov** [getcursor/cursor#776]
Hi,

I was trying to connect to the remote server, but consistently getting the following error: `Error resolving authority
Error: Illegal argument: connectionToken`

This is the full log:

`[Info  - 11:55:07.225] Resolving ssh remote authority 'ssh-remote+kirill.vishniakov@placeholder' (attemp #1)
[Error  - 11:55:07.256] Couldn't get identities from OpenSSH agent
Error: Failed to connect to agent
	at Socket.n (c:\Users\Kirill\AppData\Local\Programs\cursor\resources\app\extensions\open-remote-ssh\dist\main.js:1:112720)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[Trace  - 11:55:07.256] Identity keys:
C:\Users\Kirill\.ssh\id_rsa ssh-rsa placeholder
[Info  - 11:55:07.350] Trying no-auth authentication
[Info  - 11:55:13.318] Trying publickey authentication: C:\Users\Kirill\.ssh\id_rsa ssh-rsa placeholder
[Trace  - 11:55:15.35] Server install command:

# Server installation script

TMP_DIR="${XDG_RUNTIME_DIR:-"/tmp"}"

DISTRO_VERSION="0.8.1"
DISTRO_COMMIT="4cd130570efc4042afde40b375a5734f708e91b7"
DISTRO_QUALITY="stable"
DISTRO_VSCODIUM_RELEASE="1.0.0"

SERVER_APP_NAME="codium-server"
SERVER_INITIAL_EXTENSIONS=""
SERVER_LISTEN_FLAG="--port=0"
SERVER_DATA_DIR="$HOME/.cursor-server"
SERVER_DIR="$SERVER_DATA_DIR/bin/$DISTRO_COMMIT-$DISTRO_QUALITY"
SERVER_SCRIPT="$SERVER_DIR/bin/$SERVER_APP_NAME"
SERVER_LOGFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.log"
SERVER_PIDFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.pid"
SERVER_TOKENFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.token"
SERVER_OS=
SERVER_ARCH=
SERVER_CONNECTION_TOKEN=
SERVER_DOWNLOAD_URL=

LISTENING_ON=
OS_RELEASE_ID=
ARCH=
PLATFORM=

# Mimic output from logs of remote-ssh extension
print_install_results_and_exit() {
    echo "54b48c8087edbc9bdff9b787: start"
    echo "exitCode==$1=="
    echo "listeningOn==$LISTENING_ON=="
    echo "connectionToken==$SERVER_CONNECTION_TOKEN=="
    echo "logFile==$SERVER_LOGFILE=="
    echo "osReleaseId==$OS_RELEASE_ID=="
    echo "arch==$ARCH=="
    echo "platform==$PLATFORM=="
    echo "tmpDir==$TMP_DIR=="
    
    echo "54b48c8087edbc9bdff9b787: end"
    exit 0
}

# Check if platform is supported
PLATFORM="$(uname -s)"
case $PLATFORM in
    Darwin)
        SERVER_OS="darwin"
        ;;
    Linux)
        SERVER_OS="linux"
        ;;
    FreeBSD)
        SERVER_OS="freebsd"
        ;;
    DragonFly)
        SERVER_OS="dragonfly"
        ;;
    *)
        echo "Error platform not supported: $PLATFORM"
        print_install_results_and_exit 1
        ;;
esac

# Check machine architecture
ARCH="$(uname -m)"
case $ARCH in
    x86_64 | amd64)
        SERVER_ARCH="x64"
        ;;
    armv7l | armv8l)
        SERVER_ARCH="armhf"
        ;;
    arm64 | aarch64)
        SERVER_ARCH="arm64"
        ;;
    ppc64le)
        SERVER_ARCH="ppc64le"
        ;;
    *)
        echo "Error architecture not supported: $ARCH"
        print_install_results_and_exit 1
        ;;
esac

# https://www.freedesktop.org/software/systemd/man/os-release.html
OS_RELEASE_ID="$(grep -i '^ID=' /etc/os-release 2>/dev/null | sed 's/^ID=//gi' | sed 's/"//g')"
if [[ -z $OS_RELEASE_ID ]]; then
    OS_RELEASE_ID="$(grep -i '^ID=' /usr/lib/os-release 2>/dev/null | sed 's/^ID=//gi' | sed 's/"//g')"
    if [[ -z $OS_RELEASE_ID ]]; then
        OS_RELEASE_ID="unknown"
    fi
fi

# Create installation folder
if [[ ! -d $SERVER_DIR ]]; then
    mkdir -p $SERVER_DIR
    if (( $? > 0 )); then
        echo "Error creating server install directory"
        print_install_results_and_exit 1
    fi
fi

SERVER_DOWNLOAD_URL="$(echo "https://cursor.blob.core.windows.net/remote-releases/\${version}-\${release}/vscode-reh-\${os}-\${arch}.tar.gz" | sed "s/\${quality}/$DISTRO_QUALITY/g" | sed "s/\${version}/$DISTRO_VERSION/g" | sed "s/\${commit}/$DISTRO_COMMIT/g" | sed "s/\${os}/$SERVER_OS/g" | sed "s/\${arch}/$SERVER_ARCH/g" | sed "s/\${release}/$DISTRO_VSCODIUM_RELEASE/g")"

echo "Downloading server from '$SERVER_DOWNLOAD_URL'"

# Check if server script is already installed
if [[ ! -f $SERVER_SCRIPT ]]; then
    if [[ "$SERVER_OS" = "dragonfly" ]] || [[ "$SERVER_OS" = "freebsd" ]]; then
        echo "Error "$SERVER_OS" needs manual installation of remote extension host"
        print_install_results_and_exit 1
    fi

    pushd $SERVER_DIR > /dev/null

    if [[ ! -z $(which wget) ]]; then
        wget --tries=3 --timeout=10 --continue --no-verbose -O vscode-server.tar.gz $SERVER_DOWNLOAD_URL
    elif [[ ! -z $(which curl) ]]; then
        curl --retry 3 --connect-timeout 10 --location --show-error --silent --output vscode-server.tar.gz $SERVER_DOWNLOAD_URL
    else
        echo "Error no tool to download server binary"
        print_install_results_and_exit 1
    fi

    if (( $? > 0 )); then
        echo "Error downloading server from $SERVER_DOWNLOAD_URL"
        print_install_results_and_exit 1
    fi

    tar -xf vscode-server.tar.gz --strip-components 1
    if (( $? > 0 )); then
        echo "Error while extracting server contents"
        print_install_results_and_exit 1
    fi

    if [[ ! -f $SERVER_SCRIPT ]]; then
        echo "Error server contents are corrupted"
        print_install_results_and_exit 1
    fi

    rm -f vscode-server.tar.gz

    popd > /dev/null
else
    echo "Server script already installed in $SERVER_SCRIPT"
fi

# Try to find if server is already running
if [[ -f $SERVER_PIDFILE ]]; then
    SERVER_PID="$(cat $SERVER_PIDFILE)"
    echo "Server PID: $SERVER_PID"
    echo "Server script: $SERVER_SCRIPT"
    SERVER_RUNNING_PROCESS="$(ps -o pid,args -p $SERVER_PID | grep $SERVER_SCRIPT)"
else
    echo "Server script: $SERVER_SCRIPT"
    SERVER_RUNNING_PROCESS="$(ps -o pid,args -A | grep $SERVER_SCRIPT | grep -v grep)"
fi

echo "Server running process: $SERVER_RUNNING_PROCESS"

if [[ -z $SERVER_RUNNING_PROCESS ]]; then
    if [[ -f $SERVER_LOGFILE ]]; then
        rm $SERVER_LOGFILE
    fi
    if [[ -f $SERVER_TOKENFILE ]]; then
        rm $SERVER_TOKENFILE
    fi

    touch $SERVER_TOKENFILE
    chmod 600 $SERVER_TOKENFILE
    SERVER_CONNECTION_TOKEN="0b9125fe-6d6b-4cae-ae0f-50a6e5712c28"
    echo $SERVER_CONNECTION_TOKEN > $SERVER_TOKENFILE

    $SERVER_SCRIPT --start-server --host=127.0.0.1 $SERVER_LISTEN_FLAG $SERVER_INITIAL_EXTENSIONS --connection-token-file $SERVER_TOKENFILE --telemetry-level off --enable-remote-auto-shutdown --accept-server-license-terms &> $SERVER_LOGFILE &
    echo $! > $SERVER_PIDFILE
else
    echo "Server script is already running $SERVER_SCRIPT"
fi

if [[ -f $SERVER_TOKENFILE ]]; then
    SERVER_CONNECTION_TOKEN="$(cat $SERVER_TOKENFILE)"
else
    echo "Error server token file not found $SERVER_TOKENFILE"
    print_install_results_and_exit 1
fi

if [[ -f $SERVER_PIDFILE ]]; then
    SERVER_PID="$(cat $SERVER_PIDFILE)"
    SERVER_RUNNING_PROCESS="$(ps -o pid,args -p $SERVER_PID | grep $SERVER_SCRIPT)"
else
    SERVER_RUNNING_PROCESS="$(ps -o pid,args -A | grep $SERVER_SCRIPT | grep -v grep)"
fi
if [[ -f $SERVER_LOGFILE ]]; then
    for i in {1..5}; do
        LISTENING_ON="$(cat $SERVER_LOGFILE | grep -E 'Extension host agent listening on .+' | sed 's/Extension host agent listening on //')"
        if [[ -n $LISTENING_ON ]]; then
            break
        fi
        sleep 0.5
    done

    if [[ -z $LISTENING_ON ]]; then
        echo "Error server did not start sucessfully"
        print_install_results_and_exit 1
    fi
else
    echo "Error server log file not found $SERVER_LOGFILE"
    print_install_results_and_exit 1
fi

# Finish server setup
print_install_results_and_exit 0

[Trace  - 11:55:49.308] Server install command stderr:
2023-08-23 15:55:46 URL:https://cursor.blob.core.windows.net/remote-releases/0.8.1-1.0.0/vscode-reh-linux-x64.tar.gz [52678611/52678611] -> "vscode-server.tar.gz" [1]
bash: line 174: /home/kirill.vishniakov/.cursor-server/.4cd130570efc4042afde40b375a5734f708e91b7.token: cannot overwrite existing file
bash: line 177: /home/kirill.vishniakov/.cursor-server/.4cd130570efc4042afde40b375a5734f708e91b7.pid: cannot overwrite existing file

[Trace  - 11:55:49.308] Server install command stdout:
Downloading server from 'https://cursor.blob.core.windows.net/remote-releases/0.8.1-1.0.0/vscode-reh-linux-x64.tar.gz'
Server PID: 2001816
Server script: /home/kirill.vishniakov/.cursor-server/bin/4cd130570efc4042afde40b375a5734f708e91b7-stable/bin/codium-server
Server running process: 
54b48c8087edbc9bdff9b787: start
exitCode==0==
listeningOn==36827==
connectionToken====
logFile==/home/kirill.vishniakov/.cursor-server/.4cd130570efc4042afde40b375a5734f708e91b7.log==
osReleaseId==ubuntu==
arch==x86_64==
platform==Linux==
tmpDir==/run/user/2215==
54b48c8087edbc9bdff9b787: end

[Trace  - 11:55:49.317] Creating forwarding server 63211(local) => 63210(socks) => 36827(remote)
[Error  - 11:55:49.319] Error resolving authority
Error: Illegal argument: connectionToken
	at g (c:\Users\Kirill\AppData\Local\Programs\cursor\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:1267)
	at Se (c:\Users\Kirill\AppData\Local\Programs\cursor\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:16884)
	at new Ie (c:\Users\Kirill\AppData\Local\Programs\cursor\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:17283)
	at c:\Users\Kirill\AppData\Local\Programs\cursor\resources\app\extensions\open-remote-ssh\dist\main.js:1:435843
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
`

Do you have any suggestion on how to resolve this?

**Comment by kirill-vishniakov** [comment]
@truell20 @arvid220u A gentle ping. I still have this issue on 0.9.3.
