### ISSUE TITLE
Can't install cpptools extension when connected to WSL

### ISSUE THREAD

**Issue by dylan-baros** [getcursor/cursor#784]
System: Windows 10
WSL: Ubuntu 20.04
Cursor:
![image](https://github.com/getcursor/cursor/assets/74726798/c490bd6e-d764-44a0-a3d5-784bf15614d7)

Installed fine on the host, once I connected to WSL and attempted to install in the container I got the following error:

Log file:
```
2023-08-23 20:12:17.400 [trace] pickRunningLocation for ms-vscode.cpptools, extension kinds: [workspace], isInstalledLocally: true, isInstalledRemotely: false, preference: None => None
2023-08-23 20:12:17.404 [trace] pickRunningLocation for ms-vscode.cpptools, extension kinds: [workspace], isInstalledLocally: true, isInstalledRemotely: false, preference: None => None
2023-08-23 20:12:17.430 [error] Can't install 'ms-vscode.cpptools' extension because it is not compatible with the current version of VSCodium (version 1.80.1).: Incompatible: Can't install 'ms-vscode.cpptools' extension because it is not compatible with the current version of VSCodium (version 1.80.1).
    at e.ExtensionManagementService.checkAndGetCompatibleVersion (/home/dbaros/.cursor-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/server/node/server.main.js:141:40131)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/dbaros/.cursor-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/server/node/server.main.js:141:30247
2023-08-23 20:12:25.610 [trace] CommandService#executeCommand cursor.checkonupdate
```

Looks very similar to this bug: 
https://github.com/microsoft/vscode-remote-release/issues/8837
and https://github.com/microsoft/vscode-cpptools/issues/11307

**Comment by truell20** [comment]
Does it work if you install an old version?

<img width="435" alt="Screenshot 2023-08-23 at 9 53 42 PM" src="https://github.com/getcursor/cursor/assets/4297743/dcb6b87e-7611-4afb-84a0-91283bd1a40b">

**Comment by dylan-baros** [comment]
Tried these versions of the extension:
- 1.16.3
- 1.17.3
- 1.17.4
- 1.15.4

I get the same error for each of these.

**Comment by dylan-baros** [comment]
Confirmed that the issue still exists in Cursor Version: 0.8.3

**Comment by dylan-baros** [comment]
@truell20 any update on this?

**Comment by kotborealis** [comment]
> @truell20 any update on this?

It's probably on the microsoft side, maybe you could attach your logs to [vscode-remote-release/8837](https://github.com/microsoft/vscode-remote-release/issues/8837)?

**Comment by dylan-baros** [comment]
> > @truell20 any update on this?
> 
> 
> 
> It's probably on the microsoft side, maybe you could attach your logs to [vscode-remote-release/8837](https://github.com/microsoft/vscode-remote-release/issues/8837)?

Seems specific to cursor but I can attach my logs.

**Comment by kotborealis** [comment]
> Seems specific to cursor

It's not :(

**Comment by dylan-baros** [comment]
> > Seems specific to cursor
> 
> It's not :(

You are having the issue too in vscode? I am using both the most current insiders and release versions and do not have this issue.

**Comment by kotborealis** [comment]
> > > Seems specific to cursor
> > 
> > 
> > It's not :(
> 
> You are having the issue too in vscode? I am using both the most current insiders and release versions and do not have this issue.

I had this exact issue about 2 months ago, on a brand new machine and clean vscode installation. After a few days, I no longed could reproduce it.

Then I've stumbled across it again ~2 weeks ago, and now I cannot reproduce it anymore.

It may even be an issue with vscode extension store --- cpptools downloaded directly from GH works just fine.

**Comment by Vigneshvky261** [comment]
![2024-03-06_10h37_40](https://github.com/getcursor/cursor/assets/81271717/89117fb2-ad7f-45e3-a5bd-7f90babf1349)

The issue is still reproduceable in VScode Version V.1.87.0

Version: 1.87.0 (system setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by konstk1** [comment]
Any update here? Hitting same issue in Cursor
```
Can't install 'ms-vscode.cpptools' extension because it is not compatible with the current version of Cursor (version 0.45.11, VSCode version 1.96.2).
```

**Comment by nzmora-nvidia** [comment]
I also have this problem: works with VScode when I connect to a remote container; fails with cursor when connected to a remote container over SSH ("Can't install 'ms-vscode.cpptools' extension because it is not compatible.")
