### ISSUE TITLE
Can't run any comman+k prompts or chats.

### ISSUE THREAD

**Issue by sweepy84** [getcursor/cursor#793]
Type: <b>Bug</b>

I simply cant run any any prompts. it keep erroring

The connection failed...
Please check your internet connection or use a VPN and try again. If this persists, please email hi@cursor.so.
Your request ID is e123742e-3076-42a4-9db6-d7b19f5dc6a8.

VS Code version: Cursor 0.8.4 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-08-24T22:55:42.209Z)
OS version: Darwin arm64 23.0.0
Modes:

</details>

**Comment by truell20** [comment]
Do you have a firewall that's blocking cursor.sh?

**Comment by sweepy84** [comment]
Nope - no firewall, no vpn. After upgrading to paid version (and also updating), it now doesn't give the same error but just stops midway. Opening output window I can see

`2023-09-04 16:52:29.173 [error] [unknown] Failed to fetch: ConnectError: [unknown] Failed to fetch
    at w (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4:114683)
    at Object.unary (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4:120342)
    at async Object.availableDocs (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5:561)
    at async e.AIService.availableDocs (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:21139:3488)
    at async Object.fn (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:21969:68579)
2023-09-04 16:52:29.639 [error] [unknown] Failed to fetch: ConnectError: [unknown] Failed to fetch
    at w (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4:114683)
    at Object.unary (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4:120342)
    at async Object.reportBug (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5:561)
`

**Comment by sweepy84** [comment]
It now fails every single time I run it! Very frustrating!

**Comment by AXSJ** [comment]
Having the same issue. Please help

**Comment by sweepy84** [comment]
FYI I've tested on multiple networks (e.g. iPhone hotspot) and happens regardless. I am on a Mac and have no private relay or vpn.

**Comment by dka58** [comment]
This happened to me as well after hitting my gpt-4 request limit

**Comment by bmikaili** [comment]
> This happened to me as well after hitting my gpt-4 request limit Edit: Temporarily switching to gpt-3.5 and then back to gpt-4 fixed the issue

This helped me as well!

**Comment by gtroshin** [comment]
I have the same issue. It’s very frustrating and happens so often. Any updates from developers @truell20?

**Comment by stewones** [comment]
same

**Comment by T-mac-one** [comment]
HTTP/2 setting: If you're behind a corporate proxy and having issues with Cursor Tab or Cmd K, try setting "cursor.general.disableHttp2": true in the settings.

It worked for me!!

**Comment by praneethpy** [comment]
> HTTP/2 setting: If you're behind a corporate proxy and having issues with Cursor Tab or Cmd K, try setting "cursor.general.disableHttp2": true in the settings.
> 
> It worked for me!!

how to make this changes

**Comment by gorjs3540** [comment]
I've tried the solution of @dka58 @T-mac-one, but it hasn't worked out. Please help

**Comment by gorjs3540** [comment]
I've tried the solution of @dka58 @T-mac-one, but it hasn't worked out. Please help

**Comment by mcrookrumsey** [comment]
I'm also getting the same issue after updating to pro. Switching model does not help.

**Comment by jeanlorencini** [comment]
> Também estou tendo o mesmo problema após atualizar para o pro. Trocar de modelo não ajuda. Desabilitar http2 não ajudou.



> I'm also getting the same issue after updating to pro. Switching model does not help. Disabling http2 did not help.

it seems like a general problem now
https://www.reddit.com/r/cursor/comments/1fpzfsm/cursor_down/

**Comment by antoremin** [comment]
same here, started today.

**Comment by crow-1412** [comment]
> HTTP/2 setting: If you're behind a corporate proxy and having issues with Cursor Tab or Cmd K, try setting "cursor.general.disableHttp2": true in the settings.
> 
> It worked for me!!

thank you very much!!!!

**Comment by Freddixx** [comment]
Not sure if this is helpful, but the reason might just be bot / misusage protection. 

I noticed that Cursor would completely stop working while I was travelling. Not sure if it's the country, a dodgy WiFi or whatever heuristics their edge servers are employing.

But — once I VPN'ed into my home country — everything started working like a charm again. 

Hope it helps!

**Comment by YMingF** [comment]
> Not sure if this is helpful, but the reason might just be bot / misusage protection.
> 
> I noticed that Cursor would completely stop working while I was travelling. Not sure if it's the country, a dodgy WiFi or whatever heuristics their edge servers are employing.
> 
> But — once I VPN'ed into my home country — everything started working like a charm again.
> 
> Hope it helps!

yes, after refresh vpn, the issues' gone

**Comment by pakgayaa** [comment]
Thanks! Turning off the Http2 setting solved it for me too. It was quite difficult to find the setting on my windows cursor app though.

**Comment by sharath-sidewalk** [comment]
I'm on iPhone hotspot, changing the DNS to 8.8.8.8 fixed the connection issues.
source: https://github.com/getcursor/cursor/issues/1728#issuecomment-2323274742

**Comment by src200** [comment]
I'm on iPhone hotspot, changing the DNS to 8.8.8.8 fixed connection issues.
source:https://github.com/getcursor/cursor/issues/1728#issuecomment-2323274742

**Comment by hydehk** [comment]
> I'm on iPhone hotspot, changing the DNS to 8.8.8.8 fixed connection issues. source:[#1728 (comment)](https://github.com/getcursor/cursor/issues/1728#issuecomment-2323274742)

Confirming this works for me

**Comment by HanWangyang** [comment]
> HTTP/2 setting: If you're behind a corporate proxy and having issues with Cursor Tab or Cmd K, try setting "cursor.general.disableHttp2": true in the settings.
> 
> It worked for me!!

so as me!

**Comment by imharrisonking** [comment]
Also having this issue behind a corporate firewall and proxy. Going to have to cancel Pro for now
