### ISSUE TITLE
WSL - Indexing fails on all files - ENOENT: no such file or directory, stat '/\home\...

### ISSUE THREAD

**Issue by jonstelly** [getcursor/cursor#865]
Windows 11, opening a WSL folder, trying to index the codebase.  It's stuck at 0.04% and can't index anything.  Looking at the Indexing & Retrieval output I see hundreds of the errors below.

It feels like it's a path separator / root path issue?  Opening the same codebase on Windows gets everything indexed just fine

```
2023-09-03 11:26:06.902 [error] EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/\home\jon\code\MYAPP\apps\web\src\types\next-auth.d.ts'
	at Function.c (/home/jon/.cursor-server/bin/e83fb25fe9144aa8b230e6f9ee2056e20fb24c70/out/vs/workbench/api/node/extensionHostProcess.js:101:28185)
	at Object.stat (/home/jon/.cursor-server/bin/e83fb25fe9144aa8b230e6f9ee2056e20fb24c70/out/vs/workbench/api/node/extensionHostProcess.js:101:26836)
	at async e.Indexer.u (/home/jon/.cursor-server/bin/e83fb25fe9144aa8b230e6f9ee2056e20fb24c70/extensions/cursor-retrieval/dist/main.js:1:170933)
	at async /home/jon/.cursor-server/bin/e83fb25fe9144aa8b230e6f9ee2056e20fb24c70/extensions/cursor-retrieval/dist/main.js:1:172495
	at async e.Semaphore.withSemaphore (/home/jon/.cursor-server/bin/e83fb25fe9144aa8b230e6f9ee2056e20fb24c70/extensions/cursor-retrieval/dist/main.js:1:275584)
	at async Promise.all (index 565)
	at async e.Indexer.getIterableWorkspaceFiles (/home/jon/.cursor-server/bin/e83fb25fe9144aa8b230e6f9ee2056e20fb24c70/extensions/cursor-retrieval/dist/main.js:1:172357)
	at async e.Indexer.uploadFiles (/home/jon/.cursor-server/bin/e83fb25fe9144aa8b230e6f9ee2056e20fb24c70/extensions/cursor-retrieval/dist/main.js:1:172860)
	at async /home/jon/.cursor-server/bin/e83fb25fe9144aa8b230e6f9ee2056e20fb24c70/extensions/cursor-retrieval/dist/main.js:1:168163
```

**Comment by finaldzn** [comment]
I can forming indexing doesn't work when using cursor with a WSL project

**Comment by mamolli** [comment]
adding comment for visibility, also run into this

**Comment by gugahoa** [comment]
Also running into a issue where codebase-wide suggestion does not read the codebase. Can't pinpoint if related to this because I don't know how to check these logs.

**Comment by leerob** [comment]
Thanks for opening this issue! We've moved our community support to the [Cursor Forum](https://forum.cursor.com) where you can get help from both the team and other users.

If this is a specific bug that you can still reproduce, please open a new issue with clear reproduction steps on the forum.

Thanks you!
