### ISSUE TITLE
copilot sign in export error

### ISSUE THREAD

**Issue by jkxiongxin** [getcursor/cursor#91]
When i click "sign in" button of "copilot", it report such log:
Error occurred in handler for 'sendRequestLS': Error: Connection is closed.
    at le (/tmp/.mount_gpte42YLjb/resources/app.asar/.webpack/main/index.js:8:692747)
    at Object.sendRequest (/tmp/.mount_gpte42YLjb/resources/app.asar/.webpack/main/index.js:8:694887)
    at Ne.<anonymous> (/tmp/.mount_gpte42YLjb/resources/app.asar/.webpack/main/index.js:8:828146)
    at Generator.next (<anonymous>)
    at /tmp/.mount_gpte42YLjb/resources/app.asar/.webpack/main/index.js:8:816232
    at new Promise (<anonymous>)
    at Re (/tmp/.mount_gpte42YLjb/resources/app.asar/.webpack/main/index.js:8:815977)
    at Ne.sendRequest (/tmp/.mount_gpte42YLjb/resources/app.asar/.webpack/main/index.js:8:826495)
    at node:electron/js2c/browser_init:2:97574
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81087)

**Comment by OnePieceJoker** [comment]
I also got this error. The reason for my problem is that copilot/dist/agent.js cannot be found.

My solution is:
Step 1: Find the constructor function in the lsp.ts file, print the value of the store, and get the config.json path for configuration reading. My path is: /Users/xxx/Library/Application Support/Cursor/config.json

Step 2: Clear the Cursor configuration directory obtained in the first step, in my case: rm -rf /Users/xxx/Library/Application Support/Cursor/

Step 3: Restart the project

hope it can help you

**Comment by truell20** [comment]
Should be fixed in the newest version 🙂
