### ISSUE TITLE
Can’t connect to remote ssh server after recent update

### ISSUE THREAD

**Issue by Lowpower** [getcursor/cursor#943]
[Error  - 09:29:41.91] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (/Applications/Cursor.app/Contents/Resources/app/extensions/open-remote-ssh/dist/main.js:1:797661)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Applications/Cursor.app/Contents/Resources/app/extensions/open-remote-ssh/dist/main.js:1:438101

Can you guys update more concentrated and separate the stable version and the preview version? With daily updates, every time there is an update it malfunctions and is unusable!!!

**Comment by Dicklesworthstone** [comment]
Same problem. Basically can't use it all until this is sorted out. Remote SSH is a very core feature that should be part of Cursor's automated build testing. Switched back to regular VScode for now. Would also be nice if there were an easy way to roll back to a previous version from inside the Cursor options menu.

**Comment by truell20** [comment]
Thank you all for reporting this, and apologies for this. Completely agree that SSH is core functionality and something like this should never. To address this in the future, we're going to be switching to daily alpha tester releases and weekly rollout to all users with much better testing of things like this.

To fix the immediate problem: @Dicklesworthstone @Lowpower could you post your error logs?

**Comment by truell20** [comment]
@frontierkodiak Your error message confuses me because it is getting a corrupted tar.gz file from the server. Does your error persist after retrying?

**Comment by Dicklesworthstone** [comment]
Thanks, we talked earlier today on email about this-- the problem resolved
itself before I had a chance to get the logs.

**Comment by Lowpower** [comment]
Consider first downloading and installing the remote service. If the installation fails, the client should still be compatible with the previously installed version. Currently, every time the client is upgraded, if the download or installation of the remote service fails, the client becomes unusable and cannot be rolled back.

**Comment by Lowpower** [comment]
[Trace  - 02:15:40.229] Server install command stderr:
2023-09-22 10:15:40 URL:https://cursor.blob.core.windows.net/remote-releases/0.11.4-f2c0839f42da0829d871a1e56ea2a8c8041d9370/vscode-reh-linux-x64.tar.gz [52642768/52642768] -> "vscode-server.tar.gz" [1]
tar: Skipping to next header

gzip: stdin: invalid compressed data--format violated
tar: Child returned status 1
tar: Error is not recoverable: exiting now

[Trace  - 02:15:40.229] Server install command stdout:
Downloading server from 'https://cursor.blob.core.windows.net/remote-releases/0.11.4-f2c0839f42da0829d871a1e56ea2a8c8041d9370/vscode-reh-linux-x64.tar.gz'
Error while extracting server contents
47790b19dadfb361bb906cde: start
exitCode==1==
listeningOn====
connectionToken====
logFile==/home/szq/.cursor-server/.f2c0839f42da0829d871a1e56ea2a8c8041d9370.log==
osReleaseId==ubuntu==
arch==x86_64==
platform==Linux==
tmpDir==/run/user/1001==
47790b19dadfb361bb906cde: end

[Error  - 02:15:40.231] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (/Applications/Cursor.app/Contents/Resources/app/extensions/open-remote-ssh/dist/main.js:1:797661)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Applications/Cursor.app/Contents/Resources/app/extensions/open-remote-ssh/dist/main.js:1:438101

**Comment by Lowpower** [comment]
<img width="321" alt="企业微信截图_675b8f15-3361-44da-9252-5f8143633cf9" src="https://github.com/getcursor/cursor/assets/3133734/177b4122-d182-4a66-8a11-e504e2c9ca4c">

**Comment by jamesneal** [comment]
> @frontierkodiak Your error message confuses me because it is getting a corrupted tar.gz file from the server. Does your error persist after retrying?

I believe this can happen when you have two Remote workspace windows open on to the same host.  Each workspace connects and tries to install the updated server, and they clobber each other's tarballs. 

The workaround for us users is to manually login to the remote server, and remove the cursed cursor install/tarball from .cursor-server/bin/

**Comment by Lowpower** [comment]
[Trace  - 03:20:08.112] Server install command stdout:
Downloading server from 'https://cursor.blob.core.windows.net/remote-releases/0.11.5-598d3e09a76d6c7f9e541c04c5e5df113aeb0b70/vscode-reh-linux-x64.tar.gz'
Error while extracting server contents
dd12d3429f024539c3f3dc6d: start
exitCode==1==
listeningOn====
connectionToken====
logFile==/home/szq/.cursor-server/.598d3e09a76d6c7f9e541c04c5e5df113aeb0b70.log==
osReleaseId==ubuntu==
arch==x86_64==
platform==Linux==
tmpDir==/run/user/1001==
dd12d3429f024539c3f3dc6d: end

[Error  - 03:20:08.113] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (/Applications/Cursor.app/Contents/Resources/app/extensions/open-remote-ssh/dist/main.js:1:797661)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Applications/Cursor.app/Contents/Resources/app/extensions/open-remote-ssh/dist/main.js:1:438101

**Comment by namtran3005** [comment]
Can't setup remote server when connecting to mac servers with remote ssh

[Trace  - 20:42:11.679] Server install command stdout:
Downloading server from 'https://cursor.blob.core.windows.net/remote-releases/0.11.7-db9228712f398b2885678c7e2b2644471555d3e0/vscode-reh-darwin-arm64.tar.gz'
Error while extracting server contents
ca22f65718159c934b448799: start
exitCode==1==
listeningOn====
connectionToken====
logFile==/Users/szq/.cursor-server/.db9228712f398b2885678c7e2b2644471555d3e0.log==
osReleaseId==unknown==
arch==arm64==
platform==Darwin==
tmpDir==/tmp==
ca22f65718159c934b448799: end

[Error  - 20:42:11.680] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (/Applications/Cursor.app/Contents/Resources/app/extensions/open-remote-ssh/dist/main.js:1:797661)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Applications/Cursor.app/Contents/Resources/app/extensions/open-remote-ssh/dist/main.js:1:438101

**Comment by truell20** [comment]
> I believe this can happen when you have two Remote workspace windows open on to the same host. Each workspace connects and tries to install the updated server, and they clobber each other's tarballs.

Thank you for reporting this! We will have a patch for this in the next update.

**Comment by jamesneal** [comment]
> Thank you for reporting this! We will have a patch for this in the next update.

Thank YOU.  I've really been enjoying Cursor.

**Comment by tmm1** [comment]
I ran into a similar issue:

```
[Trace  - 20:04:58.664] Server install command stderr:
https://cursor.blob.core.windows.net/remote-releases/0.12.0-411849e318e2197448b0ce3a216c258c7c641a40/vscode-reh-darwin-x64.tar.gz:
2023-10-03 13:04:58 ERROR 404: The specified blob does not exist..
```

**Comment by ydil1** [comment]
[Trace  - 00:47:14.257] Server install command stdout:
[Error  - 00:47:14.257] Error resolving authority
Error: Failed parsing install script output
	at t.installCodeServer (c:\Users\19685\AppData\Local\Programs\cursor\resources\app\extensions\open-remote-ssh\dist\main.js:1:895098)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async c:\Users\19685\AppData\Local\Programs\cursor\resources\app\extensions\open-remote-ssh\dist\main.js:1:438343
	
I am starting having similar issues these days. Can anyone help me out with this?

**Comment by davidvasandani** [comment]
```
[Trace  - 13:05:02.456] Server install command stdout:
Downloading server from 'https://cursor.blob.core.windows.net/remote-releases/0.26.1-67f5075f00c0ea3eccbed4bcff4452d742ee1f90/vscode-reh-darwin-arm64.tar.gz'
Error while extracting server contents
```

and when checking if the file exists:

```
BlobNotFoundThe specified blob does not exist. RequestId:eb19f56a-401e-005f-0feb-5cd798000000 Time:2024-02-11T13:07:39.5369514Z
```

**Comment by tals** [comment]
I was just bitten by this.

# Workaround
```
$ rm -r ~/.cursor-server/bin/
```
and restart cursor.

# Details

There's two problems in play:

One is that there is a source of corruption, likely coming from the download script being launched concurrently (as observed by @jamesneal).
Once this happens, you end up with a broken file in ~/.cursor-server/bin staging area.
I believe this is what happened to me, as in my case the downloaded tar was 227mb instead of the expected 57mb one.

Restarting cursor won't help, because it runs `wget --continue` to resume the download. So the download part just no-ops, and the thing continues to crash.

some fixes could be:
* make it recover from broken downloads by checking a hash after the download completes, and removing the file if it fails
* add some mechanism to prevent the concurrent issue (`flock`?)

**Comment by tals** [comment]
hey @truell20 , just heads up - I think this might be the source of many issues users are hitting, see #955, #959, #943.
fwiw I am still observing it after every update (it just happened to me now after updating to 0.45.2)

The bug is pretty easy to observe and reproduce

**Comment by Eggwardhan** [comment]
> 我刚刚被这个事情困扰了。
> 
> # 解决方法
> ```
> $ rm -r ~/.cursor-server/bin/
> ```
> 
> 并重新启动光标。
> 
> # 细节
> 游戏中存在两个问题：
> 
> 一是存在损坏源，可能来自同时启动的下载脚本（正如所观察到的[@jamesneal](https://github.com/jamesneal) 一旦发生这种情况，~/.cursor-server/bin 暂存区中就会出现损坏的文件。我相信我遇到的情况就是这样，因为下载的 tar 文件大小是 227mb，而不是预期的 57mb。
> 
> 重启 Cursor 也无济于事，因为它会继续运行`wget --continue`以恢复下载。所以下载部分根本没用，系统继续崩溃。 损坏基本上“持续”存在。
> 
> 一些修复方法可能是：
> 
> * 通过在下载完成后检查哈希值来恢复损坏的下载，如果失败则删除文件
> * 添加一些机制来防止并发问题（`flock`？）

I deleted the dir ,but it still not works
