### ISSUE TITLE
[BUG] Remote Dev Container Not Building

### ISSUE THREAD

**Issue by jjfantini** [getcursor/cursor#950]
OS: Mac Ventura 13.2

Starting from a new folder, fresh install. Opening directory and creating New Dev Container. Selecting ubuntu, and then running into an error:

```
[29 ms] Dev Containers 0.309.0 in VS Code 1.80.1 (598d3e09a76d6c7f9e541c04c5e5df113aeb0b70).
[28 ms] Start: Resolving Remote
[91 ms] Start: Check Docker is running
[92 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[189 ms] Server API version: 1.43
[190 ms] Start: Run: docker build -f /var/folders/s_/lf4k81t901bf6b3kgwvxxdhh0000gn/T/vsch/bootstrap-image/0.309.0/bootstrap.Dockerfile -t vsc-volume-bootstrap /var/folders/s_/lf4k81t901bf6b3kgwvxxdhh0000gn/T/vsch/bootstrap-image/0.309.0
[+] Building 0.3s (10/10) FINISHED                         docker:desktop-linux
 => [internal] load build definition from bootstrap.Dockerfile             0.0s
 => => transferring dockerfile: 607B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/base:0-a  0.2s
 => [1/5] FROM mcr.microsoft.com/devcontainers/base:0-alpine-3.16@sha256:  0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 2.51kB                                        0.0s
 => CACHED [2/5] RUN echo "@old https://dl-cdn.alpinelinux.org/alpine/v3.  0.0s
 => CACHED [3/5] RUN apk add --no-cache  git-lfs  nodejs  python3  npm  m  0.0s
 => CACHED [4/5] RUN cd && npm i node-pty                                  0.0s
 => CACHED [5/5] COPY .vscode-remote-containers /root/.vscode-remote-cont  0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:3eeaff46821dbc0abd5bbb37e6a72930170eabd1b1802  0.0s
 => => naming to docker.io/library/vsc-volume-bootstrap                    0.0s

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview
[1162 ms] Start: Run: docker run -d --mount type=volume,src=ubuntu,dst=/workspaces -v /var/run/docker.sock:/var/run/docker.sock vsc-volume-bootstrap sleep infinity
[1500 ms] Start: Run in container: /bin/sh
[1786 ms] Start: Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /workspaces/ubuntu --id-label vsc.devcontainer.volume.name=ubuntu --id-label vsc.devcontainer.volume.folder=ubuntu --log-level debug --log-format json --mount-workspace-git-root true
[2340 ms] @devcontainers/cli 0.51.1. Node.js v16.20.1. linux 6.3.13-linuxkit x64.
[2340 ms] Start: Run: git rev-parse --show-cdup
[2352 ms] Start: Run: docker ps -q -a --filter label=vsc.devcontainer.volume.name=ubuntu --filter label=vsc.devcontainer.volume.folder=ubuntu
[2407 ms] Start: Run in container: test -e "/Users/jjfantini" || (mkdir -p "$(dirname "/Users/jjfantini")" && ln -s ~ "/Users/jjfantini")
[2413 ms] 
[2413 ms] 
[2413 ms] Start: Run in container: cat <<'EOF-/tmp/devcontainer-e38fad04-9d40-44c8-813e-d10998504275.json' >/tmp/devcontainer-e38fad04-9d40-44c8-813e-d10998504275.json_1695503860235
[2418 ms] 
[2418 ms] 
[2419 ms] Start: Run in container: docker volume ls -q
[2832 ms] Start: Run in container: docker ps -q -a --filter label=vsc.devcontainer.volume.name=ubuntu --filter label=vsc.devcontainer.volume.folder=ubuntu
[2992 ms] Start: Run in container: docker ps -q -a --filter label=vsc.devcontainer.volume.name=ubuntu --filter label=vsc.devcontainer.volume.folder=ubuntu --filter label=devcontainer.config_file=/workspaces/ubuntu/.devcontainer/devcontainer.json
[3139 ms] Start: Run in container: docker ps -q -a --filter label=vsc.devcontainer.volume.name=ubuntu --filter label=vsc.devcontainer.volume.folder=ubuntu
[3298 ms] Start: Run in container: docker ps -q -a --filter label=vsc.devcontainer.volume.name=ubuntu --filter label=vsc.devcontainer.volume.folder=ubuntu
[3702 ms] Start: Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /workspaces/ubuntu --id-label vsc.devcontainer.volume.name=ubuntu --id-label vsc.devcontainer.volume.folder=ubuntu --id-label devcontainer.config_file=/workspaces/ubuntu/.devcontainer/devcontainer.json --log-level debug --log-format json --config /workspaces/ubuntu/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-e38fad04-9d40-44c8-813e-d10998504275.json --mount-workspace-git-root true
[4124 ms] @devcontainers/cli 0.51.1. Node.js v16.20.1. linux 6.3.13-linuxkit x64.
[4124 ms] Start: Run: git rev-parse --show-cdup
[4138 ms] Start: Run: docker ps -q -a --filter label=vsc.devcontainer.volume.name=ubuntu --filter label=vsc.devcontainer.volume.folder=ubuntu --filter label=devcontainer.config_file=/workspaces/ubuntu/.devcontainer/devcontainer.json
[4253 ms] Start: Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-9fa75330-2835-4404-af7d-ef682ab3641b1695503855354 --workspace-folder /workspaces/ubuntu --workspace-mount-consistency cached --id-label vsc.devcontainer.volume.name=ubuntu --id-label vsc.devcontainer.volume.folder=ubuntu --id-label devcontainer.config_file=/workspaces/ubuntu/.devcontainer/devcontainer.json --log-level debug --log-format json --config /workspaces/ubuntu/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-e38fad04-9d40-44c8-813e-d10998504275.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=ubuntu,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true
[4695 ms] @devcontainers/cli 0.51.1. Node.js v16.20.1. linux 6.3.13-linuxkit x64.
[4695 ms] Start: Run: docker buildx version
[4786 ms] github.com/docker/buildx v0.8.2 6224def4dd2c3d347eee19db595348c50d7cb491
[4787 ms] 
[4787 ms] Start: Resolving Remote
[4794 ms] Start: Run: git rev-parse --show-cdup
[4931 ms] Start: Run: docker ps -q -a --filter label=vsc.devcontainer.volume.name=ubuntu --filter label=vsc.devcontainer.volume.folder=ubuntu --filter label=devcontainer.config_file=/workspaces/ubuntu/.devcontainer/devcontainer.json
[4963 ms] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:jammy
[4996 ms] local container features stored at: /root/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/node_modules/vscode-dev-containers/container-features
[4998 ms] Start: Run: tar --no-same-owner -x -f -
[5019 ms] Start: Run: docker -v
[5045 ms] Start: Run: docker events --format {{json .}} --filter event=start
[5050 ms] Start: Starting container
[5051 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=volume,src=ubuntu,dst=/workspaces --mount type=volume,src=vscode,dst=/vscode -l vsc.devcontainer.volume.name=ubuntu -l vsc.devcontainer.volume.folder=ubuntu -l devcontainer.config_file=/workspaces/ubuntu/.devcontainer/devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/git:1"},{"remoteUser":"vscode"}] mcr.microsoft.com/devcontainers/base:jammy -c echo Container started
Container started
[5342 ms] Start: Run: docker ps -q -a --filter label=vsc.devcontainer.volume.name=ubuntu --filter label=vsc.devcontainer.volume.folder=ubuntu --filter label=devcontainer.config_file=/workspaces/ubuntu/.devcontainer/devcontainer.json
[5383 ms] Start: Run: docker inspect --type container e6fa8312b19e
[5425 ms] Start: Inspecting container
[5425 ms] Start: Run: docker inspect --type container e6fa8312b19e83fff6ebe87b9f672d215eeef825580dc88260a87ad4d498210f
[5473 ms] Start: Run in container: /bin/sh
[5478 ms] Start: Run in container: uname -m
[5564 ms] x86_64
[5564 ms] 
[5564 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[5568 ms] PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
[5568 ms] 
[5569 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'vscode' || grep -E '^vscode|^[^:]*:[^:]*:vscode:' /etc/passwd || true)
[5575 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcEnvironmentMarker'
[5579 ms] 
[5579 ms] 
[5579 ms] Exit code 1
[5580 ms] Start: Run in container: /bin/sh
[5584 ms] Start: Run in container: test ! -f '/var/devcontainer/.patchEtcEnvironmentMarker' && set -o noclobber && mkdir -p '/var/devcontainer' && { > '/var/devcontainer/.patchEtcEnvironmentMarker' ; } 2> /dev/null
[5663 ms] 
[5663 ms] 
[5663 ms] Start: Run in container: cat >> /etc/environment <<'etcEnvrionmentEOF'
[5669 ms] 
[5669 ms] 
[5669 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcProfileMarker'
[5673 ms] 
[5673 ms] 
[5673 ms] Exit code 1
[5673 ms] Start: Run in container: test ! -f '/var/devcontainer/.patchEtcProfileMarker' && set -o noclobber && mkdir -p '/var/devcontainer' && { > '/var/devcontainer/.patchEtcProfileMarker' ; } 2> /dev/null
[5679 ms] 
[5679 ms] 
[5679 ms] Start: Run in container: sed -i -E 's/((^|\s)PATH=)([^\$]*)$/\1${PATH:-\3}/g' /etc/profile || true
[5685 ms] 
[5685 ms] 
[5705 ms] Start: Run: docker inspect --type container e6fa8312b19e83fff6ebe87b9f672d215eeef825580dc88260a87ad4d498210f
[5774 ms] Start: Run: docker exec -i -u root e6fa8312b19e83fff6ebe87b9f672d215eeef825580dc88260a87ad4d498210f /bin/sh -c echo "New container started. Keep-alive process started." ; export VSCODE_REMOTE_CONTAINERS_SESSION=9fa75330-2835-4404-af7d-ef682ab3641b1695503855354 ; /bin/sh
[5776 ms] Start: Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /workspaces/ubuntu --id-label vsc.devcontainer.volume.name=ubuntu --id-label vsc.devcontainer.volume.folder=ubuntu --id-label devcontainer.config_file=/workspaces/ubuntu/.devcontainer/devcontainer.json --container-id e6fa8312b19e83fff6ebe87b9f672d215eeef825580dc88260a87ad4d498210f --log-level debug --log-format json --config /workspaces/ubuntu/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-e38fad04-9d40-44c8-813e-d10998504275.json --include-merged-configuration --mount-workspace-git-root true
[5890 ms] New container started. Keep-alive process started.
[6201 ms] @devcontainers/cli 0.51.1. Node.js v16.20.1. linux 6.3.13-linuxkit x64.
[6201 ms] Start: Run: git rev-parse --show-cdup
[6214 ms] Start: Run: docker inspect --type container e6fa8312b19e83fff6ebe87b9f672d215eeef825580dc88260a87ad4d498210f
[6266 ms] Start: Inspecting container
[6266 ms] Start: Run: docker inspect --type container e6fa8312b19e83fff6ebe87b9f672d215eeef825580dc88260a87ad4d498210f
[6334 ms] Start: Run in container: /bin/sh
[6335 ms] Start: Run in container: uname -m
[6494 ms] x86_64
[6494 ms] 
[6494 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[6498 ms] PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
[6498 ms] 
[6499 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'vscode' || grep -E '^vscode|^[^:]*:[^:]*:vscode:' /etc/passwd || true)
[6503 ms] Start: Run in container: /bin/sh
[6504 ms] Start: Run in container: stat -c %u /workspaces/ubuntu
[6630 ms] 0
[6630 ms] 
[6630 ms] Start: Run in container: chown vscode:1000 /workspaces
[6633 ms] 
[6634 ms] 
[6634 ms] Start: Run in container: chown -R vscode:1000 /workspaces/ubuntu
[6637 ms] 
[6637 ms] 
[6638 ms] Start: Updating configuration state
[6639 ms] Start: Setup shutdown monitor
[6640 ms] Forking shutdown monitor: /Users/jjfantini/.cursor/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/shutdown/shutdownMonitorProcess /var/folders/s_/lf4k81t901bf6b3kgwvxxdhh0000gn/T/vscode-remote-containers-884c52f5-dc8a-4e68-9850-3680eb61790b.sock singleContainer Debug /Users/jjfantini/Library/Application Support/Cursor/logs/20230923T214620/window2/exthost/ms-vscode-remote.remote-containers 1695503857822
[6643 ms] Start: Run in container: test -d /home/vscode/.cursor-server
[6645 ms] 
[6646 ms] 
[6646 ms] Exit code 1
[6646 ms] Start: Run in container: test -d /home/vscode/.vscode-remote
[6649 ms] 
[6649 ms] 
[6649 ms] Exit code 1
[6649 ms] Start: Run in container: test ! -f '/home/vscode/.cursor-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/home/vscode/.cursor-server/data/Machine' && { > '/home/vscode/.cursor-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[6653 ms] 
[6653 ms] 
[6654 ms] Start: Run in container: cat /home/vscode/.cursor-server/data/Machine/settings.json
[6657 ms] 
[6657 ms] cat: /home/vscode/.cursor-server/data/Machine/settings.json: No such file or directory
[6657 ms] Exit code 1
[6658 ms] Start: Run in container: test -d /home/vscode/.cursor-server/bin/598d3e09a76d6c7f9e541c04c5e5df113aeb0b70
[6660 ms] 
[6660 ms] 
[6660 ms] Exit code 1
[6660 ms] Start: Run in container: test -d /vscode/cursor-server/bin/linux-x64/598d3e09a76d6c7f9e541c04c5e5df113aeb0b70
[6663 ms] 
[6663 ms] 
[6663 ms] Exit code 1
[6663 ms] Installing VS Code Server for commit 598d3e09a76d6c7f9e541c04c5e5df113aeb0b70
[6666 ms] Start: Downloading VS Code Server
[6666 ms] 598d3e09a76d6c7f9e541c04c5e5df113aeb0b70 linux-x64 stable 
[6790 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:598d3e09a76d6c7f9e541c04c5e5df113aeb0b70/server-linux-x64/stable): HTTP 404 - Not Found
[6791 ms] Retrying to download VS Code Server.
[6910 ms] Start: Run: docker rm -f b12b70e7b2abab711c3769e3269e8a3b7735075313a5e5a8c2068a8948fcc359
[6916 ms] Error: Server returned 404
    at g (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:844:30682)
    at e.DownloadService.download (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:845:1567)

```

An ability to use github codespaces or these dev-conaitners would be great. Might have to stick with SSH.

**Comment by truell20** [comment]
Devcontainers should work now! Does this solve your issue?
