### ISSUE TITLE
Failed to download VS Code Server when using Dev Container plug-in

### ISSUE THREAD

**Issue by SanliurfaMerkez** [getcursor/cursor#976]
I am using Cursor 0.12.2 on Win10 22H2 x64, and Docker Desktop v4.22.0

When trying to attach to a running container, Cursor raises errors:

```
[26 ms] Dev Containers 0.309.0 in VS Code 1.80.1 (c54534cab10cbdfd889a68ef6ff44de284cfcdd0).
[25 ms] Start: 正在解析远程
[26 ms] Setting up container: /play6
[32 ms] Start: Run: docker inspect --type container /play6
[180 ms] Start: Run: wsl -l -v
[263 ms] Start: Run: wsl -d docker-desktop -e /bin/sh -c echo ~
[393 ms] Start: Run: wsl -d docker-desktop -e /bin/sh -c cd '/root' && /bin/sh
[415 ms] Start: Run in host: id -un
[479 ms] root
[479 ms] 
[480 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[481 ms] Start: Run in host: echo ~
[481 ms] /root
[481 ms] 
[482 ms] Start: Run in host: test -x '/root/.vscode-remote-containers/bin/c54534cab10cbdfd889a68ef6ff44de284cfcdd0/node'
[483 ms] 
[483 ms] 
[483 ms] Exit code 1
[483 ms] Start: Run in host: test -x '/root/.cursor-server/bin/c54534cab10cbdfd889a68ef6ff44de284cfcdd0/node'
[485 ms] 
[485 ms] 
[485 ms] Exit code 1
[485 ms] Start: Run in host: uname -s
[487 ms] Linux
[487 ms] 
[487 ms] Start: Run in host: uname -m
[488 ms] x86_64
[488 ms] 
[488 ms] Start: Run in host: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[488 ms] PRETTY_NAME="Docker Desktop"
[489 ms] 
[489 ms] Start: Downloading VS Code Server
[489 ms] c54534cab10cbdfd889a68ef6ff44de284cfcdd0 linux-x64 stable 
[1133 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:c54534cab10cbdfd889a68ef6ff44de284cfcdd0/server-linux-x64/stable): HTTP 404 - Not Found
[1133 ms] Retrying to download VS Code Server.
[1464 ms] Could not connect to WSL.
[1464 ms] Server returned 404
[1465 ms] Start: Check Docker is running
[1465 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[1586 ms] Server API version: 1.43
[1587 ms] Start: Run: C:\Users\jz\AppData\Local\Programs\cursor\Cursor.exe c:\Users\jz\.cursor\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js set-up --container-id e376cf74b2f334e98c95d0c1b42b5b685543f221352320438aa7347319ec8330 --user-data-folder c:\Users\jz\AppData\Roaming\Cursor\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-2c224114-c14e-494b-b6fb-683325a906691696744648860 --log-level debug --log-format json --default-user-env-probe loginInteractiveShell --skip-post-create
[1794 ms] @devcontainers/cli 0.51.1. Node.js v16.17.1. win32 10.0.19045 x64.
[1794 ms] Start: Run: docker buildx version
[2042 ms] github.com/docker/buildx v0.11.2-desktop.1 986ab6afe790e25f022969a18bc0111cff170bc2
[2042 ms] 
[2042 ms] Start: Run: docker inspect --type container e376cf74b2f334e98c95d0c1b42b5b685543f221352320438aa7347319ec8330
[2151 ms] Start: Inspecting container
[2151 ms] Start: Run: docker inspect --type container e376cf74b2f334e98c95d0c1b42b5b685543f221352320438aa7347319ec8330
[2267 ms] Start: Run in container: /bin/sh
[2292 ms] Start: Run in container: uname -m
[2426 ms] x86_64
[2426 ms] 
[2426 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2429 ms] NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
[2429 ms] 
[2430 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2435 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcEnvironmentMarker'
[2437 ms] 
[2437 ms] 
[2437 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcProfileMarker'
[2439 ms] 
[2439 ms] 
[2450 ms] Start: Run: C:\Users\jz\AppData\Local\Programs\cursor\Cursor.exe c:\Users\jz\.cursor\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js read-configuration --container-id e376cf74b2f334e98c95d0c1b42b5b685543f221352320438aa7347319ec8330 --log-level debug --log-format json --include-merged-configuration --mount-workspace-git-root true
[2667 ms] @devcontainers/cli 0.51.1. Node.js v16.17.1. win32 10.0.19045 x64.
[2667 ms] Start: Run: docker inspect --type container e376cf74b2f334e98c95d0c1b42b5b685543f221352320438aa7347319ec8330
[2787 ms] Start: Inspecting container
[2787 ms] Start: Run: docker inspect --type container e376cf74b2f334e98c95d0c1b42b5b685543f221352320438aa7347319ec8330
[2901 ms] Start: Run in container: /bin/sh
[2926 ms] Start: Run in container: uname -m
[3118 ms] x86_64
[3118 ms] 
[3118 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[3122 ms] NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
[3122 ms] 
[3122 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[3126 ms] Start: Run in container: test -d /root/.cursor-server
[3128 ms] 
[3128 ms] 
[3128 ms] Start: Run in container: test ! -f '/root/.cursor-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.cursor-server/data/Machine' && { > '/root/.cursor-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[3129 ms] 
[3129 ms] 
[3129 ms] Exit code 1
[3130 ms] Start: Run in container: cat /root/.cursor-server/data/Machine/settings.json
[3131 ms] 
[3131 ms] cat: /root/.cursor-server/data/Machine/settings.json: No such file or directory
[3131 ms] Exit code 1
[3132 ms] Start: Run in container: test -d /root/.cursor-server/bin/c54534cab10cbdfd889a68ef6ff44de284cfcdd0
[3133 ms] 
[3133 ms] 
[3133 ms] Exit code 1
[3133 ms] Installing VS Code Server for commit c54534cab10cbdfd889a68ef6ff44de284cfcdd0
[3134 ms] Start: Downloading VS Code Server
[3134 ms] c54534cab10cbdfd889a68ef6ff44de284cfcdd0 linux-x64 stable 
[3965 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:c54534cab10cbdfd889a68ef6ff44de284cfcdd0/server-linux-x64/stable): HTTP 404 - Not Found
[3966 ms] Retrying to download VS Code Server.
[4108 ms] Error: Server returned 404
    at h (vscode-file://vscode-app/c:/Users/jz/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:844:30614)
    at e.DownloadService.download (vscode-file://vscode-app/c:/Users/jz/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:845:1567)
```

I saw "Failed to download VS Code Server", "Error: Server returned 404" ......

Doing the same operation on VSCode on the same PC is fine, but Cursor showed these errors

**Comment by dstamou** [comment]
Same issue here running on a Mac. The URL for downloading the vs code server is faulty. Doing the same on VSCode works fine as @SanliurfaMerkez mentioned

**Comment by gaohang89** [comment]
same issue... can anybody help!

**Comment by memeke** [comment]
Same here:

```bash
[1158 ms] Installing VS Code Server for commit 598d3e09a76d6c7f9e541c04c5e5df113aeb0b70
[1159 ms] Start: Downloading VS Code Server
[1159 ms] 598d3e09a76d6c7f9e541c04c5e5df113aeb0b70 linux-x64 stable 
[1717 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:598d3e09a76d6c7f9e541c04c5e5df113aeb0b70/server-linux-x64/stable): HTTP 404 - Not Found
[1718 ms] Retrying to download VS Code Server.
[2127 ms] Error: Server returned 404
    at g (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:844:30682)
    at e.DownloadService.download (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:845:1567)
```

The commit does not exist when I try to open the [update url](https://update.code.visualstudio.com/commit:598d3e09a76d6c7f9e541c04c5e5df113aeb0b70/server-linux-x64/stable) on the browser.

<img width="1070" alt="Screenshot 2023-10-25 at 20 03 48" src="https://github.com/getcursor/cursor/assets/46603327/64536bef-ee1d-44b7-851b-ae73c990169b">

Mac M2: Sonoma (14.0 (23A344))

**Comment by waracci** [comment]
Same here:

```bash
[1158 ms] Installing VS Code Server for commit 598d3e09a76d6c7f9e541c04c5e5df113aeb0b70
[1159 ms] Start: Downloading VS Code Server
[1159 ms] 598d3e09a76d6c7f9e541c04c5e5df113aeb0b70 linux-x64 stable 
[1717 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:598d3e09a76d6c7f9e541c04c5e5df113aeb0b70/server-linux-x64/stable): HTTP 404 - Not Found
[1718 ms] Retrying to download VS Code Server.
[2127 ms] Error: Server returned 404
    at g (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:844:30682)
    at e.DownloadService.download (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:845:1567)
```

The commit does not exist when I try to open the [update url](https://update.code.visualstudio.com/commit:598d3e09a76d6c7f9e541c04c5e5df113aeb0b70/server-linux-x64/stable) on the browser.

<img width="1070" alt="Screenshot 2023-10-25 at 20 03 48" src="https://github.com/getcursor/cursor/assets/46603327/64536bef-ee1d-44b7-851b-ae73c990169b">

Mac M2: Sonoma (14.0 (23A344))

**Comment by emorling** [comment]
Same here

**Comment by safurrier** [comment]
Same issue here

**Comment by SValab** [comment]
Exactly the same here. Works in vscode.

**Comment by omurayuki** [comment]
Same here

**Comment by YutaOkoshi** [comment]
Any updates?

**Comment by mjcetx** [comment]
Same here

**Comment by jjfantini** [comment]
I think its gonna be a bit before Dev COntainers and GitHub CodeSPaces are supported, probably in the 0.30.... versions.

The team is prioritizing AI features for development first.

**Comment by TexicoNotMexico** [comment]
Same here

**Comment by SValab** [comment]
I hope it supports it soon. I am conflicted in purchasing a subscription as it's of no use since most of my work is done in containers.

**Comment by chnsh** [comment]
Same issue!

**Comment by bauschri** [comment]
same issue on mac os

**Comment by jgilfoil** [comment]
As someone that works primarily on windows for my home work where I can trial a product like this, I can't really use it without dev containers support.

**Comment by TexicoNotMexico** [comment]
I solved this problem by installing the [extension version of Cursor](https://github.com/Helixform/CodeCursor) on VSCode

**Comment by tianrendong** [comment]
same issue on Mac OS

**Comment by marcus302** [comment]
Same here.

**Comment by beowolx** [comment]
same! i bough the pro subscription and now can't use it for my work 😅

**Comment by Shoshi-the-Glass** [comment]
Same here.

**Comment by AlbertBaubleDeem** [comment]
Fix it please. Definitely a dealbreaker for subscriptions at the moment.

**Comment by raffareis** [comment]
Same here

**Comment by mpalazz** [comment]
This is the only thing stopping me from complete adoption.

**Comment by mjcetx** [comment]
This seems to be working now! Apart from one issue - docker compose linked devcontainers are still failing - anyone experiencing the same problem?

Sent from Outlook for iOS<https://aka.ms/o0ukef>

Michael Clancy
AI Scientist
e-therapeutics plc
Paddington Central
London
W2 6BD, UK
T  
+44 020 4551 8888
www.etherapeutics.co.uk
Please see here for our Privacy Statement
e-therapeutics plc is registered in England & Wales No. 4304473 Registered Office: 4B,
Floor 4, 4 Kingdom Street, London, W2 6BD, UK VAT registration No.
GB923838112.

This e-mail and the information it contains are confidential and may be privileged. If you
have received this e-mail in error, please reply to the sender, indicating it was received in
error and destroy this e-mail and any information attached to it. In addition, you should not
copy it for any purpose, disclose its contents to any other person or take action in reliance
on the message or any of the information. Thank you for your help and understanding.
 
________________________________

**Comment by truell20** [comment]
Hey! Devcontainers support was added in January 😃 so marking this as closed. For anyone who has more specific issues, could you please open another ticket?  (e.g. @mjcetx I'll open one for yours).

**Comment by leohxj** [comment]
same issue on Mac OS

**Comment by Ankitz007** [comment]
Stuck here when using dev container plugin:

```
[1971 ms] Installing VS Code Server for commit 58b91712431381a1b75817cd3437cee35dddcb30
[1972 ms] Start: Run in container: /bin/sh
[1974 ms] Start: Downloading VS Code Server
[1974 ms] 58b91712431381a1b75817cd3437cee35dddcb30 linux-arm64 stable 
````

**Comment by ericlau1987** [comment]
Same issue on Mac M1

**Comment by miketang84** [comment]
same issue for Cursor 0.40.3 on my WSL.

**Comment by simontuck** [comment]
Same issue for 0.40.4 on Mac M3

**Comment by jes-work** [comment]
Same problem in 0.40.4 on Windows 11. Seems to be a faulty url to VS Code Server updates.

**Comment by joelong01** [comment]
same issue running on my Mac.  uninstalled the Dev Container Extension and reinstalled it.  that was a royal PITA (why do you have to manually download it and drag and drop it onto the extension pane instead of just searching for it and installing it from the pane).  Still doesn't work.

**Comment by johnshew** [comment]
hey @joelong01, did you find a way to resolve this? i'm hitting the same issue opening a dev container that works fine in vs code.

**Comment by victorkwak** [comment]
In case it's helpful, I ran into this 404 issue while using:
- I'm using Windows client
- Cursor 0.41.3 
- Local WSL distro (Ubuntu) 
I got past this issue by deleting `.cursor-server` from the distro and letting Cursor set that up again.

**Comment by joelong01** [comment]
> hey @joelong01, did you find a way to resolve this? i'm hitting the same issue opening a dev container that works fine in vs code.

@johnshew: I did not, i'm running natively to "make progress".

**Comment by densuke** [comment]
same here

```
[2024-12-18T01:37:42.436Z] Stop (156 ms): Run in container: apk info | grep -e '^libstdc++$' || (apk update && apk add libstdc++)
[2024-12-18T01:37:42.926Z] Failed to download VS Code Server (https://cursor.blob.core.windows.net/remote-releases/a846435528b4b760494a836f96f0739889253530/vscode-reh-linux-alpine.tar.gz): HTTP 404 - The specified blob does not exist.
[2024-12-18T01:37:42.926Z] Retrying to download VS Code Server.
[2024-12-18T01:37:43.533Z] Stop (1249 ms): Downloading VS Code Server
[2024-12-18T01:37:43.537Z] Error: Server returned 404
    at f (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1212:49047)
    at C.download (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1213:1915)
```

**Comment by wrawka** [comment]
Same here, deleting `.cursor-server` didn't help either.
Progress log stops here indefinitely:
```
[1014 ms] Installing VS Code Server for commit 3611c5390c448b242ab97e328493bb8ef7241e60
[1014 ms] Start: Run in container: /bin/sh
[1015 ms] Start: Downloading VS Code Server
[1015 ms] 3611c5390c448b242ab97e328493bb8ef7241e60 linux-arm64 stable
```

**Comment by jgilfoil** [comment]
This seems to be an issue with Alpline. For my devcontainers that were using alpine base images, i swapped them out to debian based images and they work. It sounds like alpine support is in 'preview' or something.

**Comment by kaiiak** [comment]
same issue

**Comment by incureforce** [comment]
Hm ok, but i hope alpine works soon. It is my go to choice for containers 😆
