### ISSUE TITLE
Handshake Failed during codebase indexing

### ISSUE THREAD

**Issue by T-Ev** [getcursor/cursor#981]
After the latest cursor update on windows 11, indexing no longer works for me. I get the following error:

2023-10-10 17:42:20.367 [info] Creating merkle client.
2023-10-10 17:42:20.367 [info] Done creating merkle client.
2023-10-10 17:42:20.367 [info] Doing a startup handshake.
2023-10-10 17:42:20.367 [info] Creating merkle client.
2023-10-10 17:42:20.367 [info] Done creating merkle client.
2023-10-10 17:42:20.391 [info] Finished initializing merkle tree in 24.003599882125854 ms.
2023-10-10 17:42:20.399 [info] Doing the initial handshake with hash: ---< My Hash >----
2023-10-10 17:42:41.447 [error] Handshake failed:
2023-10-10 17:42:41.450 [error] ConnectError: [unavailable] connect ETIMEDOUT 10.0.2.98:443
	at a.from (c:\Users\tjero\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:1106978)
	at e.connectErrorFromNodeReason (c:\Users\tjero\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:1091956)
	at ClientHttp2Session.o (c:\Users\tjero\AppData\Local\Programs\cursor\resources\app\extensions\cursor-retrieval\dist\main.js:2:1084022)
	at ClientHttp2Session.emit (node:events:513:28)
	at emitClose (node:internal/http2/core:1079:10)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-10-10 17:42:41.450 [error] Handshake failed.
2023-10-10 17:42:41.450 [info] Finished updating repository.

![image](https://github.com/getcursor/cursor/assets/26844451/f6d25abf-8c72-4009-ad57-47bca8dbc6cf)

**Comment by psychaos999** [comment]
hi, same here

**Comment by whatif-dev** [comment]
Same here for our team. They should have a status update so users don't bombard them with the same comments. Just a suggestion @Cursor team.

**Comment by akegaviar** [comment]
same here on macOS Ventura 13.6 and Cursor:

```
Version: 0.12.3
VSCode Version: 1.80.1
Commit: 3c1a98b47d7c2e903562d2b756fc9cafe4915fb0
Date: 2023-10-08T22:51:40.884Z
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.6.0
```

**Comment by truell20** [comment]
Apologies about this. Aware of the issue and investigating.

**Comment by akegaviar** [comment]
btw just noticed that previously imported docs are also gone. Probably the same issue.
<img width="543" alt="SCR-20231012-kz1" src="https://github.com/getcursor/cursor/assets/10195782/e8712a92-315c-4aff-ad17-ad095459b4de">

**Comment by milesian01** [comment]
Same thing here. New user on a fresh Windows 10 install in a tightly controlled company environment. Is this possibly linked to strict firewall settings or SSL certificate issues?

**Comment by rendyfebry** [comment]
Seem like still a problem

**Comment by stico-best** [comment]
same, so how can I solve this problem?

**Comment by rune32bit** [comment]
Same, reinstalling seemed to solve it

**Comment by Verminous** [comment]
same here :'(

**Comment by dickermoshe** [comment]
Please use windows store or allow disabled ssl

**Comment by janniks** [comment]
Yep, +1
Indexing seems to not be working (Chat look fine though), even after a reboot and fresh reinstall of Cursor 

_on macOS 13.5.2 (22G91)_
```
Version: 0.12.3
VSCode Version: 1.80.1
Commit: 3c1a98b47d7c2e903562d2b756fc9cafe4915fb0
Date: 2023-10-08T22:51:40.884Z
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by NourEldin-Osama** [comment]
same here

**Comment by mrtcntn** [comment]
sam here

**Comment by AI4lifegpt3** [comment]
same issue

**Comment by NourEldin-Osama** [comment]
@truell20 is there is any update?

**Comment by siko-ki** [comment]
Same here....Mac Sonoma Version 14.0

**Comment by wardnath** [comment]
Same +1 macOS Sonoma 

```

Version: 0.12.3
VSCode Version: 1.80.1
Commit: 3c1a98b47d7c2e903562d2b756fc9cafe4915fb0
Date: 2023-10-08T22:51:40.884Z (1 wk ago)
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 23.1.0
```

**Comment by 37chandler** [comment]
+1 

Version: 0.12.3
VSCode Version: 1.80.1
Commit: 3c1a98b47d7c2e903562d2b756fc9cafe4915fb0
Date: 2023-10-08T22:51:40.884Z
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 23.0.0

**Comment by milesian01** [comment]
> Please use windows store or allow disabled ssl

Thank you for the suggestions. A couple of follow-up questions:

When you mention "use windows store", do you mean importing the necessary certificates into the Windows certificate store? If so, could you provide a brief guide or point me to a resource on how to do this?

For "allow disabled ssl", are you suggesting to disable SSL verification or allow connections without SSL? Could you provide steps or guidance on how to implement this?

Any additional details would be greatly appreciated.

**Comment by vquigley** [comment]
Also seeing this issue

```

Version: 0.12.3
VSCode Version: 1.80.1
Commit: 3c1a98b47d7c2e903562d2b756fc9cafe4915fb0
Date: 2023-10-08T22:51:40.884Z (2 wks ago)
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by mbtre** [comment]
Same here:


`
Version: 0.13.0
VSCode Version: 1.83.1
Commit: e4dfb063f60fbbb889ccfa43d4d2ba3b118c8830
Date: 2023-10-22T01:31:20.010Z (2 days ago)
Electron: 25.8.4
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
`

Currently I am only able to use Cursor Nightly. There I do not have that problem. Still quite annoying..

**Comment by FelixGraeber** [comment]
Same here. 
Mac 14.0 (23A344)

**Comment by eduwass** [comment]
ugh, happening here too

**Comment by truell20** [comment]
Ack, just discovered this thread. Please let me know if you still see issues. If you do see issues, it'd be super helpful if you could go to "Output" and "Indexing & Retrieval" and post your logs.

<img width="520" alt="Screenshot 2023-11-02 at 7 33 45 PM" src="https://github.com/getcursor/cursor/assets/42977

<img width="415" alt="Screenshot 2023-11-02 at 7 33 54 PM" src="https://github.com/getcursor/cursor/assets/4297743/f7e03c93-13db-42b4-91bf-210ce7d0f993">
43/440e1897-76db-4371-8972-8ee8343ebfbe">

**Comment by truell20** [comment]
@bfmcneill Was your node_modules in your `.gitignore`?

**Comment by mbtre** [comment]
Here's a brief update: I haven't experienced the handshake-issue recently. However, indexing remains inconsistent—sometimes it's successful, other times it's not. I currently have both the stable and nightly versions of the cursor installed, and unfortunately, neither is indexing properly.


Currently both nightly:
![image](https://github.com/getcursor/cursor/assets/128634931/f555bcf8-68b3-49bc-a060-65d5bff187cf)

And normal cursor do not index:

![image](https://github.com/getcursor/cursor/assets/128634931/ea60a534-3640-4c5b-9635-6e16c2f752e9)

Both remain in this state.


```
Version: 0.14.0
VSCode Version: 1.83.1
Commit: edbb49b5481d7fddb9a1115a33617591f39a6d00
Date: 2023-11-02T20:00:53.580Z
Electron: 25.8.4
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```

```
Version: 0.14.3-nightly
VSCode Version: 1.83.1
Commit: 925acadcebd35f04de6ba07812ae72f54cbe5659
Date: 2023-11-05T22:41:35.619Z
Electron: 25.8.4
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```
This repository is relatively small. Ensuring that the indexing functions reliably would be greatly appreciated! :)

**Comment by akegaviar** [comment]
Same issue here. No handshake issues now, but the indexing just doesn't work. It either never completes, never starts, or shows as completed but then only portions of a repo are indexed (doesn't seem to depend on the repo size btw).

You can easily have the indexing go to 100% in a minute and then cursor not being able to answer question of functions that are there in the repo and cursor simply not aware of their existence.

**Comment by sualehasif** [comment]
(the people getting the issue around Nov were fixed by several major stability fixes we released. since then we have had not many complaints.)

i will release a debug build to you by posting a link on that issue. hopefully that will help me figure out why this is getting stuck for you.

**Comment by darinkishore** [comment]
Thank you @sualehasif , much appreciated! Hope the debug build will help.

**Comment by anurag619mo** [comment]
I am still facing the same issue. Looks like similar issue, was there any fix for this issue ?
<img width="1123" alt="Screenshot 2024-07-16 at 4 11 38 PM" src="https://github.com/user-attachments/assets/c051250c-9896-489e-9514-befe04d6520b">

**Comment by Balance8** [comment]
Bump, same issue here 

Version: 0.37.1
VSCode Version: 1.89.1
Commit: bee043c1bb0095dab94043787985ccfc7cc38e50
Date: 2024-07-14T03:18:35.590Z
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin x64 23.5.0

**Comment by mathieufrh** [comment]
Same for me here:

About:

```
Version: 0.37.1
VSCode Version: 1.89.1
Commit: bee043c1bb0095dab94043787985ccfc7cc38e50
Date: 2024-07-14T03:18:35.590Z (1 wk ago)
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin x64 23.5.0
```

Log:

```
2024-07-24 14:00:14.107 [info] Repo client: syncing embeddings with backend:  https://repo42.cursor.sh
2024-07-24 14:00:14.107 [info] Creating merkle client.
2024-07-24 14:00:14.107 [info] Done creating merkle client.
2024-07-24 14:00:14.108 [info] Doing a startup handshake.
2024-07-24 14:00:14.108 [info] Finished initializing merkle tree in 344.77525520324707 ms.
2024-07-24 14:00:14.109 [info] Doing the initial handshake with hash: 0625bb56b5c60159341e1fda143c0e06d580eecefac86046fd7321626016d725
2024-07-24 14:00:14.134 [info] Handshake start
2024-07-24 14:00:19.009 [info] Handshake start
2024-07-24 14:00:27.013 [info] Handshake start
2024-07-24 14:00:28.199 [info] Search by message took 86.11463689804077ms for query "hello"
2024-07-24 14:00:28.200 [info] Search by sha took 37.799203872680664ms for query "hello"
2024-07-24 14:00:31.554 [info] Search by message took 81.87645721435547ms for query ""
2024-07-24 14:00:31.555 [info] Search by sha took 45.47870111465454ms for query ""
2024-07-24 14:00:43.017 [info] Handshake start
2024-07-24 14:01:15.027 [info] Handshake start
2024-07-24 14:02:19.031 [info] Handshake start
2024-07-24 14:02:25.366 [warning] Error computing full high level folder description. Ignoring. [unavailable] connect ETIMEDOUT 3.231.38.91:443
2024-07-24 14:03:29.367 [error] Handshake failed:
2024-07-24 14:03:29.368 [error] Error: timeout in handshake with retry
    at t.RepoClientMultiplexer.handshakeWithRetry (/home/xyz/.cursor-server/cli/servers/Stable-bee043c1bb0095dab94043787985ccfc7cc38e50/server/extensions/cursor-retrieval/dist/main.js:2:993323)
    at y.getServerStatus (/home/xyz/.cursor-server/cli/servers/Stable-bee043c1bb0095dab94043787985ccfc7cc38e50/server/extensions/cursor-retrieval/dist/main.js:2:1008226)
    at y.startIndexingRepository (/home/xyz/.cursor-server/cli/servers/Stable-bee043c1bb0095dab94043787985ccfc7cc38e50/server/extensions/cursor-retrieval/dist/main.js:2:1010471)
2024-07-24 14:03:29.369 [error] Handshake failed.
2024-07-24 14:03:29.370 [info] Indexing job successfully done or aborted.
```

**Comment by anurag619mo** [comment]
Got a reply on this issue, pasting the forum link below.
https://forum.cursor.com/t/copilot-autocomplete-not-working-on-another-machine/6632/4

**Comment by Boardtale** [comment]
I got the issue and jsut downloaded this software. @home, no proxies, nothing. Bad first impression :P 
It was working morning, turned off computer before finish, resumed and this I got.

**Comment by LaRiffle** [comment]
Restarting Cursor solved it for me :)

**Comment by BHK0** [comment]
> Restarting Cursor solved it for me :)

@LaRiffle you are genius man, that fixed it for me lol

**Comment by KinetoCebPac** [comment]
@LaRiffle  how to restart Cursor?

**Comment by BHK0** [comment]
> @LaRiffle how to restart Cursor?

@KinetoCebPac just close it and open it again, that worked for me

**Comment by ameryzhu** [comment]
> Restarting Cursor solved it for me :)

restarting cursor worked for me too.

**Comment by menguzat** [comment]
didn't work for me after the last update.

**Comment by NikhilSehgal123** [comment]
Yep didn't work for me either, still looks like a problem

**Comment by Crysis21** [comment]
I updated and now I have this issue. handshake failed or it will just freeze at setting up indexing...

**Comment by Maxime-Fleurant** [comment]
Same doesn't  work

**Comment by 13220887675** [comment]
Believe me. No restarting  no reinstalling，by deleting redundant project files, it will change from "Handshake failed" to 100%.

**Comment by timothyericsson** [comment]
> Believe me. No restarting no reinstalling，by deleting redundant project files, it will change from "Handshake failed" to 100%.

It just hangs at 100% for me but still not working. It's been down for a few hours now.

**Comment by 13220887675** [comment]
> Same doesn't work



> Believe me. No restarting no reinstalling，by deleting redundant project files, it will change from "Handshake failed" to 100%.



> > Believe me. No restarting no reinstalling，by deleting redundant project files, it will change from "Handshake failed" to 100%.
> 
> It just hangs at 100% for me but still not working. It's been down for a few hours now.

Yes, the same for me. Don't wait. Please check your project, maybe some files confuse cursor.

**Comment by 13220887675** [comment]
> > Believe me. No restarting no reinstalling，by deleting redundant project files, it will change from "Handshake failed" to 100%.Believe me. No restarting no reinstalling，by deleting redundant project files, it will change from "Handshake failed" to 100%.相信我。不重启不重新安装，通过删除多余的项目文件，它会从 “Handshake failed” 变为 100%。
> 
> It just hangs at 100% for me but still not working. It's been down for a few hours now.It just hangs at 100% for me but still not working. It's been down for a few hours now.它对我来说只是挂在 100% 但仍然不起作用。它已经关闭了几个小时。

try your others projects. If others normal but only this failed, then do same things as me.

**Comment by timothyericsson** [comment]
> > > Believe me. No restarting no reinstalling，by deleting redundant project files, it will change from "Handshake failed" to 100%.Believe me. No restarting no reinstalling，by deleting redundant project files, it will change from "Handshake failed" to 100%.相信我。不重启不重新安装，通过删除多余的项目文件，它会从 “Handshake failed” 变为 100%。
> > 
> > 
> > It just hangs at 100% for me but still not working. It's been down for a few hours now.It just hangs at 100% for me but still not working. It's been down for a few hours now.它对我来说只是挂在 100% 但仍然不起作用。它已经关闭了几个小时。
> 
> try your others projects. If others normal but only this failed, then do same things as me.

I just have one project lol. It was working fine this morning. Something broke on their end. I shouldn't have to tinker with stuff on my end. I just paid for pro too lmao

**Comment by timothyericsson** [comment]
Pleased to report it started working again. Have fun building everyone. Accelerate!

**Comment by boshd** [comment]
Deleting the index, then syncing again fixed it for me for anyone still facing the issue.

**Comment by joacim-boive** [comment]
I had the same issue - what ever I did I couldn't get indexing to work and the inline chat wouldn't work either.

This was for my work computer - no problems at home, both on macOS.

Until I disabled http2 at work: 
![Screenshot 2024-10-07 at 18 14 52](https://github.com/user-attachments/assets/e358ed88-123a-449e-a43f-747065f813ce)

Now everything works fine.

**Comment by julian70400** [comment]
Worked nice 2 or 3 months ago.. suddenly, same problem.

**Comment by SamirMagdyI** [comment]
same here

**Comment by bubblegumsoldier** [comment]
same here, as everybody been posting in the last few hours I guess its a server issue?

**Comment by zenmindhacker** [comment]
Must be a server issue! I've tried everything, multiple codebases, disabling HTTP/2, restarting. Nothing working, and the logs just show no response from index server:

2024-10-08 11:24:02.824 [info] Repo client: syncing embeddings with backend:  https://repo42.cursor.sh
2024-10-08 11:24:02.974 [info] Creating merkle client.
2024-10-08 11:24:02.974 [info] Done creating merkle client.
2024-10-08 11:24:02.974 [info] Doing a startup handshake.
2024-10-08 11:24:03.001 [info] Finished initializing merkle tree in 27.311667025089264 ms.
2024-10-08 11:24:03.003 [info] Doing the initial handshake with hash: 631ef3667acb8030de78eb42f27f607f8e3e08c93115a2e416fd93d810895314
2024-10-08 11:24:03.007 [info] Handshake start
2024-10-08 11:24:07.012 [info] Handshake start
2024-10-08 11:24:13.355 [info] Handshake start
2024-10-08 11:24:23.740 [info] Handshake start
2024-10-08 11:24:44.185 [info] Handshake start
2024-10-08 11:25:18.628 [info] Handshake start

**Comment by cromulus** [comment]
Adding to the chorus.

**Comment by pinion** [comment]
still the same issue.
[error] Handshake failed:
2024-10-08 21:18:50.828 [error] Error: timeout in handshake with retry
	at t.RepoClientMultiplexer.handshakeWithRetry (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:826553)
	at async w.getServerStatus (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:841881)
	at async w.startIndexingRepository (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:2:844181)

can someone at Cursor at least acknowledge the issue?

**Comment by zenmindhacker** [comment]
All looks good now.

**Comment by 0b501e7e** [comment]
can a brother get an index? 🥺👉👈

**Comment by julian70400** [comment]
![image](https://github.com/user-attachments/assets/9bbc400f-d9c5-4064-ad0a-e2dae5cc25e4)
All seem to be find now !

**Comment by julian70400** [comment]
by the way, Indexing seem to block fine working of SFTP, it's impossible to synchronize anything while indexing.

**Comment by lastmjs** [comment]
Indexing not working for me as of right now, Handshake failed

**Comment by PizBernina** [comment]
+1

![Image](https://github.com/user-attachments/assets/2b5280b9-8372-45e1-a467-1e82c455f846)

**Comment by tonyrewin** [comment]
2 days cannot use cursor - same same troubles, handshake does not go

`
2025-01-23 13:45:43.352 [info] Indexing job successfully done or aborted.
2025-01-23 13:45:43.353 [info] Creating merkle client.
2025-01-23 13:45:43.353 [info] Done creating merkle client.
2025-01-23 13:45:43.353 [info] Doing a startup handshake.
2025-01-23 13:45:43.369 [info] Finished initializing merkle tree in 12.734625000000051 ms.
2025-01-23 13:45:43.369 [info] Doing the initial handshake with hash: 94e593728d1f428d5e74bc0878a850539660d3e37b5172b6b1680ecef4f82b9c
2025-01-23 13:45:43.370 [info] Handshake start
2025-01-23 13:45:45.748 [warning] Retrying handshake with timeout 4000. Error:  [invalid_argument] Error
2025-01-23 13:45:45.748 [info] Handshake start
2025-01-23 13:45:49.878 [warning] Retrying handshake with timeout 8000. Error:  [invalid_argument] Error
2025-01-23 13:45:49.878 [info] Handshake start
2025-01-23 13:45:58.010 [warning] Retrying handshake with timeout 16000. Error:  [invalid_argument] Error
2025-01-23 13:45:58.011 [info] Handshake start
2025-01-23 13:46:14.141 [warning] Retrying handshake with timeout 32000. Error:  [invalid_argument] Error
2025-01-23 13:46:14.141 [info] Handshake start
2025-01-23 13:46:46.278 [warning] Retrying handshake with timeout 64000. Error:  [invalid_argument] Error
2025-01-23 13:46:46.278 [info] Handshake start
2025-01-23 13:47:50.416 [warning] Retrying handshake with timeout 128000. Error:  [invalid_argument] Error
2025-01-23 13:47:50.417 [error] Handshake failed:
2025-01-23 13:47:50.418 [error] Error: timeout in handshake with retry
	at t.RepoClientMultiplexer.handshakeWithRetry (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:4:814544)
	at async v.getServerStatus (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:4:831171)
	at async v.startIndexingRepository (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:4:833862)
2025-01-23 13:47:50.418 [error] Handshake failed.
2025-01-23 13:47:50.419 [info] Indexing job successfully done or aborted.

`

**Comment by jeffminim** [comment]
Right now. Unable to conduct Codebase Indexing.
