### ISSUE TITLE
Cannot SSH on Linux version. 

### ISSUE THREAD

**Issue by iHusk** [getcursor/cursor#991]
Trying to SSH to a machine on my local network from a Ubuntu 22.04 machine. Continually get cannot connect to host errors due to a .tar.gz not being able to be found? See the error at the bottom. I have tried deleting the .cursor-server directory on host machine, reinstalling cursor on both machines. I CAN ssh through command line and I can SSH through VS Code, but not cursor. I CAN SSH the opposite way (Windows 10 Machine -> Ubuntu) just fine, so error seems to be on the Linux version . 

annot find path 
'C:\Users\xxx\.cursor-server\bin\0.12.3-3c1a98b47d7c2e903562d2b756fc9cafe4915fb0\vscode-server.tar.gz' because it 
does not exist.
At C:\Users\xxx\.cursor-server\install\3c1a98b47d7c2e903562d2b756fc9cafe4915fb0.ps1:57 char:1
+ del vscode-server.tar.gz
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\xxx\...e-server.tar.gz:String) [Remove-Item], ItemNotFoundEx 
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
 
Invoke-RestMethod : BlobNotFoundThe specified blob does not exist.
RequestId:f59c93ff-b01e-0074-5c60-fd5754000000
Time:2023-10-12T23:06:00.5857405Z
At C:\Users\xxx\.cursor-server\install\3c1a98b47d7c2e903562d2b756fc9cafe4915fb0.ps1:65 char:1
+ Invoke-RestMethod @REQUEST_ARGUMENTS
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

[Trace  - 23:06:00.603] Server install command stdout:

    Directory: C:\Users\xxx\.cursor-server

Mode                 LastWriteTime         Length Name                                                                 
----                 -------------         ------ ----                                                                 
d-----        10/12/2023   6:03 PM                install                                                              

Error while installing the server binary

[Error  - 23:06:00.604] Error resolving authority
Error: Failed parsing install script output
	at t.installCodeServer (/tmp/.mount_cursoroMNZkd/resources/app/extensions/open-remote-ssh/dist/main.js:1:814560)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /tmp/.mount_cursoroMNZkd/resources/app/extensions/open-remote-ssh/dist/main.js:1:438101

**Comment by divyenduz** [comment]
Might be related, in my case the `node` binary in the .cursor-server folder wasn't working! So, I replaced it with a working one and it worked for me

Logs from the remote machine

```
[nix-shell:~/.cursor-server/bin/0.12.0-411849e318e2197448b0ce3a216c258c7c641a40]$ ./node --version
bash: ./node: cannot execute: required file not found

[nix-shell:~/.cursor-server/bin/0.12.0-411849e318e2197448b0ce3a216c258c7c641a40]$ uname -a
Linux nixos 6.5.7-orbstack-00109-gd8500ae6683d #1 SMP Fri Oct 13 01:28:33 UTC 2023 aarch64 GNU/Linux

[nix-shell:~/.cursor-server/bin/0.12.0-411849e318e2197448b0ce3a216c258c7c641a40]$ file node
node: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=f01764bcc204c2fb3be31e4319f13a68d48912dc, with debug_info, not stripped

[nix-shell:~/.cursor-server/bin/0.12.0-411849e318e2197448b0ce3a216c258c7c641a40]$ which node
/run/current-system/sw/bin/node

[nix-shell:~/.cursor-server/bin/0.12.0-411849e318e2197448b0ce3a216c258c7c641a40]$ mv node _node

[nix-shell:~/.cursor-server/bin/0.12.0-411849e318e2197448b0ce3a216c258c7c641a40]$ cp /run/current-system/sw/bin/node .

[nix-shell:~/.cursor-server/bin/0.12.0-411849e318e2197448b0ce3a216c258c7c641a40]$ node --version
v18.17.1

[nix-shell:~/.cursor-server/bin/0.12.0-411849e318e2197448b0ce3a216c258c7c641a40]$ ./node --version
v18.17.1
```
